homeassistant:
  name: Luzern
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: -21
  unit_system: metric
  time_zone: Asia/Bangkok
  auth_providers:
    - type: homeassistant
  auth_mfa_modules:
    - type: totp
      name: "Authenticator app"
    - type: notify
      message: 'PIN: {}'
  customize: !include customize.yaml
  packages: !include_dir_named packages/

browser:

cast:
  media_player:
    - host: !secret candy_ip
    - host: !secret biscuit_ip
    - host: !secret doughnut_ip

# cloud:

config:

conversation:

device_tracker:
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: pe
  - platform: icloud3
    username: !secret icloud_username
    password: !secret icloud_password
    tracking_method: famshr
    # tracking_method: fmf
    track_devices:
      - pesiphone7plus > phumin@sawasdee.org, pe.jpg
      - pesipadmini5 > phumin@sawasdee.org, pe.jpg
      - juesiphone6splus > malaiwan@gamil.com, jue.jpg
      - juesipadmini4 > malaiwan@gmail.com, jue.jpg
      - sinbad > phumin@sawasdee.org, pe.jpg
      - benjysiphone6 > benjy.p@gmail.com, pe.jpg
    group: family
    unit_of_measurement: km
    distance_method: calc
    gps_accuracy_threshold: 100
    inzone_interval: '5 min'
    stationary_inzone_interval: '1 min'
    stationary_still_time: '3 min'
    old_location_threshold: '2 min'
    ignore_gps_accuracy_inzone: False
    travel_time_factor: .6
    log_level: debug, eventlog
  
discovery:

# duckdns:
#   domain: phumin
#   access_token: !secret duckdnstoken

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# hacs:
#   token: !secret github_token
#   sidepanel_title: Community
#   sidepanel_icon: "mdi:alpha-c-box"
#   appdaemon: "False"
#   python_script: "False"
#   theme: "False"

group: !include_dir_merge_named group/

history:

http:
  base_url: !secret base_url

hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: false

ios:

logbook:

logger:
  default: critical
  logs:
    homeassistant.components.automation: debug
    homeassistant.components.camera.xiaomi: debug
    homeassistant.components.device_tracker: critical
    homeassistant.components.http: warning
    homeassistant.components.ios: debug
    homeassistant.components.lights: debug
    homeassistant.components.recorder: debug
    homeassistant.components.script: debug
    homeassistant.components.sensor: debug
    homeassistant.components.sensor.command_line: critical
    homeassistant.components.sensor.speedtest: warning
    homeassistant.components.sensoer.systemmonitor: debug
    homeassistant.components.switch.command_line: critical
    homeassistant.components.tplink: critical
    custom_components.notify.gntp: debug
    custom_components.sensor.places: debug  

map:

media_player:
  - platform: apple_tv
    name: "Apple TV"
    host: !secret apple_tv_ip
    login_id: !secret apple_tv_login_id
  - platform: denonavr
    name: "Denon"
    host: !secret denon_ip
    show_all_sources: True
    timeout: 10
  - platform: dunehd
    name: Dune
    host: !secret dune_ip
  - platform: kodi
    name: "Kodi"
    host: !secret kodi_ip
    username: !secret my_username
    password: !secret my_password
    turn_off_action: quit
  - platform: itunes
    name: iTunes
    host: !secret itunes_ip
  - platform: mpd
    name: "MPD MacBook Pro"
    host: !secret itunes_ip
    port: 6600

# media_extractor:

mobile_app:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret my_password
  client_id: home-assistant
  discovery: true
  discovery_prefix: homeassistant

notify:
  - platform: ios
    name: iOSApp
    target: 'PHUMIN'
  - platform: nfandroidtv
    name: tv
    host: !secret kodi_ip
  - platform: kodi
    name: kodi
    host: !secret kodi_ip
    port: 8080
    username: !secret my_username
    password: !secret my_password
  - platform: smtp
    name: email
    server: !secret smtp_server
    port: !secret smtp_port
    sender: !secret smtp_sender
    recipient: phumin@sawasdee.org
  - platform: group
    name: television
    services:
      - service: tv
      - service: kodi
  - platform: gntp
    name: growl
    hostname: !secret itunes_ip
    password: !secret my_password
  - platform: group
    name: pe
    services:
      - service: mobile_app_pes_iphone_7_plus
      - service: mobile_app_pes_ipad_mini_5
  - platform: group
    name: jue
    services:
      - service: mobile_app_jues_iphone_6s_plus
      - service: mobile_app_jues_ipad_mini_4

recorder:
  purge_keep_days: 10
  purge_interval: 1
  # db_url: !secret db_url
  # exclude:

panel_iframe:
  configurator:
    title: 'Editor'
    icon: mdi:wrench
    url: !secret url_configurator
  glances:
    title: 'Statistics'
    icon: mdi:speedometer
    url: !secret url_stats

# python_scripts:

script: !include scripts.yaml

stream:

sun:

system_health:

tts:
  - platform: google_translate
    base_url: !secret base_url
    cache: true
    cache_dir: /config/www/tts
    time_memory: 300
    service_name: google_say

updater:

upnp:
  sensors: true
  local_ip: !secret mqtt_broker
  port_mapping: true
  ports:
    hass: 7575
    8080: 8080

wake_on_lan:

zeroconf:

