homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: -21
  unit_system: metric
  time_zone: Asia/Bangkok
  customize: !include config/customise.yaml
  packages: !include_dir_named packages

http:
  api_password: !secret my_password
  base_url: !secret base_url
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

config:
conversation:
discovery:
# shopping_list:
sun:
updater:
zeroconf:

light:
  platform: hue
  host: !secret hue_ip
  allow_unreachable: true
  allow_hue_groups: false

tts:
  platform: google
  cache: true
  cache_dir: /tts
  time_memory: 300

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret my_password
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "hass/status"
    payload: "Online"
  will_message:
    topic: "hass/status"
    payload: "Offline"

frontend:
  themes:
    red:
      primary-color: "#C0392B"
    green:
      primary-color: "#2ECC71"
    blue:
      primary-color: "#3498DB"
    darkred:
      primary-color: "#601D16"
    darkgreen:
      primary-color: "#1ABC9C"
    darkblue:
      primary-color: "#2C3E50"

apple_tv:
  name: "Apple TV"
  host: !secret apple_tv_ip
  login_id: !secret apple_tv_login_id
  credentials: 8BE9E6B8815126A9:5C6D48EDCF40E6CEF3551198D43BD98C541455F472731A5288F4813BDA6ED27C

# weather:
#   - platform: openweathermap
#     api_key: !secret openweather_api
#     latitude: !secret latitude_home
#     longitude: !secret longitude_home

ifttt:
  key: !secret ifttt_key

# automation: !include_dir_merge_list automation/
device_tracker: !include config/device_tracker.yaml
group: !include_dir_merge_named group/
media_player: !include config/media_player.yaml
notify: !include config/notify.yaml
scene: !include config/scene.yaml
script: !include config/script.yaml
# sensor: !include_dir_merge_list sensor/

# history: !include config/logs.yaml
# logbook: !include config/logs.yaml
# recorder: !include config/recorder.yaml
history:
logbook:
recorder:
  purge_days: 10
  db_url: !secret db_url

logger:
  default: critical
  logs:
    # homeassistant.components.automation: debug
    homeassistant.components.automation: info
    # homeassistant.components.device_tracker.icloud: debug
    homeassistant.components.device_tracker: critical
    homeassistant.components.http: warning
    homeassistant.components.input_boolean: debug
    homeassistant.components.input_select: debug
    homeassistant.components.ios: debug
    homeassistant.components.mqtt: info
    # homeassistant.components.media_player.mpd: debug
    homeassistant.components.media_player: critical
    # homeassistant.components.media_player.denon: debug
    # homeassistant.components.media_player.denonavr: debug
    homeassistant.components.notify: warning
    homeassistant.components.proximity: critical
    homeassistant.components.script: debug
    homeassistant.components.sensor: debug
    homeassistant.components.sensor.command_line: warning
    homeassistant.components.sensor.speedtest: warning
    homeassistant.components.shell_command: debug
    homeassistant.components.switch: debug
    homeassistant.components.switch.command_line: critical
