homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 8
  unit_system: metric
  time_zone: Asia/Bangkok
  customize: !include config/customise.yaml
  packages:
    alarmclock: !include packages/alarmclock.yaml
    broadlink: !include packages/broadlink.yaml
    # foscam: !include packages/foscam.yaml
    homemode: !include packages/homemode.yaml
    ios: !include packages/ios.yaml
    offline: !include packages/offline.yaml
    zone: !include packages/zone.yaml

http:
  api_password: !secret my_password
  base_url: !secret base_url
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

recorder:
  purge_days: 30
  db_url: !secret db_url
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.ram_use
      - sensor.cpu_use
      - sensor.solar_angle
      - sun.sun
      - sensor.time
      # - sensor.common_room_temperature
      - camera.current_location_jue
      - camera.current_location_pe

config:
conversation:
discovery:
frontend:
sun:
updater:
zeroconf:

light:
  platform: hue
  host: 192.168.1.22
  allow_unreachable: true
  # allow_in_emulated_hue: false
  allow_hue_groups: false

tts:
  platform: google

ifttt:
  key: !secret ifttt_key

ffmpeg:
  ffmpeg_bin: /bin/ffmpeg

automation: !include_dir_merge_list automation/
# binary_sensor: !include config/binary_sensor.yaml
camera: !include config/camera.yaml
device_tracker: !include config/device_tracker.yaml
group: !include_dir_merge_named group/
history: !include config/history.yaml
# input_boolean: !include config/input_boolean.yaml
# input_select: !include config/input_select.yaml
logbook: !include config/logbook.yaml
media_player: !include config/media_player.yaml
notify: !include config/notify.yaml
proximity: !include config/proximity.yaml
scene: !include config/scene.yaml
script: !include config/script.yaml
sensor: !include_dir_merge_list sensor/
# switch: !include config/switch.yaml
weblink: !include config/weblink.yaml
# zone: !include_dir_list zone/

# critical, fatal, error, warning, warn, info, debug, notset
logger:
  default: critical
  # default: warning
  logs:
    homeassistant.components.automation: debug
    # homeassistant.components.history: debug
    homeassistant.components.http: warning
    homeassistant.components.input_boolean: debug
    homeassistant.components.input_select: debug
    homeassistant.components.ios: debug
    # homeassistant.components.logbook: debug
    homeassistant.components.notify: debug
    # homeassistant.components.proximity: debug
    homeassistant.components.script: debug
    homeassistant.components.sensor: debug
    # homeassistant.components.switch: debug

mqtt:
  broker: !secret cloudmqtt_broker
  port: !secret cloudmqtt_port
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password
  discovery: true
  discovery_prefix: homeassistant
