###########################################################
#
#   iCloud3 Configuration Parameters
#
#   These parameters will override those specified in the HA
#   configuration.yaml file. They can be used to change the
#   iCloud3 operations without restarting HA. To do this,
#   change the parameter in this file and select
#   Event Log > Actions > Restart iC3
#
###########################################################

# --Track Devices Parameters-------------------------------
devices:
 - device_name: pesiphone13pro
   name: Pe's iPhone 13 Pro
   email: phumin@sawasdee.org
   picture: pe.jpg
 - device_name: pesipadpro
   name: Pe's iPad Pro
   email: phumin@sawasdee.org
   picture: pe.jpg
 - device_name: pepe
   name: Pe's Macbook Pro
   email: phumin@sawasdee.org
   picture: pe.jpg
 - device_name: juesiphonexsmax
   name: Jue's iPhone XS Max
   email: malaiwan@gmail.com
   picture: jue.jpg
 - device_name: juesipadmini4
   name: Jue's iPad Mini 4
   email: malaiwan@gmail.com
   picture: jue.jpg

# --Zone/Tracking Parameters--------------------------------
inzone_interval: 5 min
max_interval: 4 hrs
center_in_zone: true
stationary_inzone_interval: 1 min
stationary_still_time: 3 min
stationary_zone_offset: 1, 0
travel_time_factor: .6
distance_method: calc

# --Display Parameters--------------------------------------
# display_zone_fname: True
unit_of_measurement: km
time_format: 24
display_text_as:
 - phumin@sawasdee.org > phumin@sawasdee.org
 - malaiwan@gmail.com > malaiwan@gmail.com
 - benjy.p@gmail.com > benjy.p@gmail.com

# --Accuracy Parameters-------------------------------------
gps_accuracy_threshold: 100
ignore_gps_accuracy_inzone: True
old_location_threshold: 3 min

# --Waze Parameters-----------------------------------------
# distance_method: waze
# waze_region: US
# waze_min_distance: 1
# waze_max_distance: 9999
# waze_realtime: False

# -- Debug/Logging Parameters-------------------------------
log_level: debug
# log_level: debug+intervalcalc
# log_level: debug+rawdata
