homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: -21
  unit_system: metric
  time_zone: Asia/Bangkok
  auth_providers:
    - type: homeassistant
  auth_mfa_modules:
    - type: totp
      name: "Authenticator app"
    - type: notify
      message: 'PIN: {}'
  customize: !include customize.yaml
  packages: !include_dir_named packages/

browser:

cast:
  media_player:
    - host: !secret candy_ip
    - host: !secret biscuit_ip
    - host: !secret doughnut_ip

cloud:

config:

conversation:

discovery:

# duckdns:
#   domain: phumin
#   access_token: !secret duckdnstoken

ffmpeg:

history:

http:
  base_url: !secret base_url
  server_port: 8123

# homekit:
#   filter:
#     exclude_domains:
#       - input_boolean
#       - script
#     exclude_entities:
#       - sensor.jues_ipad_mini_2_battery_level
#       - sensor.jues_ipad_mini_2_battery_state
#       - sensor.jues_iphone_6s_plus_battery_level
#       - sensor.jues_iphone_6s_plus_battery_state
#       - sensor.pes_ipad_mini_2_battery_level
#       - sensor.pes_ipad_mini_2_battery_state
#       - sensor.pes_iphone_7_plus_battery_level
#       - sensor.pes_iphone_7_plus_battery_state
#       - sensor.battery_juesipadmini2
#       - sensor.battery_juesiphone6splus
#       - sensor.battery_pesipadmini2
#       - sensor.battery_pesiphone7plus
#       - light.discoagroup
#       - light.discoagroupeven
#       - light.discoagroupodd
#       - sensor.processor_use
#       - sensor.memory_use_percent
#       - sensor.bedroom_temperature_mean
#       - sensor.bedroom_humidity_mean
#       - sensor.common_room_temperature_mean
#       - sensor.common_room_humidity_mean
#       - sensor.firstfloor_temperature_mean
#       - sensor.firstfloor_humidity_mean
#       - sensor.earth
#       - sensor.earth_toner_black
#       - sensor.earth_drum_black
#       - sensor.earth_output_tray_0
#       - sensor.earth_tray_1
#       - sensor.samsung_m267x_287x_series_192168144
#       - sensor.samsung_m267x_287x_series_192168144_toner_black
#       - sensor.samsung_m267x_287x_series_192168144_drum_black
#       - sensor.samsung_m267x_287x_series_192168144_output_tray_0
#       - sensor.samsung_m267x_287x_series_192168144_tray_1

hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: false

# ifttt:
#   key: !secret ifttt_key

ios:

logbook:

logger:
  default: critical
  logs:
    homeassistant.components.automation: debug
    homeassistant.components.device_tracker: critical
    # homeassistant.components.device_tracker.life360: debug
    homeassistant.components.http: warning
    # homeassistant.components.http.ban: warning
    homeassistant.components.input_boolean: debug
    homeassistant.components.input_select: debug
    # homeassistant.components.ios: debug
    homeassistant.components.lights.hue: debug
    # homeassistant.components.mqtt: debug
    homeassistant.components.media_player: critical
    # homeassistant.components.notify: debug
    homeassistant.components.notify.gntp: debug
    homeassistant.components.owntracks: debug
    homeassistant.components.proximity: critical
    homeassistant.components.recorder: debug
    homeassistant.components.script: debug
    homeassistant.components.sensor: debug
    homeassistant.components.sensor.command_line: critical
    homeassistant.components.glances2: debug
    homeassistant.components.sensor.speedtest: warning
    # :homeassistant.components.mqtt: debug
    homeassistant.components.sensoer.systemmonitor: debug
    homeassistant.components.switch.command_line: critical
    # homeassistant.components.switch.broadlink: debug
    # homeassistant.components.tts: debug

map:

media_extractor:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret my_password
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1.1
  discovery: true
  discovery_prefix: homeassistant

owntracks:

recorder:
  purge_keep_days: 15
  purge_interval: 1
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - camera
      - input_select
      - input_slider
      - input_boolean
      - proximity
      - scene
      - script
      - sensor
      - zone
    entities:
      - remote.apple_tv
      - sun.sun
  include:
    domains:
      - binary_sensor
      - counter
      - device_tracker
      - media_player
      - switch
    entities:
      - script.callisto_restart
      - script.ganymede_restart
      - script.hometheatre_turnoff
      - script.hometheatre_turnon
      - sensor.bedroom_humidity_mean
      - sensor.bedroom_temperature_mean
      - sensor.callisto_humidity
      - sensor.callisto_temperature
      - sensor.common_room_humidity_mean
      - sensor.common_room_temperature_mean
      - sensor.first_floor_humidity_mean
      - sensor.first_floor_temperature_mean
      - sensor.mimas_humidity
      - sensor.mimas_temperature
      - sensor.pandora_humidity
      - sensor.pandora_temperature

panel_iframe:
  configurator:
    title: 'Editor'
    icon: mdi:wrench
    url: !secret configurator_url
  glances:
    title: 'Statistics'
    icon: mdi:speedometer
    url: !secret stats_url

stream:

sun:

system_health:

tplink:

tts:
  - platform: google
    base_url: !secret base_url
    cache: true
    cache_dir: /config/www/tts
    time_memory: 300

updater:

wake_on_lan:

zeroconf:

device_tracker: !include conf/device_tracker.yaml
group: !include_dir_merge_named group/
media_player: !include conf/media_player.yaml
notify: !include conf/notify.yaml
script: !include scripts.yaml
# automation: !include automations.yaml
