homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: -21
  unit_system: metric
  time_zone: Asia/Bangkok
  customize: !include config/customise.yaml
  packages: !include_dir_named packages/
  customize_glob:
    light.*:
      custom_ui_state_card: state-card-custom-ui
    cover.*:
      custom_ui_state_card: state-card-custom-ui

http:
  api_password: !secret my_password
  base_url: !secret base_url
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
  # ip_ban_enabled: True
  # login_attempts_threshold: 3

browser:
cloud:
config:
conversation:
discovery:
history:
logbook:
map:
# python_script:
# shopping_list:
sun:
updater:
wake_on_lan:
zeroconf:

apple_tv:
  name: "Apple TV"
  host: !secret apple_tv_ip
  login_id: !secret apple_tv_login_id
  credentials: 8BE9E6B8815126A9:5C6D48EDCF40E6CEF3551198D43BD98C541455F472731A5288F4813BDA6ED27C

frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-mini-media-player.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-mini-media-player_es5.html

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

homekit:
  pincode: '666-88-999'

hue:
  bridges:
    - host: !secret hue_ip
      filename: phue.conf
      allow_unreachable: true
      allow_in_emulated_hue: false
      allow_hue_groups: false

ifttt:
  key: !secret ifttt_key

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret my_password
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1
  discovery: false
  discovery_prefix: homeassistant

recorder:
  purge_keep_days: 30
  purge_interval: 1
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - camera
      - input_select
      - input_slider
      - input_boolean
      - proximity
      - scene
      - script
      - sensor
      - zone
    entities:
      - binary_sensor.bedroom_colder
      - binary_sensor.bedroom_warmer
      - binary_sensor.common_room_colder
      - binary_sensor.common_room_warmer
      - binary_sensor.first_floor_colder
      - binary_sensor.first_floor_warmer
      - binary_sensor.saturn_disks_are_hot
      - binary_sensor.saturn_temperature_down
      - binary_sensor.saturn_temperature_up
      - remote.apple_tv
      - sun.sun
  include:
    domains:
      - binary_sensor
      - counter
      - device_tracker
      - media_player
      - switch
    entities:
      - script.callisto_restart
      - script.ganymede_restart
      - script.hometheatre_turnoff
      - script.hometheatre_turnon
      - sensor.average_disk_temperature
      - sensor.bedroom_humidity_mean
      - sensor.bedroom_temperature_mean
      - sensor.callisto_humidity
      - sensor.callisto_temperature
      - sensor.common_room_humidity_mean
      - sensor.common_room_temperature_mean
      - sensor.first_floor_humidity_mean
      - sensor.first_floor_temperature_mean
      - sensor.maximum_disk_temperature
      - sensor.mimas_humidity
      - sensor.mimas_temperature
      - sensor.pandora_humidity
      - sensor.pandora_temperature

shell_command:
  line_pe: '/config/command/line_pe "{{ message }}"'
  line_jue: '/config/command/line_jue "{{ message }}"'
  line_both: '/config/command/line_both "{{ message }}"'
  # denon_checking: '/config/command/denon_checking'

tts:
  - platform: google
    cache: true
    cache_dir: /tts
    time_memory: 300

device_tracker: !include config/device_tracker.yaml
group: !include_dir_merge_named group/
media_player: !include config/media_player.yaml
notify: !include config/notify.yaml
scene: !include config/scene.yaml
script: !include config/script.yaml

logger:
  default: critical
  logs:
    homeassistant.components.automation: info
    # homeassistant.components.device_tracker.icloud: debug
    homeassistant.components.device_tracker: critical
    homeassistant.components.http: warning
    homeassistant.components.input_boolean: debug
    homeassistant.components.input_select: debug
    homeassistant.components.ios: debug
    homeassistant.components.mqtt: info
    # homeassistant.components.media_player.mpd: debug
    homeassistant.components.media_player: critical
    homeassistant.components.notify: warning
    # homeassistant.components.notify.command_line: debug
    homeassistant.components.proximity: critical
    homeassistant.components.script: debug
    homeassistant.components.sensor: debug
    homeassistant.components.sensor.command_line: warning
    homeassistant.components.sensor.speedtest: warning
    homeassistant.components.shell_command: debug
    homeassistant.components.switch: debug
    homeassistant.components.switch.command_line: critical
