homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 8
  unit_system: metric
  time_zone: Asia/Bangkok
  customize: !include config/customise.yaml

http:
  api_password: !secret api_password
  base_url: !secret base_url
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key

recorder:
  purge_days: 60
  db_url: !secret db_url

frontend:
config:
updater:
discovery:
conversation:
sun:
zeroconf:

light:
  platform: hue
  host: 192.168.1.22
  allow_unreachable: true
  allow_hue_groups: true

tts:
  platform: google

ifttt:
  key: !secret ifttt_key

automation: !include_dir_merge_list automation/
camera: !include config/camera.yaml
device_tracker: !include config/device_tracker.yaml
group: !include_dir_merge_named group/
history: !include config/history.yaml
input_boolean: !include config/input_boolean.yaml
input_select: !include config/input_select.yaml
logbook: !include config/logbook.yaml
media_player: !include config/media_player.yaml
notify: !include config/notify.yaml
scene: !include config/scene.yaml
script: !include config/script.yaml
sensor: !include config/sensor.yaml
switch: !include config/switch.yaml
weblink: !include config/weblink.yaml
zone: !include_dir_list zone/

# critical, fatal, error, warning, warn, info, debug, notset
logger:
  default: critical
  logs:
    homeassistant.components.automation: debug
    # homeassistant.components.camera: debug
    # homeassistant.components.device_tracker: debug
    homeassistant.components.groups: debug
    homeassistant.components.history: debug
    homeassistant.components.input_boolean: debug
    homeassistant.components.input_select: debug
    homeassistant.components.ios: debug
    homeassistant.components.logbook: debug
    # homeassistant.components.mqtt: debug
    homeassistant.components.notify: debug
    # homeassistant.components.recorder: debug
    # homeassistant.components.scene: debug
    homeassistant.components.script: debug
    homeassistant.components.sensor: debug
    homeassistant.components.switch: debug
    # homeassistant.components.zone: debug

ios:
  # push:
  #   categories:
  #     - name: Alarm
  #       identifier: 'ALARM'
  #       actions:
  #         - identifier: 'SOUND_ALARM'
  #           title: 'Sound Alarm'
  #           activationMode: 'background'
  #           authenticationRequired: yes
  #           destructive: yes
  #           behavior: 'default'
  #         - identifier: 'SILENCE_ALARM'
  #           title: 'Silence Alarm'
  #           activationMode: 'background'
  #           authenticationRequired: yes
  #           destructive: no
  #           behavior: 'textInput'
  #           textInputButtonTitle: 'Silencio!'
  #           textInputPlaceholder: 'Placeholder'

mqtt:
  broker: !secret cloudmqtt_broker
  port: !secret cloudmqtt_port
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password
  discovery: true
  discovery_prefix: homeassistant
