homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: -21
  unit_system: metric
  time_zone: Asia/Bangkok
  customize: !include config/customise.yaml
  packages: !include_dir_named packages

http:
  api_password: !secret my_password
  base_url: !secret base_url
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

config:
conversation:
discovery:
frontend:
sun:
updater:
zeroconf:

light:
  platform: hue
  host: !secret hue_ip
  allow_unreachable: true
  allow_hue_groups: false

tts:
  platform: google
  cache: true
  cache_dir: /tts
  time_memory: 300

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret my_password
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1
  discovery: true
  discovery_prefix: homeassistant

ifttt:
  key: !secret ifttt_key

automation: !include_dir_merge_list automation/
device_tracker: !include config/device_tracker.yaml
group: !include_dir_merge_named group/
history: !include config/logs.yaml
logbook: !include config/logs.yaml
media_player: !include config/media_player.yaml
notify: !include config/notify.yaml
recorder: !include config/recorder.yaml
scene: !include config/scene.yaml
script: !include config/script.yaml
sensor: !include_dir_merge_list sensor/

logger:
  default: critical
  logs:
    homeassistant.components.automation: critical
    homeassistant.components.device_tracker: critical
    homeassistant.components.http: warning
    homeassistant.components.input_boolean: debug
    homeassistant.components.input_select: debug
    homeassistant.components.ios: debug
    homeassistant.components.mqtt: debug
    homeassistant.components.media_player: critical
    homeassistant.components.notify: warning
    homeassistant.components.proximity: debug
    homeassistant.components.script: debug
    homeassistant.components.sensor: debug
    homeassistant.components.shell_command: debug
    homeassistant.components.switch: debug
