homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 8
  unit_system: metric
  time_zone: Asia/Bangkok
  customize: !include config/customise.yaml
  packages:
    alarmclock: !include packages/alarmclock.yaml
    broadlink: !include packages/broadlink.yaml
    daylight: !include packages/daylight.yaml
    denon: !include packages/denon.yaml
    foscam: !include packages/foscam.yaml
    homemode: !include packages/homemode.yaml
    ios: !include packages/ios.yaml
    itunes: !include packages/itunes.yaml
    offline: !include packages/offline.yaml
    server: !include packages/server.yaml
    zone: !include packages/zone.yaml

http:
  api_password: !secret my_password
  base_url: !secret base_url
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

config:
conversation:
discovery:
frontend:
sun:
updater:
zeroconf:

light:
  platform: hue
  host: !secret hue_ip
  allow_unreachable: true
  # allow_in_emulated_hue: false
  allow_hue_groups: false

tts:
  platform: google

ifttt:
  key: !secret ifttt_key

ffmpeg:
  ffmpeg_bin: /bin/ffmpeg

automation: !include_dir_merge_list automation/
device_tracker: !include config/device_tracker.yaml
group: !include_dir_merge_named group/
history: !include config/history.yaml
logbook: !include config/logbook.yaml
media_player: !include config/media_player.yaml
notify: !include config/notify.yaml
recorder: !include config/recorder.yaml
scene: !include config/scene.yaml
script: !include config/script.yaml
# switch: !include config/switch.yaml
sensor: !include_dir_merge_list sensor/

# critical, fatal, error, warning, warn, info, debug, notset
logger:
  default: critical
  # default: warning
  logs:
    homeassistant.components.automation: debug
    homeassistant.components.http: warning
    homeassistant.components.input_boolean: debug
    homeassistant.components.input_select: debug
    homeassistant.components.ios: debug
    homeassistant.components.media_player: critical
    homeassistant.components.notify: debug
    homeassistant.components.proximity: critical
    homeassistant.components.script: debug
    homeassistant.components.sensor: debug
    homeassistant.components.switch: debug

mqtt:
  broker: !secret cloudmqtt_broker
  port: !secret cloudmqtt_port
  username: hass
  password: !secret my_password
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1
