homeassistant:
  name: Luzern
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: -21
  unit_system: metric
  time_zone: Asia/Bangkok
  external_url: http://phumin.synology.me:7575/
  internal_url: http://192.168.1.99:8123/
  auth_providers:
    - type: homeassistant
  auth_mfa_modules:
    - type: totp
      name: "Authenticator app"
    - type: notify
      message: 'PIN: {}'
  customize: !include customize.yaml
  packages: !include_dir_named packages/

automation: !include automations.yaml

apple_tv:
  - host: !secret apple_tv_ip
    login_id: !secret apple_tv_login_id
    # name: ATV
    start_off: True
    credentials: !secret apple_tv_credentials

browser:

# cast:
#   media_player:
#     - host: !secret candy_ip
#     - host: !secret biscuit_ip
#     - host: !secret doughnut_ip

camera:
  - platform: generic
    name: BoxieB1
    still_image_url: !secret boxieb1_still_image_url
    stream_source: !secret boxieb1_stream_source
    username: !secret boxie_username
    password: !secret my_password
    authentication: basic
    verify_ssl: false
  - platform: generic
    name: BoxieB2
    still_image_url: !secret boxieb2_still_image_url
    stream_source: !secret boxieb2_stream_source
    username: !secret boxie_username
    password: !secret my_password
    authentication: basic
    verify_ssl: false
  - platform: generic
    name: "Foscam Garage"
    stream_source: !secret foscam_white_mjpeg_url
    still_image_url: !secret foscam_white_still_image_url
    username: !secret my_username
    password: !secret my_password
    authentication: basic
    verify_ssl: false
  - platform: generic
    name: "Mini Cam"
    still_image_url: !secret esp32cam_still_image_url
    stream_source: !secret esp32cam_stream_source
    authentication: basic
    verify_ssl: false

config:

conversation:

counter:
  bedroom:
    name: "Bedroom Reboot Counter"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  commonroom:
    name: "Common Room Reboot Counter"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  firstfloor:
    name: "Frst Floor Reboot Counter"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  wled:
    name: "WLED Reboot Counter"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  wled2:
    name: "WLED2 Reboot Counter"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  bedroom2:
    name: "Bedroom2 Reboot Counter"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  foscammotion:
    name: "Foscam Motion Activation"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false

device_tracker:
  # - platform: tomato
  #   host: !secret deeper_ip
  #   username: !secret my_username
  #   password:  !secret my_password
  #   http_id: !secret tomato_http_id_1
  #   interval_seconds: 240
  #   consider_home: 180
  #   new_device_defaults:
  #     track_new_devices: true
  - platform: icloud3
    username: !secret icloud_username
    password: !secret icloud_password
    # tracking_method: fmf
    tracking_method: famshr
    # group: family
    consider_home: 180
    new_device_defaults:
      track_new_devices: true

discovery:

# duckdns:
#   domain: phumin
#   access_token: !secret duckdnstoken

frontend:
  themes: !include_dir_merge_named themes

ffmpeg:
  # ffmpeg_bin: /usr/bin/ffmpeg

history:

http:
  # base_url: !secret base_url
# api_password: !secret my_password

# hue:
#   bridges:
#     - host: !secret hue_ip
#       allow_unreachable: true
#       allow_hue_groups: false

# homekit:
  # - filter:
  #     include_domains:
  #       - camera
  #       # - light
  #       - media_player
  #   entity_config:
  #     media_player.denon:
  #       feature_list:
  #         - feature: on_off
  #         - feature: play_pause
  #         - feature: play_stop
  #         - feature: toggle_mute
  #     switch.common_room_haier:
  #       type: fan
  #     switch.bedroom_daikin:
  #       type: fan
  #     switch.ff_daikin:
  #       type: fan
  #     camera.boxieb1:
  #       support_audio: True
  #     camera.boxieb1:
  #       support_audio: True
  #     camera.foscam_gaarage:
  #       support_audio: True

# ios:
#   actions:
#     - name: Fred
#       background_color: "#000000"
#       label:
#         text: "Hello, World"
#         color: "#ff0000"
#       icon:
#         icon: earth
#         color: "#ffffff"

# logbook:

logger:
  default: warn
  logs:
    # custom_components.icloud3.device_tracker: debug
    # custom_components.icloud3_dev.pyicloud_ic3: debug
    homeassistant.core: fatal

# lovelace:
#   mode: yaml

# map:

media_player:
  # - platform: denonavr
  #   name: "Denon"
  #   host: !secret denon_ip
  #   show_all_sources: True
  #   timeout: 10
  # - platform: dunehd
  #   name: Dune
  #   host: !secret dune_ip
  - platform: kodi
    name: "Kodi"
    host: !secret kodi_ip
    username: !secret my_username
    password: !secret my_password
  # - platform: itunes
  #   name: iTunes
  #   host: !secret itunes_ip
  - platform: mpd
    name: "MPD MacBook Pro"
    host: !secret itunes_ip

media_extractor:

mobile_app:

notify:
  # - platform: ios
  #   name: iOSApp
  # #   target: 'PHUMIN'
  # - platform: nfandroidtv
  #   name: tv
  #   host: !secret kodi_ip
  # - platform: kodi
  #   name: kodi
  #   host: !secret kodi_ip
  #   port: 8080
  #   username: !secret my_username
  #   password: !secret my_password
  - platform: smtp
    name: email
    server: !secret smtp_server
    port: 587
    timeout: 15
    encryption: starttls
    sender: !secret smtp_sender
    recipient: !secret icloud_username
  - platform: group
    name: television
    services:
      - service: tv
      - service: kodi
  - platform: group
    name: pe
    services:
      - service: mobile_app_pesiphone13pro
      - service: mobile_app_pesipadpro
      - service: mobile_app_samsungs8plus
  - platform: group
    name: jue
    services:
      - service: mobile_app_juesiphonexsmax
      - service: mobile_app_juesipadmini4
  # - platform: tts
  #   name: in_the_living_room
  #   tts_service: tts.google_say
  #   media_player: media_player.living_room

recorder:
  purge_keep_days: 10
  # exclude:
  #   entities:
  #     - sensor.icloud3_event_log

panel_iframe:
  glances:
    title: 'Statistics'
    icon: mdi:speedometer
    url: !secret url_stats

script: !include scripts.yaml

stream:

sun:

system_health:

tts:
  - platform: google_translate
    cache: true
    cache_dir: /config/tts
    time_memory: 3000
    base_url: !secret internal_url
    service_name: google_say

# updater:

wake_on_lan:

websocket_api:

zeroconf:

