#!/bin/bash

curl -X POST -H "Authorization: Bearer tKWJggoiVW0v0jrma5MGjnfxPwQZQNE7xhtp1Deb9uq" -F "message=$1" https://notify-api.line.me/api/notify

# /bin/ping -w 5 192.168.1.124 > /dev/null 2>&1
# if [ $? -eq 0 ]; then
#     echo "Success"
# else
#     echo "Fail"
# fi

