# - platform: apple_tv
#   name: "Apple TV"
#   host: !secret apple_tv_ip
#   login_id: !secret apple_tv_login_id

- platform: denonavr
  name: "Denon"
  host: !secret denon_ip
  show_all_sources: True
  timeout: 10

- platform: dunehd
  name: Dune
  host: !secret dune_ip

- platform: kodi
  name: "Kodi"
  host: !secret kodi_ip
  username: !secret my_username
  password: !secret my_password
  turn_off_action: quit

- platform: itunes
  name: iTunes
  host: !secret itunes_ip

- platform: mpd
  name: "MPD Raspberry Pi"
  host: !secret cookie_ip
  port: 6600

- platform: mpd
  name: "Music Player Daemon"
  host: !secret itunes_ip
  port: 6600

# - platform: cast
#   media_player:
#   host: !secret biscuit_ip
#   host: !secret biscuit_ip
