- platform: ping
  host: 192.168.1.78
  name: "Foscam Black"

- platform: ping
  host: 192.168.1.79
  name: "Foscam White"

- platform: ping
  host: 192.168.1.44
  name: "Printer"

- platform: ping
  host: 192.168.1.1
  name: "Deeper"

- platform: ping
  host: 192.168.1.11
  name: "Higher"

- platform: ping
  host: 192.168.1.2
  name: "Pluto"

- platform: ping
  host: 192.168.1.3
  name: "Neptune"

- platform: ping
  host: 192.168.1.4
  name: "Uranus"

- platform: ping
  host: 192.168.1.5
  name: "Mercury"

- platform: ping
  host: 192.168.1.22
  name: "Moon"

- platform: ping
  host: 192.168.1.12
  name: "Broadlink RM Pro"

- platform: ping
  host: 192.168.1.13
  name: "Broadlink RM Mini"
