- platform: synology
  url: http://192.168.1.100:5000
  username: !secret my_username
  password: !secret my_password
  timeout: 15
  verify_ssl: false

# - platform: foscam
#   name: Foscam Black
#   ip: 192.168.1.78
#   port: 7070
#   username: !secret my_username
#   password: !secret my_password

# - platform: foscam
#   name: Foscam White
#   ip: 192.168.1.79
#   port: 7171
#   username: !secret my_username
#   password: !secret my_password

- platform: generic
  name: Current Location Pe
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.pesiphone6.attributes.latitude }},{{ states.device_tracker.pesiphone6.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.pesiphone6.attributes.latitude }},{{ states.device_tracker.pesiphone6.attributes.longitude }}
  limit_refetch_to_url_change: false

- platform: generic
  name: Current Location Jue
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.pesiphone6.attributes.latitude }},{{ states.device_tracker.pesiphone6.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.pesiphone6.attributes.latitude }},{{ states.device_tracker.pesiphone6.attributes.longitude }}
  limit_refetch_to_url_change: false
