### icon ###

device_tracker.pesiphone6:
  icon: mdi:cellphone-iphone
  friendly_name: "Pe iPhone 6"
device_tracker.ping_pesiphone6:
  icon: mdi:cellphone-iphone
  friendly_name: "Pe iPhone 6 (Ping)"
device_tracker.user_pesiphone6:
  icon: mdi:cellphone-iphone
  friendly_name: "Pe iPhone 6 (Owntracks)"
device_tracker.pesipadmini2:
  icon: mdi:tablet-ipad
  friendly_name: "Pe iPad Mini 2"
device_tracker.ping_pesipadmini2:
  icon: mdi:tablet-ipad
  friendly_name: "Pe iPad Mini 2 (Ping)"
device_tracker.user_pesipadmini2:
  icon: mdi:tablet-ipad
  friendly_name: "Pe iPad Mini 2 (Owntracks)"
device_tracker.pepe:
  icon: mdi:laptop-mac
  friendly_name: "Pe Macbook Pro"
device_tracker.ping_pepe:
  icon: mdi:laptop-mac
  friendly_name: "Pe Macbook Pro (Ping)"
device_tracker.pepework:
  icon: mdi:laptop-windows
  friendly_name: "Pe Dell Laptop"
device_tracker.ping_pepework:
  icon: mdi:laptop-windows
  friendly_name: "Pe Dell Laptop (Ping)"
device_tracker.pesipodtouch4:
  icon: mdi:cellphone-dock
  friendly_name: "iPod Touch BMW"
device_tracker.ping_pesipodtouch4:
  icon: mdi:cellphone-dock
  friendly_name: "iPod Touch BMW (Ping)"
device_tracker.juesiphone6splus:
  icon: mdi:cellphone-iphone
  friendly_name: "Jue iPhone 6s Plus"
device_tracker.ping_juesiphone6splus:
  icon: mdi:cellphone-iphone
  friendly_name: "Jue iPhone 6s Plus (Ping)"
device_tracker.user_juesiphone6splus:
  icon: mdi:cellphone-iphone
  friendly_name: "Jue iPhone 6s Plus (Owntracks)"
device_tracker.juesipadmini2:
  icon: mdi:tablet-ipad
  friendly_name: "Jue iPad Mini 2"
device_tracker.ping_juesipadmini2:
  icon: mdi:tablet-ipad
  friendly_name: "Jue iPad Mini 2 (Ping)"
device_tracker.user_juesipadmini2:
  icon: mdi:tablet-ipad
  friendly_name: "Jue iPad Mini 2 (Owntracks)"
device_tracker.benjy:
  icon: mdi:cellphone-iphone
  friendly_name: "Benjy"
device_tracker.ping_benjy:
  icon: mdi:cellphone-iphone
  friendly_name: "Benjy (Ping)"
device_tracker.benjysipadmini2:
  icon: mdi:tablet-ipad
  friendly_name: "Benjy iPad Mini 2"
device_tracker.ping_benjysipadmini2:
  icon: mdi:tablet-ipad
  friendly_name: "Benjy iPad Mini 2 (Ping)"
device_tracker.benjysmbp:
  icon: mdi:laptop-mac
  friendly_name: "Benjy Macbook Pro"
device_tracker.ping_benjysmbp:
  icon: mdi:laptop-mac
  friendly_name: "Benjy Macbook Pro (Ping)"
device_tracker.boom:
  icon: mdi:cellphone-android
  friendly_name: "Boom"
device_tracker.ping_boom:
  icon: mdi:cellphone-android
  friendly_name: "Boom (Ping)"

device_tracker.dune:
  icon: mdi:movie-roll
  friendly_name: "Dune Base"
binary_sensor.dune:
  icon: mdi:movie-roll
  friendly_name: "Dune Base"
device_tracker.xdj_rx:
  icon: mdi:music
  friendly_name: "Pioneer XDJ-RX"
binary_sensor.xdj_rx:
  icon: mdi:music
  friendly_name: "XDJ-RX"

light.bedroom_1:
  icon: mdi:lightbulb
  friendly_name: "Bedroom 1"
  # custom_ui_state_card: custom_light
light.bedroom_2:
  icon: mdi:lightbulb
  friendly_name: "Bedroom 2"
  # custom_ui_state_card: custom_light
light.bedroom_3:
  icon: mdi:lightbulb
  friendly_name: "Bedroom 3"
  # custom_ui_state_card: custom_light
light.bedroom_4:
  icon: mdi:lightbulb
  friendly_name: "Bedroom 4"
  # custom_ui_state_card: custom_light
light.bedroom_lc:
  icon: mdi:spotlight
  friendly_name: "Bedroom LC"
  # custom_ui_state_card: custom_light
light.bedroom_lw:
  icon: mdi:lamp
  friendly_name: "Bedroom LW"
light.common_room_1:
  icon: mdi:ceiling-light
  friendly_name: "Common Room 1"
light.common_room_2:
  icon: mdi:ceiling-light
  friendly_name: "Common Room 2"
light.common_room_3:
  icon: mdi:ceiling-light
  friendly_name: "Common Room 3"
light.common_room_4:
  icon: mdi:ceiling-light
  friendly_name: "Common Room 4"
light.lightstrip:
  icon: mdi:alarm-light
  friendly_name: "Lightstrip"
  # custom_ui_state_card: custom_light
light.hallway:
  icon: mdi:spotlight-beam
  friendly_name: "Hallway"
  # custom_ui_state_card: custom_light
light.front_1:
  icon: mdi:lightbulb-outline
  friendly_name: "Front 1"
light.front_2:
  icon: mdi:lightbulb-outline
  friendly_name: "Front 2"
light.garage:
  icon: mdi:spotlight
  friendly_name: "Garage"

camera.foscam_black:
  icon: mdi:webcam
  friendly_name: "Foscam Black"
binary_sensor.foscam_black:
  icon: mdi:webcam
  friendly_name: "Foscam Black"
camera.foscam_white:
  icon: mdi:webcam
  friendly_name: "Foscam White"
binary_sensor.foscam_white:
  icon: mdi:webcam
  friendly_name: "Foscam White"

sensor.home_to_benjy:
  icon: mdi:car
  friendly_name: "Home to Benjy"
sensor.benjy_to_home:
  icon: mdi:car
  friendly_name: "Benjy to Home"
sensor.home_to_malaiwan:
  icon: mdi:car
  friendly_name: "Home to Malaiwan"
sensor.malaiwan_to_home:
  icon: mdi:car
  friendly_name: "Malaiwan to Home"

sensor.common_room_temperature:
  icon: mdi:thermometer
  friendly_name: "Common Room Temperature"
switch.titan:
  icon: mdi:surround-sound
  friendly_name: "Common Room Home Theatre"
  assumed_state: true
switch.europa:
  icon: mdi:surround-sound
  friendly_name: "Bedroom Sound System"
  assumed_state: true

switch.hometheatre:
  icon: mdi:surround-sound
  friendly_name: "Common Room Home Theatre"
  assumed_state: true
switch.common_room_hometheatre:
  icon: mdi:surround-sound
  friendly_name: "Common Room Home Theatre"
  assumed_state: true
switch.sonytv:
  icon: mdi:television
  friendly_name: "Common Room TV"
  assumed_state: true
switch.android_box:
  icon: mdi:android
  friendly_name: "Common Room Android Box"
  assumed_state: true
switch.common_room_air_cond:
  icon: mdi:air-conditioner
  friendly_name: "Common Room Air Cond"
  assumed_state: true
switch.common_room_fan:
  icon: mdi:fan
  friendly_name: "Common Room Fan"
  assumed_state: true
switch.common_room_saijodenki:
  icon: mdi:air-conditioner
  friendly_name: "Common Room Air Cond"
  assumed_state: true
switch.common_room_fanfan:
  icon: mdi:fan
  friendly_name: "Common Room Fan"
  assumed_state: true
switch.common_room_tv:
  icon: mdi:television
  friendly_name: "Common Room TV"
  assumed_state: true
switch.common_room_android_box:
  icon: mdi:android
  friendly_name: "Common Room Android Box"
  assumed_state: true
# switch.common_room_subwoofer:
#   icon: mdi:speaker
#   friendly_name: "Common Room Subwoofer"
#   assumed_state: true

switch.bedroom_air_cond:
  icon: mdi:air-conditioner
  friendly_name: "Bedroom Air Cond"
  assumed_state: true
  # custom_ui_state_card: custom_aircond
switch.bedroom_daikin:
  icon: mdi:air-conditioner
  friendly_name: "Bedroom Air Cond"
  assumed_state: true
switch.bedroom_tv:
  icon: mdi:television
  friendly_name: "Bedroom TV"
  assumed_state: true
switch.bedroom_sound:
  icon: mdi:amplifier
  friendly_name: "Bedroom Denon"
  assumed_state: true

switch.foscam_black_motion:
  icon: mdi:account-alert
  friendly_name: "Foscam Black Motion Detection"
  assumed_state: true
switch.foscam_white_motion:
  icon: mdi:account-alert
  friendly_name: "Foscam White Motion Detection"
  assumed_state: true

script.mute_common_room:
  icon: mdi:volume-mute
  friendly_name: "Mute Common Room"
script.mute_bedroom:
  icon: mdi:volume-mute
  friendly_name: "Mute Bedroom"

script.dj_shuffle:
  icon: mdi:music-box-outline
  friendly_name: "Playlist DJ"
script.soft_shuffle:
  icon: mdi:music-box-outline
  friendly_name: "Playlist Soft"
script.bedroom_ac_powerful:
  icon: mdi:dumbbell
  friendly_name: "AC Powerful"

# sensor.owm_temperature:
#   icon: mdi:thermometer
#   friendly_name: "Temperature"
# sensor.owm_condition:
#   icon: mdi:weather-cloudy
#   friendly_name: "Condition"
# sensor.owm_cloud_coverage:
#   icon: mdi:weather-partlycloudy
#   friendly_name: "Cloud coverage"
# sensor.owm_humidity:
#   icon: mdi:weather-fog
#   friendly_name: "Humidity"

sensor.cpu_use:
  icon: mdi:chip
  friendly_name: "CPU Usage"
sensor.ram_use:
  icon: mdi:memory
  friendly_name: "RAM Usage"
sensor.disk_use_:
  icon: mdi:harddisk
  friendly_name: "HDD Usage"
sensor.maximum_disk_temperature:
  icon: mdi:thermometer-lines
  friendly_name: "Maximum Disk Temperature"
sensor.average_disk_temperature:
  icon: mdi:thermometer
  friendly_name: "Average Disk Temperature"

sensor.denon_source:
  icon: mdi:amplifier
  friendly_name: "Common Room Denon"

# sensor.lastfm_pephumin:
#   icon: mdi:lastfm
#   friendly_name: "Now Playing"

binary_sensor.deeper:
  icon: mdi:router-wireless
  friendly_name: "Primary Gateway"
binary_sensor.higher:
  icon: mdi:router-wireless
  friendly_name: "Secondary Gateway"
binary_sensor.pluto:
  icon: mdi:wifi
  friendly_name: "Airport Extreme"
binary_sensor.neptune:
  icon: mdi:wifi
  friendly_name: "Airport Express Bedroom"
binary_sensor.uranus:
  icon: mdi:wifi
  friendly_name: "Airport Express Downstairs"
binary_sensor.mercury:
  icon: mdi:wifi
  friendly_name: "Airport Express Satellite"
binary_sensor.apollo:
  icon: mdi:wifi
  friendly_name: "ASUStek RT-12+"
binary_sensor.sputnik:
  icon: mdi:wifi
  friendly_name: "Ubiquiti Rocket M2"

binary_sensor.apple_tv:
  icon: mdi:apple
  friendly_name: "Apple TV"
binary_sensor.denon:
  icon: mdi:amplifier
  friendly_name: "Denon AVR-2113"
binary_sensor.android_box:
  icon: mdi:android
  friendly_name: "Android Box"

binary_sensor.moon:
  icon: mdi:orbit
  friendly_name: "Philips Hue"
binary_sensor.broadlink_rm_pro:
  icon: mdi:remote
  friendly_name: "Broadlink RM Pro"
binary_sensor.broadlink_rm_mini_a:
  icon: mdi:remote
  friendly_name: "Broadlink RM Mini A"
binary_sensor.broadlink_rm_mini_b:
  icon: mdi:remote
  friendly_name: "Broadlink RM Mini B"
binary_sensor.earth:
  icon: mdi:printer
  friendly_name: "Samsung Printer"

binary_sensor.titan:
  icon: mdi:power-socket-us
  friendly_name: "TP-Link Plug Common Room"
binary_sensor.europa:
  icon: mdi:power-socket-us
  friendly_name: "TP-Link Plug Bedroom"
binary_sensor.ganymede:
  icon: mdi:power-socket
  friendly_name: "Sonoff POW Ganymede"
binary_sensor.callisto:
  icon: mdi:power-plug
  friendly_name: "Sonoff Basic Callisto"
binary_sensor.mimas:
  icon: mdi:power-plug
  friendly_name: "Sonoff Basic Mimas"
binary_sensor.pandora:
  icon: mdi:power-plug
  friendly_name: "Sonoff Basic Pandora"
binary_sensor.phoebe:
  icon: mdi:power-plug
  friendly_name: "Sonoff Basic Phoebe"
binary_sensor.calypso:
  icon: mdi:power-plug
  friendly_name: "Sonoff Basic Calypso"

binary_sensor.nodemcu:
  icon: mdi:video-input-antenna
  friendly_name: "NodeMCU"
binary_sensor.wemoslitea:
  icon: mdi:video-input-antenna
  friendly_name: "WeMos Lite A"
binary_sensor.wemosliteled:
  icon: mdi:video-input-antenna
  friendly_name: "WeMos Lite LED"
binary_sensor.wemospro:
  icon: mdi:video-input-antenna
  friendly_name: "WeMos Pro"
binary_sensor.wemosbell:
  icon: mdi:video-input-antenna
  friendly_name: "WeMos Bell"
binary_sensor.wemosb:
  icon: mdi:video-input-antenna
  friendly_name: "WeMos B"

proximity.jue_home:
  # icon: mdi:compass-outline
  friendly_name: "Jue from Home"
proximity.pe_home:
  # icon: mdi:compass-outline
  friendly_name: "Pe from Home"
proximity.jue_malaiwan:
  # icon: mdi:compass-outline
  friendly_name: "Jue from Malaiwan"
proximity.pe_benjawan:
  # icon: mdi:compass-outline
  friendly_name: "Pe from Benjy"

switch.ganymede:
  icon: mdi:power-socket
  friendly_name: "Bedroom Online Switch"
  assumed_state: true
sensor.ganymede_power:
  icon: mdi:power-socket
  friendly_name: "Ganymede Power"
sensor.ganymede_power_factor:
  icon: mdi:power-socket
  friendly_name: "Ganymede Power Factor"
sensor.ganymede_current:
  icon: mdi:pulse
  friendly_name: "Ganymede Current"
sensor.ganymede_voltage:
  icon: mdi:tower-fire
  friendly_name: "Ganymede Voltage"
sensor.ganymede_uptime:
  icon: mdi:timelapse
  friendly_name: "Ganymede Uptime"
sensor.ganymede_energy_today:
  icon: mdi:chart-areaspline
  friendly_name: "Ganymede Energy Today"
sensor.ganymede_energy_yesterday:
  icon: mdi:chart-areaspline
  friendly_name: "Ganymede Energy Yesterday"
sensor.ganymede_energy_total:
  icon: mdi:chart-areaspline
  friendly_name: "Ganymede Energy Total"

switch.callisto:
  icon: mdi:power-plug
  friendly_name: "Callisto"
  assumed_state: true
switch.mimas:
  icon: mdi:speaker
  friendly_name: "Common Room Subwoofer"
  assumed_state: true
light.pandora:
  icon: mdi:lightbulb-on-outline
  friendly_name: "Bedroom Night Light"
  assumed_state: false
sensor.pandora_temperature:
  icon: mdi:thermometer
  friendly_name: "Bedroom Temperature"
sensor.pandora_humidity:
  icon: mdi:water-percent
  friendly_name: "Bedroom Humidity"
light.phoebe:
  icon: mdi:lightbulb-on-outline
  friendly_name: "Kitchen"
  assumed_state: false
switch.calypso:
  icon: mdi:power-plug
  friendly_name: "Calypso"
  assumed_state: true
sensor.mimas_temperature:
  icon: mdi:thermometer
  friendly_name: "Common Room Temperature"
sensor.mimas_humidity:
  icon: mdi:water-percent
  friendly_name: "Common Room Humidity"

group.lights_all:
  assumed_state: false
group.common_room_lights_all:
  assumed_state: false
group.bedroom_lights_all:
  assumed_state: false
group.first_floor_lights_all:
  assumed_state: false

sensor.rm_pro_temperature_mean:
  icon: mdi:chart-line-stacked
  friendly_name: "RM Pro Temperature"
sensor.common_room_temperature_mean:
  icon: mdi:chart-line-stacked
  friendly_name: "Common Room Temperature"
sensor.common_room_humidity_mean:
  icon: mdi:chart-line-stacked
  friendly_name: "Common Room Humidity"
sensor.bedroom_temperature_mean:
  icon: mdi:chart-line-stacked
  friendly_name: "Bedroom Temperature"
sensor.bedroom_humidity_mean:
  icon: mdi:chart-line-stacked
  friendly_name: "Bedroom Humidity"
sensor.maximum_disk_temperature_mean:
  icon: mdi:chart-line-stacked
  friendly_name: "Maximum Saturn Temperature"
sensor.average_disk_temperature_mean:
  icon: mdi:chart-line-stacked
  friendly_name: "Average Saturn Temperature"

light.led:
  icon: mdi:led-strip
  friendly_name: "LED Lightstrip"
  assumed_state: true
input_number.led_animation_speed:
  icon: mdi:fast-forward
  friendly_name: "Speed"

sensor.last_boot:
  hidden: true
sensor.since_last_boot:
  hidden: true
sensor.pes_iphone_6_battery_level:
  hidden: true
sensor.pes_iphone_6_battery_level_2:
  hidden: true
sensor.pes_iphone_6_battery_level_3:
  hidden: true
sensor.pes_iphone_6_battery_state:
  hidden: true
sensor.pes_iphone_6_battery_state_2:
  hidden: true
sensor.pes_iphone_6_battery_state_3:
  hidden: true
sensor.jues_iphone_6s_plus_battery_level:
  hidden: true
sensor.jues_iphone_6s_plus_battery_level_2:
  hidden: true
sensor.jues_iphone_6s_plus_battery_level_3:
  hidden: true
sensor.jues_iphone_6s_plus_battery_state:
  hidden: true
sensor.jues_iphone_6s_plus_battery_state_2:
  hidden: true
sensor.jues_iphone_6s_plus_battery_state_3:
  hidden: true
sensor.jues_iphone6s_plus_battery_level:
  hidden: true
sensor.jues_iphone6s_plus_battery_level_2:
  hidden: true
sensor.jues_iphone6s_plus_battery_state:
  hidden: true
sensor.jues_iphone6s_plus_battery_state_2:
  hidden: true
sensor.pes_ipad_mini_2_battery_level:
  hidden: true
sensor.pes_ipad_mini_2_battery_level_2:
  hidden: true
sensor.pes_ipad_mini_2_battery_state:
  hidden: true
sensor.pes_ipad_mini_2_battery_state_2:
  hidden: true
sensor.jues_ipad_mini_2_battery_level:
  hidden: true
sensor.jues_ipad_mini_2_battery_level_2:
  hidden: true
sensor.jues_ipad_mini_2_battery_state:
  hidden: true
sensor.jues_ipad_mini_2_battery_state_2:
  hidden: true
sensor.temperature_sda:
  hidden: true
sensor.temperature_sdb:
  hidden: true
sensor.temperature_sdc:
  hidden: true
sensor.temperature_sdd:
  hidden: true
