- platform: icloud
  username: !secret icloud_username
  password: !secret icloud_password
  account_name: pe
  track_new_devices: true
  interval_seconds: 300
  consider_home: 600

- platform: tomato
  host: 192.168.1.1
  username: !secret my_username
  password: !secret my_password
  http_id: !secret tomato_http_id
  track_new_devices: true
  interval_seconds: 300
  consider_home: 600

# - platform: nmap_tracker
#   hosts: 192.168.1.1/24
#   home_interval: 10
#   track_new_devices: true
#   interval_seconds: 300
#   consider_home: 300
