- platform: icloud
  username: !secret icloud_username
  password: !secret icloud_password
  account_name: pe
  interval_seconds: 12
  consider_home: 300

- platform: nmap_tracker
  hosts: 192.168.1.1/24
  home_interval: 5
  scan_options: "--unprivileged -sn"
  interval_seconds: 12
  consider_home: 300
  exclude:
    - 192.168.1.100

# - platform: bluetooth_tracker
#   home_interval: 5
#   interval_seconds: 12
#   consider_home: 300

- platform: owntracks
  max_gps_accuracy: 100

- platform: mqtt
  devices:
    pesiphone6: /owntracks/user/pesiphone6
    juesiphone6splus: /owntracks/user/juesiphone6splus

# - platform: tomato
#   host: 192.168.1.1
#   username: !secret my_username
#   password: !secret my_password
#   http_id: !secret tomato_http_id_1
#   track_new_devices: true
#   interval_seconds: 10
#   consider_home: 180

# - platform: tomato
#   host: 192.168.1.11
#   username: !secret my_username
#   password: !secret my_password
#   http_id: !secret tomato_http_id_2
#   track_new_devices: true
#   interval_seconds: 10
#   consider_home: 180

# - platform: ping
#   hosts:
#     iphone_pe: 192.168.1.124
#     ipad_pe: 192.168.1.181
#     iphone_jue: 192.168.1.110
#     ipad_jue: 192.168.1.129
#     ipod_bmw: 192.168.1.180
#     mbp_pe: 192.168.1.200
