include:
  domains:
    - binary_sensor
    - device_tracker
    - media_player
    - proximity
  entities:
    - input_boolean.presence_pe
    - input_boolean.presence_jue
    - input_boolean.presence_benjy
    - input_boolean.presence_pe_benjawan
    - input_boolean.presence_jue_malaiwan
    - sensor.benjy_to_home
    - sensor.home_to_benjy
    - sensor.home_to_malaiwan
    - sensor.malaiwan_to_home
    - sensor.uptime
    - sensor.cpu_use
    - sensor.ram_use
    - sensor.average_temperature
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.common_room_temperature
    - sensor.titan_current_consumption
    - sensor.europa_current_consumption

exclude:
  domains:
    - input_slider
    - input_boolean
    - light
    - scene
    - sensor
    - sun
    - switch
    - updater
    - weblink
    - zone
  entities:
    - sun.sun
    - camera.foscam_black
    - camera.foscam_white
    - camera.current_location_jue
    - camera.current_location_pe
