# - platform: apple_tv
#   name: "Apple TV"
#   host: !secret apple_tv_ip
#   login_id: !secret apple_tv_login_id

# - platform: denon
#   host: !secret denon_ip

- platform: denonavr
  name: "Denon"
  host: !secret denon_ip

- platform: dunehd
  name: Dune
  host: !secret dune_ip

- platform: kodi
  name: "Kodi"
  host: !secret kodi_ip
  username: !secret my_username
  password: !secret my_password
  turn_off_action: quit

- platform: mpd
  name: "Music Player Daemon"
  host: !secret itunes_ip
  port: 6600
