- platform: apple_tv
  name: "Apple TV"
  host: !secret apple_tv_ip
  login_id: !secret apple_tv_login_id

- platform: denonavr
  name: "Denon"
  host: !secret denon_ip

- platform: dunehd
  name: Dune
  host: !secret dune_ip

- platform: kodi
  name: "Kodi"
  host: !secret kodi_ip
  username: !secret my_username
  password: !secret my_password
  turn_off_action: quit

- platform: mpd
  name: "Music Player Daemon"
  host: !secret itunes_ip
  port: 6600

# - platform: universal
#   name: Common Room Media Center
#   children:
#     - media_player.apple_tv
#     - media_player.denon
#     - media_player.dune
#     - media_player.kodi
#     - media_player.avr2113_airtunes_speaker
#     - media_player.living_room_apple_tv_airtunes_speaker
#   commands:
#     turn_on:
#       service: media_player.turn_on
#       data:
#         entity_id: media_player.denon
#     turn_off:
#       service: media_player.turn_off
#       data:
#         entity_id: media_player.denon
#     volume_up:
#       service: media_player.volume_up
#       data:
#         entity_id: media_player.denon
#     volume_down:
#       service: media_player.volume_down
#       data:
#         entity_id: media_player.denon
#     volume_mute:
#       service: media_player.volume_mute
#       data:
#         entity_id: media_player.denon
#     volume_set:
#       service: media_player.volume_set
#       data_template:
#         entity_id: media_player.denon
#         volume_level: ''
#     select_source:
#       service: media_player.select_source
#       data_template:
#         entity_id: media_player.denon
#         source: ''
#   attributes:
#     state: media_player.denon
#     is_volume_muted: media_player.denon|volume_mute
#     volume_level: media_player.denon|volume_level
#     source: media_player.denon|source
#     source_list: media_player.denon|source_list

# - platform: universal
#   name: Bedroom Media Center
#   children:
#     - media_player.itunes
#     - media_player.computer_airtunes_speaker
#     - media_player.bedroom_aex_airtunes_speaker
#   commands:
#     turn_on:
#       service: media_player.turn_on
#       data:
#         entity_id: media_player.itunes
#     turn_off:
#       service: media_player.turn_off
#       data:
#         entity_id: media_player.itunes
#     volume_up:
#       service: media_player.volume_up
#       data:
#         entity_id: media_player.itunes
#     volume_down:
#       service: media_player.volume_down
#       data:
#         entity_id: media_player.itunes
#     volume_mute:
#       service: media_player.volume_mute
#       data:
#         entity_id: media_player.itunes
#     volume_set:
#       service: media_player.volume_set
#       data_template:
#         entity_id: media_player.itunes
#         volume_level: ''
#     select_source:
#       service: media_player.select_source
#       data_template:
#         entity_id: media_player.itunes
#         source: ''
#   attributes:
#     state: media_player.itunes
#     is_volume_muted: media_player.itunes|volume_mute
#     volume_level: media_player.itunes|volume_level
#     source: media_player.itunes|source
#     source_list: media_player.itunes|source_list
