- platform: nfandroidtv
  name: tv
  host: !secret kodi_ip
  duration: 15
  transparency: "25%"
  color: "black"

- platform: kodi
  name: kodi
  host: !secret kodi_ip
  port: 8080
  username: !secret my_username
  password: !secret my_password

- platform: lannouncer
  name: voicetv
  host: !secret kodi_ip

- platform: smtp
  name: email
  server: !secret smtp_server
  port: !secret smtp_port
  sender: !secret smtp_sender
  recipient: phumin@sawasdee.org

- platform: group
  name: television
  services:
    - service: tv
    - service: kodi
    - service: voicetv

- platform: file
  name: file
  filename: !secret notify_file
  timestamp: true

# - platform: pushbullet
#   name: pushbullet
#   api_key: !secret api_key_pushbullet

# - platform: html5
#   gcm_api_key: !secret gcm_api_key
#   gcm_sender_id: !secret gcm_sender_id
