- platform: nfandroidtv
  name: tv
  host: 192.168.1.88
  duration: 15
  transparency: "25%"
  # color: grey (default), black, indigo, green, red, cyan, teal, amber, pink

- platform: kodi
  name: kodi
  host: 192.168.1.88
  port: 8080
  username: !secret my_username
  password: !secret my_password

- platform: smtp
  name: email
  server: !secret smtp_server
  port: !secret smtp_port
  sender: !secret smtp_sender
  recipient: phumin@sawasdee.org

# - platform: pushbullet
#   name: pushbullet
#   api_key: !secret api_key_pushbullet

# - platform: html5
#   gcm_api_key: !secret gcm_api_key
#   gcm_sender_id: !secret gcm_sender_id

# - platform: group
#   name: tv
#   services:
#     - service: nfandroidtv
#     # - service: kodi
