purge_days: 30
db_url: !secret db_url

include:
  domains:
    - sensor
    - binary_sensor
    - light
    - switch
    - device_tracker
  entities:
    - input_select.homemode
    - media_player.apple_tv
    - media_player.kodi
    - media_player.denon
    - media_player.dune
    - media_player.itunes

exclude:
  domains:
    - sun
    - weblink
    - proximity
    - scene
    - zone
    - input_slider
    - input_boolean
    - updater
  entities:
    - sensor.benjy_to_home
    - sensor.cpu_use
    - sensor.date
    - sensor.day_light
    - sensor.home_to_benjy
    - sensor.home_to_malaiwan
    - sensor.jues_ipad_mini_2_battery_level
    - sensor.jues_ipad_mini_2_battery_level_2
    - sensor.jues_ipad_mini_2_battery_state
    - sensor.jues_ipad_mini_2_battery_state_2
    - sensor.jues_iphone_6s_plus_battery_level
    - sensor.jues_iphone_6s_plus_battery_level_2
    - sensor.jues_iphone_6s_plus_battery_level_3
    - sensor.jues_iphone_6s_plus_battery_state
    - sensor.jues_iphone_6s_plus_battery_state_2
    - sensor.jues_iphone_6s_plus_battery_state_3
    - sensor.last_boot
    - sensor.malaiwan_to_home
    - sensor.moon
    - sensor.owm_cloud_coverage
    - sensor.owm_condition
    - sensor.owm_humidity
    - sensor.owm_rain
    - sensor.owm_temperature
    - sensor.pes_ipad_mini_2_battery_level
    - sensor.pes_ipad_mini_2_battery_level_2
    - sensor.pes_ipad_mini_2_battery_state
    - sensor.pes_ipad_mini_2_battery_state_2
    - sensor.pes_iphone_6_battery_level
    - sensor.pes_iphone_6_battery_level_2
    - sensor.pes_iphone_6_battery_level_3
    - sensor.pes_iphone_6_battery_state
    - sensor.pes_iphone_6_battery_state_2
    - sensor.pes_iphone_6_battery_state_3
    - sensor.ram_use
    - sensor.since_last_boot
    - sensor.solar_angle
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.temperature_sda
    - sensor.temperature_sdb
    - sensor.temperature_sdc
    - sensor.temperature_sdd
    - sensor.time
    - sensor.uptime
    - sun.sun
    - camera.foscam_black
    - camera.foscam_white
    - camera.current_location_jue
    - camera.current_location_pe
