purge_days: 10
db_url: !secret db_url

include:
  domains:
    - binary_sensor
    - device_tracker
    - proximity
  entities:
    - sensor.benjy_to_home
    - sensor.home_to_benjy
    - sensor.home_to_malaiwan
    - sensor.malaiwan_to_home
    - sensor.uptime
    - sensor.cpu_use
    - sensor.ram_use
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.titan_current_consumption
    - sensor.europa_current_consumption

exclude:
  domains:
    - input_slider
    - input_boolean
    - light
    - media_player
    - scene
    - sensor
    - sun
    - switch
    - updater
    - weblink
    - zone
  entities:
    - sun.sun
    - camera.foscam_black
    - camera.foscam_white
    - camera.current_location_jue
    - camera.current_location_pe
