- name: "All Lights Off"
  entities:
    group.all_lights:
      state: off

- name: "Common Room Off"
  entities:
    group.common_room_lights_all:
      state: off

- name: "Common Room Bright"
  entities:
    light.whites_A1:
      state: on
      transition: 1
      brightness: 124
    light.whites_A2:
      state: on
      transition: 1
      brightness: 124
    light.whites_A3:
      state: on
      transition: 1
      brightness: 254
    light.whites_A4:
      state: on
      transition: 1
      brightness: 254
    light.tv:
      state: off
    light.hallway:
      state: off

# - name: "Common Room Alive"
#   entities:
#     light.whites_A1:
#       state: off
#     light.whites_A2:
#       state: off
#     light.whites_A3:
#       state: on
#       transition: 1
#       brightness: 131
#     light.whites_A4:
#       state: on
#       transition: 1
#       brightness: 131
#     light.tv:
#       state: off
#     light.hallway:
#       state: off

- name: "Common Room Dim"
  entities:
    light.whites_A1:
      state: off
    light.whites_A2:
      state: off
    light.whites_A3:
      state: on
      transition: 1
      brightness: 35
    light.whites_A4:
      state: on
      transition: 1
      brightness: 35
    light.tv:
      state: off
    light.hallway:
      state: off

- name: "Bedroom Off"
  entities:
    group.bedroom_lights_all:
      state: off

- name: "Bedroom Very Bright"
  entities:
    light.hue_1:
      state: on
      transition: 1
      brightness: 127
      xy_color: [0.3145,0.3303]
    light.hue_2:
      state: on
      transition: 1
      brightness: 127
      xy_color: [0.3145,0.3303]
    light.hue_3:
      state: on
      transition: 1
      brightness: 254
      xy_color: [0.3145,0.3303]
    light.hue_4:
      state: on
      transition: 1
      brightness: 254
      xy_color: [0.3145,0.3303]
    light.whites_w:
      state: off
    light.mood:
      state: off
    light.pandora:
      state: off

- name: "Bedroom Bright"
  entities:
    light.hue_1:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.2951,0.2930]
    light.hue_2:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.2951,0.2930]
    light.hue_3:
      state: on
      transition: 1
      brightness: 127
      xy_color: [0.2951,0.2930]
    light.hue_4:
      state: on
      transition: 1
      brightness: 127
      xy_color: [0.2951,0.2930]
    light.whites_w:
      state: off
    light.mood:
      state: off
    light.pandora:
      state: off

# - name: "Bedroom Alive"
#   entities:
#     light.hue_1:
#       state: off
#     light.hue_2:
#       state: off
#     light.hue_3:
#       state: on
#       transition: 1
#       brightness: 170
#       xy_color: [0.2723,0.2482]
#     light.hue_4:
#       state: on
#       transition: 1
#       brightness: 170
#       xy_color: [0.2723,0.2482]
#     light.whites_w:
#       state: off
#     light.mood:
#       state: off
#     light.pandora:
#       state: off

- name: "Bedroom Night"
  entities:
    light.hue_1:
      state: off
    light.hue_2:
      state: off
    light.hue_3:
      state: on
      transition: 1
      brightness: 220
      xy_color: [0.3685,0.3717]
    light.hue_4:
      state: off
    light.whites_w:
      state: off
    light.mood:
      state: off
    light.pandora:
      state: on

# - name: "Bedroom Warm"
#   entities:
#     light.hue_1:
#       state: off
#     light.hue_2:
#       state: off
#     light.hue_3:
#       state: on
#       transition: 1
#       brightness: 6
#       xy_color: [0.4410,0.4379]
#     light.hue_4:
#       state: on
#       transition: 1
#       brightness: 6
#       xy_color: [0.4410,0.4379]
#     light.whites_w:
#       state: on
#       transition: 1
#       brightness: 6
#     light.mood:
#       state: off
#     light.pandora:
#       state: off

- name: "Bedroom Sleep"
  entities:
    light.hue_1:
      state: off
    light.hue_2:
      state: off
    light.hue_3:
      state: off
    light.hue_4:
      state: off
    light.whites_w:
      state: off
    light.mood:
      state: on
      transition: 1
      brightness: 70
      xy_color: [0.3227,0.5086]
    light.pandora:
      state: off

# - name: "Bedroom Concentrate"
#   entities:
#     light.hue_1:
#       state: on
#       transition: 1
#       brightness: 110
#       xy_color: [0.3685,0.3717]
#     light.hue_2:
#       state: on
#       transition: 1
#       brightness: 110
#       xy_color: [0.3685,0.3717]
#     light.hue_3:
#       state: on
#       transition: 1
#       brightness: 220
#       xy_color: [0.3685,0.3717]
#     light.hue_4:
#       state: on
#       transition: 1
#       brightness: 220
#       xy_color: [0.3685,0.3717]
#     light.whites_w:
#       state: off
#     light.mood:
#       state: off
#     light.pandora:
#       state: on

# - name: "Bedroom Energize"
#   entities:
#     light.hue_1:
#       state: on
#       transition: 1
#       brightness: 101
#       xy_color: [0.368,0.3686]
#     light.hue_2:
#       state: on
#       transition: 1
#       brightness: 101
#       xy_color: [0.368,0.3686]
#     light.hue_3:
#       state: on
#       transition: 1
#       brightness: 202
#       xy_color: [0.368,0.3686]
#     light.hue_4:
#       state: on
#       transition: 1
#       brightness: 202
#       xy_color: [0.368,0.3686]
#     light.whites_w:
#       state: off
#     light.mood:
#       state: off
#     light.pandora:
#       state: on

# - name: "Bedroom Read"
#   entities:
#     light.hue_1:
#       state: on
#       transition: 1
#       brightness: 120
#       xy_color: [0.4448,0.4066]
#     light.hue_2:
#       state: on
#       transition: 1
#       brightness: 120
#       xy_color: [0.4448,0.4066]
#     light.hue_3:
#       state: on
#       transition: 1
#       brightness: 240
#       xy_color: [0.4448,0.4066]
#     light.hue_4:
#       state: on
#       transition: 1
#       brightness: 240
#       xy_color: [0.4448,0.4066]
#     light.whites_w:
#       state: off
#     light.mood:
#       state: off
#     light.pandora:
#       state: on

# - name: "Bedroom Relax"
#   entities:
#     light.hue_1:
#       state: on
#       transition: 1
#       brightness: 70
#       xy_color: [0.5119,0.4147]
#     light.hue_2:
#       state: on
#       transition: 1
#       brightness: 70
#       xy_color: [0.5119,0.4147]
#     light.hue_3:
#       state: on
#       transition: 1
#       brightness: 144
#       xy_color: [0.5119,0.4147]
#     light.hue_4:
#       state: on
#       transition: 1
#       brightness: 144
#       xy_color: [0.5119,0.4147]
#     light.whites_w:
#       state: off
#     light.mood:
#       state: off
#     light.pandora:
#       state: off

- name: "Bedroom Blossom"
  entities:
    light.hue_1:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.3944,0.2952]
    light.hue_2:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.3944,0.2952]
    light.hue_3:
      state: on
      transition: 1
      brightness: 123
      xy_color: [0.3944,0.2952]
    light.hue_4:
      state: on
      transition: 1
      brightness: 123
      xy_color: [0.3944,0.2952]
    light.whites_w:
      state: off
    light.mood:
      state: off
    light.pandora:
      state: off

- name: "Bedroom Savanna"
  entities:
    light.hue_1:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.6406,0.3333]
    light.hue_2:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.4640,0.4513]
    light.hue_3:
      state: on
      transition: 1
      brightness: 123
      xy_color: [0.6406,0.3333]
    light.hue_4:
      state: on
      transition: 1
      brightness: 123
      xy_color: [0.5888,0.3536]
    light.whites_w:
      state: off
    light.mood:
      state: off
    light.pandora:
      state: off

- name: "Bedroom Twilight"
  entities:
    light.hue_1:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.5997,0.3765]
    light.hue_2:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.3581,0.2871]
    light.hue_3:
      state: on
      transition: 1
      brightness: 123
      xy_color: [0.5993,0.3765]
    light.hue_4:
      state: on
      transition: 1
      brightness: 123
      xy_color: [0.3581,0.2872]
    light.whites_w:
      state: off
    light.mood:
      state: off
    light.pandora:
      state: off

- name: "Bedroom Aurora"
  entities:
    light.hue_1:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.2351,0.1743]
    light.hue_2:
      state: on
      transition: 1
      brightness: 88
      xy_color: [0.1684,0.0416]
    light.hue_3:
      state: on
      transition: 1
      brightness: 123
      xy_color: [0.2916,0.2860]
    light.hue_4:
      state: on
      transition: 1
      brightness: 123
      xy_color: [0.3108,0.3239]
    light.whites_w:
      state: off
    light.mood:
      state: off
    light.pandora:
      state: off

- name: "First Floor Off"
  entities:
    group.first_floor_lights_all:
      state: off

# - name: "First Floor Concentrate"
#   entities:
#     group.first_floor_lights_main:
#       state: on
#       profile: "Concentrate"
#     light.garage:
#       state: off
#     light.phoebe:
#       state: on

# - name: "First Floor Energize"
#   entities:
#     group.first_floor_lights_main:
#       state: on
#       profile: "Energize"
#     light.garage:
#       state: off
#     light.phoebe:
#       state: on

# - name: "First Floor Read"
#   entities:
#     group.first_floor_lights_main:
#       state: on
#       profile: "Read"
#     light.garage:
#       state: off
#     light.phoebe:
#       state: on

# - name: "First Floor Relax"
#   entities:
#     group.first_floor_lights_main:
#       state: on
#       profile: "Relax"
#     light.garage:
#       state: off
#     light.phoebe:
#       state: off

- name: "First Floor Bright"
  entities:
    light.whites_B1:
      state: on
      transition: 1
      brightness: 254
    light.whites_B2:
      state: on
      transition: 1
      brightness: 254
    light.garage:
      state: on
      transition: 1
      brightness: 124
    light.phoebe:
      state: on

# - name: "First Floor Alive"
#   entities:
#     light.whites_B1:
#       state: on
#       transition: 1
#       brightness: 131
#     light.whites_B2:
#       state: on
#       transition: 1
#       brightness: 131
#     light.garage:
#       state: off
#     light.phoebe:
#       state: off

- name: "First Floor Dim"
  entities:
    light.whites_B1:
      state: on
      transition: 1
      brightness: 35
    light.whites_B2:
      state: on
      transition: 1
      brightness: 35
    light.garage:
      state: off
    light.phoebe:
      state: off
