# kodi_notification:
#   sequence:
#   - service: notify.kodi
#     data:
#       title: "Home Assistant"
#       message: "Message to KODI from Home Assistant!"
#       data:
#         displaytime: 20000
#         icon: "warning"

# common_room_aircond_on:
#   sequence:
#     - service: broadlink.send_packet_192_168_1_142
#       data:
#         packet:
#           - "JgCYAAABJ5cUOBQTFTYWEhQSFBIVEhURFjcVERUTFDgVEBYRFRIUFBQ2FhIVNhQTFBIUOBQUExQTExQ3FDoSExQ4FDgVExMTExMVEhQSFTgTFBM4FBMVEhMSFRIVEhQ4FBIVNxUSFBMUExMTFBMVNxQSFDgUExQSFTcVOBQ3FTcVOBQ4FjcTOBY2FDkTORMTFTcTOBUSFBEVAA0F"
#           # - "JgAyAXE2Dg0PDRAnDw0RJw4NESYPDQ8MEScQDBALECcRJxALEQwODQ8ODgwPDg8LEAwQKQ4NECcPDg0ODg0PDQ8oDwwQDBAoDygQJxAMECkODA8NDwwPDRAoDygQCxEoDycQKBAMDgAJkHE1EAwPDREmDwwQKQ4NECcPDBAMECkODA8NECcQJxELDw4ODBAODgwQCxAMDw0QJxAMECcPDQ8ODg0PDBAnDw0PDRAoDycQKQ4NDygPDBANDg4ODRAnEScPDBEnECcQKA4ODgAJj3I0EAwRCxAnDw0QKBALECcRCw8ODycPDBANDygRJw4ODg4PDA4NDw0PDBAMEAsRKA8NDycPDBAMDw0PDREmEA0ODQ8oDygQJw8OECYRCw8NDwwQDBAoDygQCxAoECcQKBAMDgANBQAAAAAAAA=="
