flashing_long:
  alias: "Flashing Long and Notify"
  sequence:
    - service: light.turn_on
      entity_id: group.flashlights
      data:
        transition: 1
        brightness: 250
        flash: long
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

flashing_short:
  alias: "Flashing Short and Notify"
  sequence:
    - service: light.turn_on
      entity_id: group.flashlights
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: group.flashlights
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: group.flashlights
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: group.flashlights
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: group.flashlights
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

flashing_once:
  alias: "Flashing Once and Notify"
  sequence:
    - service: light.turn_on
      entity_id: group.flashlights
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

# flashing_slow:
#   alias: "Flashing Slow and Notify"
#   sequence:
#     - service: light.turn_on
#       entity_id: light.bedroom_1
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_1
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_1
#     # - service: light.turn_off
#     #   entity_id: light.common_room_1
#     - service: light.turn_on
#       entity_id: light.bedroom_2
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_2
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_2
#     # - service: light.turn_off
#     #   entity_id: light.common_room_2
#     - service: light.turn_on
#       entity_id: light.bedroom_1
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_1
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_1
#     # - service: light.turn_off
#     #   entity_id: light.common_room_1
#     - service: light.turn_on
#       entity_id: light.bedroom_2
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_2
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_2
#     # - service: light.turn_off
#     #   entity_id: light.common_room_2
#     - service: light.turn_on
#       entity_id: light.bedroom_1
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_1
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_1
#     # - service: light.turn_off
#     #   entity_id: light.common_room_1
#     - service: light.turn_on
#       entity_id: light.bedroom_2
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_2
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_2
#     # - service: light.turn_off
#     #   entity_id: light.common_room_2
#     - service: notify.tv
#       data_template:
#         title: '{{ title }}'
#         message: '{{ message }}'
#     - service: notify.email
#       data_template:
#         title: '{{ title }}'
#         message: '{{ message }}'

notifying:
  alias: "Notify to TV and email"
  sequence:
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: script.notify_pesiphone6
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

# strobe_a:
#   alias: "Strobe A"
#   sequence:
#     - service: light.turn_on
#       data:
#         entity_id: light.bedroom_3
#         effect: random
#         transition: 0
#         brightness: 254
#         xy: [0.1684, 0.0416]
#     - delay:
#         milliseconds: 500
#     - service: script.strobe_b

# strobe_b:
#   alias: "Strobe B"
#   sequence:
#     - service: light.turn_off
#       data:
#         entity_id: light.bedroom_3
#         transition: 0
#     - delay:
#         milliseconds: 500
#     - service: script.strobe_a
