# foscam_off:
#   sequence:
#     - service: switch.turn_off
#       data:
#         entity_id: switch.foscam_motion
#     - service: shell_command.foscam_turn_off
# foscam_on:
#   sequence:
#     - service: switch.turn_off
#       data:
#         entity_id: switch.foscam_motion
#     - service: shell_command.foscam_turn_on
#     - service: switch.turn_on
#       data:
#         entity_id: switch.foscam_motion

# strobe:
#   startA:
#     sequence:
#       - service: light.turn_on
#         entity_id: light.bedroom_3
#         data:
#           effect: random
#           transition: 0
#           brightness: 254
#           xy: [0.1684, 0.0416]
#       - delay:
#           milliseconds: 500
#       - service: script.startB
#   startB:
#     sequence:
#       - service: light.turn_off
#         entity_id: light.bedroom_3
#         data:
#           transition: 0
#       - delay:
#           milliseconds: 500
#       - service: script.startA

strobe_a:
  alias: "Strobe A"
  sequence:
    - service: light.turn_on
      entity_id: light.bedroom_3
      data:
        effect: random
        transition: 0
        brightness: 254
        xy: [0.1684, 0.0416]
    - delay:
        milliseconds: 500
    # - service: script.strobe_b

strobe_b:
  alias: "Strobe B"
  sequence:
    - service: light.turn_off
      entity_id: light.bedroom_3
      data:
        transition: 0
    - delay:
        milliseconds: 500
    # - service: script.strobe_a
