flashing_long:
  alias: "Flashing Long and Notify"
  sequence:
    - service: light.turn_on
      entity_id:
        - group.flashlights
        # - light.hallway
        # - light.lightstrip
      data:
        transition: 1
        brightness: 250
        flash: long
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

flashing_short:
  alias: "Flashing Short and Notify"
  sequence:
    - service: light.turn_on
      entity_id:
        - group.flashlights
        # - light.hallway
        # - light.lightstrip
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id:
        - group.flashlights
        # - light.hallway
        # - light.lightstrip
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id:
        - group.flashlights
        # - light.hallway
        # - light.lightstrip
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id:
        - group.flashlights
        # - light.hallway
        # - light.lightstrip
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id:
        - group.flashlights
        # - light.hallway
        # - light.lightstrip
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

flashing_once:
  alias: "Flashing Once and Notify"
  sequence:
    - service: light.turn_on
      entity_id:
        - group.flashlights
        # - light.hallway
        # - light.lightstrip
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

notifying:
  alias: "Notify to TV and email"
  sequence:
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: script.notify_pesiphone6
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
