# strobe_a:
#   alias: "Strobe A"
#   sequence:
#     - service: light.turn_on
#       data:
#         entity_id: light.bedroom_3
#         effect: random
#         transition: 0
#         brightness: 254
#         xy: [0.1684, 0.0416]
#     - delay:
#         milliseconds: 500
#     - service: script.strobe_b

# strobe_b:
#   alias: "Strobe B"
#   sequence:
#     - service: light.turn_off
#       data:
#         entity_id: light.bedroom_3
#         transition: 0
#     - delay:
#         milliseconds: 500
#     - service: script.strobe_a

autolight_sunset_home:
  alias: "Autolighting Sunset Home"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.lightstrip
        transition: 300
        brightness: 200
        xy_color: [0.1794, 0.0964]
    - service: script.flashing_once
      data:
        title: "Lightstrip has been turned on"
        message: '15 minutes before sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 01:15:00
    - service: light.turn_off
      data:
        entity_id: light.lightstrip
        transition: 1
    - service: script.flashing_once
      data:
        title: "Lightstrip has been turned off"
        message: '1.5 hors after sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_sunset_away:
  alias: "Autolighting Sunset Away"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.garage
        transition: 300
        brightness: 255
    - service: script.notifying
      data:
        title: "Garage light has been turned on"
        message: '15 minutes before sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 01:15:00
    - service: light.turn_off
      data:
        entity_id: light.garage
        transition: 1
    - service: script.notifying
      data:
        title: "Garage light has been turned off"
        message: '1.5 hors after sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_mode_home_1:
  alias: "Autolighting Home 1"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.front_1
        transition: 5
        brightness: 200
    - service: script.flashing_once
      data:
        title: "Downstairs Light has been turned on"
        message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 01:00:00
    - service: light.turn_off
      data:
        entity_id: light.front_1
        transition: 5
    - service: script.flashing_once
      data:
        title: "Downstairs Light has been turned off"
        message: 'At 20:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_mode_home_2:
  alias: "Autolighting Home 2"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lw
        transition: 60
        brightness: 50
    - service: script.flashing_once
      data:
        title: "Bedroom LW has been turned on"
        message: 'At 21:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 02:00:00
    - service: light.turn_off
      data:
        entity_id: light.bedroom_lw
        transition: 5
    - service: script.flashing_once
      data:
        title: "Bedroom LW has been turned off"
        message: 'At 23:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_mode_away_1:
  alias: "Autolighting Away 1"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.garage
        transition: 1
        brightness: 255
    - service: script.notifying
      data:
        title: "Garage Light has been turned on"
        message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 01:00:00
    - service: light.turn_off
      data:
        entity_id: light.garage
        transition: 1
    - service: script.notifying
      data:
        title: "Garage Light has been turned off"
        message: 'At 20:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_mode_away_2:
  alias: "Autolighting Away 2"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.front_2
        transition: 1
        brightness: 255
    - service: script.notifying
      data:
        title: "Downstairs Light has been turned on"
        message: 'At 20:45pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 00:45:00
    - service: light.turn_off
      data:
        entity_id: light.front_2
        transition: 1
    - service: script.notifying
      data:
        title: "Downstairs Light has been turned off"
        message: 'At 21:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_mode_away_3:
  alias: "Autolighting Away 3"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lw
        transition: 1
        brightness: 255
    - service: script.notifying
      data:
        title: "Bedroom LW has been turned on"
        message: 'At 21:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 01:30:00
    - service: light.turn_off
      data:
        entity_id: light.bedroom_lw
        transition: 1
    - service: script.notifying
      data:
        title: "Bedroom LW has been turned off"
        message: 'At 22:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_mode_vacation_1:
  alias: "Autolighting Vacation 1"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.garage
        transition: 1
        brightness: 255
    - service: script.notifying
      data:
        title: "Garage Light has been turned on"
        message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 01:00:00
    - service: light.turn_off
      data:
        entity_id: light.garage
        transition: 1
    - service: script.notifying
      data:
        title: "Garage Light has been turned off"
        message: 'At 20:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_mode_vacation_2:
  alias: "Autolighting Vacation 2"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.front_2
        transition: 1
        brightness: 255
    - service: script.notifying
      data:
        title: "Downstairs Light has been turned on"
        message: 'At 20:45pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 00:45:00
    - service: light.turn_off
      data:
        entity_id: light.front_2
        transition: 1
    - service: script.notifying
      data:
        title: "Downstairs Light has been turned off"
        message: 'At 21:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

autolight_mode_vacation_3:
  alias: "Autolighting Vacation 3"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lw
        transition: 1
        brightness: 255
    - service: script.notifying
      data:
        title: "Bedroom LW has been turned on"
        message: 'At 21:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - delay: 01:30:00
    - service: light.turn_off
      data:
        entity_id: light.bedroom_lw
        transition: 1
    - service: script.notifying
      data:
        title: "Bedroom LW has been turned off"
        message: 'At 22:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

flashing_long:
  alias: "Flashing Long and Notify"
  sequence:
    - service: light.turn_on
      entity_id: light.common_room_1
      data:
        transition: 1
        brightness: 250
        flash: long
    - service: light.turn_on
      entity_id: light.common_room_2
      data:
        transition: 1
        brightness: 250
        flash: long
    - service: light.turn_on
      entity_id: light.bedroom_1
      data:
        transition: 1
        brightness: 250
        flash: long
    - service: light.turn_on
      entity_id: light.bedroom_2
      data:
        transition: 1
        brightness: 250
        flash: long
    - service: light.turn_on
      entity_id: light.front_1
      data:
        transition: 1
        brightness: 250
        flash: long
    - service: light.turn_on
      entity_id: light.front_2
      data:
        transition: 1
        brightness: 250
        flash: long
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

flashing_short:
  alias: "Flashing Short and Notify"
  sequence:
    - service: light.turn_on
      entity_id: light.common_room_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.common_room_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.common_room_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.common_room_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.common_room_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.common_room_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.common_room_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.common_room_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.common_room_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.common_room_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

flashing_once:
  alias: "Flashing Once and Notify"
  sequence:
    - service: light.turn_on
      entity_id: light.common_room_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.common_room_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.bedroom_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_1
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: light.turn_on
      entity_id: light.front_2
      data:
        transition: 1
        brightness: 250
        flash: short
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'

# flashing_slow:
#   alias: "Flashing Slow and Notify"
#   sequence:
#     - service: light.turn_on
#       entity_id: light.bedroom_1
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_1
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_1
#     # - service: light.turn_off
#     #   entity_id: light.common_room_1
#     - service: light.turn_on
#       entity_id: light.bedroom_2
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_2
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_2
#     # - service: light.turn_off
#     #   entity_id: light.common_room_2
#     - service: light.turn_on
#       entity_id: light.bedroom_1
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_1
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_1
#     # - service: light.turn_off
#     #   entity_id: light.common_room_1
#     - service: light.turn_on
#       entity_id: light.bedroom_2
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_2
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_2
#     # - service: light.turn_off
#     #   entity_id: light.common_room_2
#     - service: light.turn_on
#       entity_id: light.bedroom_1
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_1
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_1
#     # - service: light.turn_off
#     #   entity_id: light.common_room_1
#     - service: light.turn_on
#       entity_id: light.bedroom_2
#       data:
#         transition: 1
#         brightness: 250
#         xy_color: [0.3680,0.3686]
#         flash: short
#     - service: light.turn_on
#       entity_id: light.common_room_2
#       data:
#         transition: 1
#         brightness: 250
#         flash: short
#     - delay: 00:00:01
#     # - service: light.turn_off
#     #   entity_id: light.bedroom_2
#     # - service: light.turn_off
#     #   entity_id: light.common_room_2
#     - service: notify.tv
#       data_template:
#         title: '{{ title }}'
#         message: '{{ message }}'
#     - service: notify.email
#       data_template:
#         title: '{{ title }}'
#         message: '{{ message }}'

notifying:
  alias: "Notify to TV and email"
  sequence:
    - service: notify.tv
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    - service: notify.email
      data_template:
        title: '{{ title }}'
        message: '{{ message }}'
    # - service: script.notify_pesiphone6
    #   data_template:
    #     title: '{{ title }}'
    #     message: '{{ message }}'
