esphomeyaml:
  name: Reed
  platform: ESP8266
  board: esp01

wifi:
  ssid: 'deep'
  password: 'stupidg1rl'

mqtt:
  broker: '192.168.1.10'
  username: 'hass'
  password: '2bbadd'

# Enable logging
logger:

ota:
  password: 'stupidg1rl'
