- platform: google_travel_time
  name: "Home to Benjy"
  api_key: !secret google_travel_time_api_key
  origin: zone.home
  destination: zone.benjawan
  options:
   mode: driving
   units: metric

- platform: google_travel_time
  name: "Benjy to Home"
  api_key: !secret google_travel_time_api_key
  origin: zone.benjawan
  destination: zone.home
  options:
   mode: driving
   units: metric

- platform: google_travel_time
  name: "Home to Malaiwan"
  api_key: !secret google_travel_time_api_key
  origin: zone.home
  destination: zone.malaiwan
  options:
   mode: driving
   units: metric

- platform: google_travel_time
  name: "Malaiwan to Home"
  api_key: !secret google_travel_time_api_key
  origin: zone.malaiwan
  destination: zone.home
  options:
   mode: driving
   units: metric
