- platform: template
  sensors:
    battery_pesiphone6:
      friendly_name: "Battery on Pe iPhone 6"
      icon_template: '{% if is_state("sensor.battery_pesiphone6", "unknown") %}mdi:battery-unknown{% elif is_state_attr("device_tracker.pesiphone6", "battery_status", "Charging") %}mdi:battery-charging{% elif states.device_tracker.pesiphone6.attributes.battery <= 5 %}mdi:battery-outline{% elif states.device_tracker.pesiphone6.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.pesiphone6.attributes.battery|float / 10)|round*10}}{% endif %}'
      value_template: '{% if states.device_tracker.pesiphone6.attributes.battery %}{{ states.device_tracker.pesiphone6.attributes.battery|round }}{% else %}{{ states.sensor.battery_pesiphone6.state }}{% endif %}'
      unit_of_measurement: '%'
    battery_pesipadmini2:
      friendly_name: "Battery on Pe iPad Mini 2"
      icon_template: '{% if is_state("sensor.battery_pesipadmini2", "unknown") %}mdi:battery-unknown{% elif is_state_attr("device_tracker.pesipadmini2", "battery_status", "Charging") %}mdi:battery-charging{% elif states.device_tracker.pesipadmini2.attributes.battery <= 5 %}mdi:battery-outline{% elif states.device_tracker.pesipadmini2.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.pesipadmini2.attributes.battery|float / 10)|round*10}}{% endif %}'
      value_template: '{% if states.device_tracker.pesipadmini2.attributes.battery %}{{ states.device_tracker.pesipadmini2.attributes.battery|round }}{% else %}{{ states.sensor.battery_pesipadmini2.state }}{% endif %}'
      unit_of_measurement: '%'
    battery_juesiphone6splus:
      friendly_name: "Battery on Jue iPhone 6s Plus"
      icon_template: '{% if is_state("sensor.battery_juesiphone6splus", "unknown") %}mdi:battery-unknown{% elif is_state_attr("device_tracker.juesiphone6splus", "battery_status", "Charging") %}mdi:battery-charging{% elif states.device_tracker.juesiphone6splus.attributes.battery <= 5 %}mdi:battery-outline{% elif states.device_tracker.juesiphone6splus.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.juesiphone6splus.attributes.battery|float / 10)|round*10}}{% endif %}'
      value_template: '{% if states.device_tracker.juesiphone6splus.attributes.battery %}{{ states.device_tracker.juesiphone6splus.attributes.battery|round }}{% else %}{{ states.sensor.battery_juesiphone6splus.state }}{% endif %}'
      unit_of_measurement: '%'
    battery_juesipadmini2:
      friendly_name: "Battery on Jue iPad Mini 2"
      icon_template: '{% if is_state("sensor.battery_juesipadmini2", "unknown") %}mdi:battery-unknown{% elif is_state_attr("device_tracker.juesipadmini2", "battery_status", "Charging") %}mdi:battery-charging{% elif states.device_tracker.juesipadmini2.attributes.battery <= 5 %}mdi:battery-outline{% elif states.device_tracker.juesipadmini2.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.juesipadmini2.attributes.battery|float / 10)|round*10}}{% endif %}'
      value_template: '{% if states.device_tracker.juesipadmini2.attributes.battery %}{{ states.device_tracker.juesipadmini2.attributes.battery|round }}{% else %}{{ states.sensor.battery_juesipadmini2.state }}{% endif %}'
      unit_of_measurement: '%'
    battery_pesipodtouch4:
      friendly_name: "Battery on iPod Touch BMW"
      icon_template: '{% if is_state("sensor.battery_pesipodtouch4", "unknown") %}mdi:battery-unknown{% elif is_state_attr("device_tracker.pesipodtouch4", "battery_status", "Charging") %}mdi:battery-charging{% elif states.device_tracker.pesipodtouch4.attributes.battery <= 5 %}mdi:battery-outline{% elif states.device_tracker.pesipodtouch4.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.pesipodtouch4.attributes.battery|float / 10)|round*10}}{% endif %}'
      value_template: '{% if states.device_tracker.pesipodtouch4.attributes.battery %}{{ states.device_tracker.pesipodtouch4.attributes.battery|round }}{% else %}{{ states.sensor.battery_pesipodtouch4.state }}{% endif %}'
      unit_of_measurement: '%'
    day_night:
      friendly_name: "Day/Night"
      icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
      value_template: '{% if is_state("sun.sun", "above_horizon") %}Day{% else %}Night{% endif %}'
    solar_angle:
      friendly_name: 'Sun Angle'
      icon_template: mdi:weather-sunset
      value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
      unit_of_measurement: '°'
    uptime:
      friendly_name: Uptime
      icon_template: mdi:timelapse
      value_template: >-
        {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
        {%- set count = slb | length -%}
        {%- set hms = slb[count - 1] -%}
        {%- set hms_trimmed = hms.split('.')[0] -%}
        {%- set hms_split = hms_trimmed.split(':') -%}
        {%- set hours = hms_split[0] | int -%}
        {%- if count == 3 -%}
          {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 hour
          {%- else -%}
            {{ hours }} hours
          {%- endif -%}
        {%- endif -%}

# - platform: template
#   sensors:
#     temp_sda:
#       friendly_name: 'Temperature Disk 1'
#       icon_template: '{% if states.sensor.temperature_sda.state <= 39 %}mdi:thermometer{% else %}mdi:thermometer-lines{% endif %}'
#       value_template: '{{ states.sensor.temperature_sda.state }}'
#       # unit_of_measurement: '°C'
