- alias: "DJ Lighting Selector"
  trigger:
    platform: event
    event_type: DJ
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.who_dj
        option: Pe
