- alias: "Benjy Visits"
  initial_state: true
  hide_entity: false
  trigger:
    # - platform: state
    #   entity_id: device_tracker.benjysiphone6
    #   from: "not_home"
    #   to: "home"
    - platform: zone
      entity_id: device_tracker.benjysiphone6
      zone: zone.home
      event: "enter"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.benjy_visits
    - service: light.turn_on
      entity_id: light.hallway
      data:
        state: on
        transition: 1
        brightness: 144
        xy_color: [0.3143,0.3302]
    - service: notify.tv
      data:
        title: "Benjy arrives"
        message: 'Benjy visits and she has arrived [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Benjy Leaves"
  trigger:
    # - platform: state
    #   entity_id: device_tracker.benjysiphone6
    #   from: "home"
    #   to: "not_home"
    #   for:
    #     minutes: 10
    - platform: zone
      entity_id: device_tracker.benjysiphone6
      zone: zone.home
      event: "leave"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.benjy_visits
    - service: light.turn_off
      entity_id: light.hallway
      data:
        state: off
        transition: 1
        # brightness: 144
        # xy_color: [0.3143,0.3302]
    - service: notify.tv
      data:
        title: "Benjy leaves"
        message: 'Benjy has left for 10 minutes [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"
