### Autolighting

- alias: "Autolights All Off 1"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: time
      after: '00:01:00'
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Home
  action:
    - service: light.turn_off
      entity_id: group.all_lights
      data:
        transition: 60
    - service: script.flashing_once
      data:
        title: "All lights has been turned off"
        message: 'All lights are off after midnight everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Autolights All Off 2"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: input_select.homemode
      state: Away
      # for:
      #   minutes: 30
  action:
    - service: light.turn_off
      entity_id: group.all_lights
      data:
        transition: 1
    - service: script.notifying
      data:
        title: "All lights has been turned off"
        message: 'All lights are off when noboby is home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Autolight Sunset Home"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Home
  action:
    - service: script.autolight_sunset_home

- alias: "Autolight Sunset Away"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Away
  action:
    - service: script.autolight_sunset_away

- alias: "Autolight Home 1"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      hours: 19
      minutes: 30
      seconds: 0
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Home
  action:
    - service: script.autolight_mode_home_1

- alias: "Autolight Home 2"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      hours: 21
      minutes: 0
      seconds: 0
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Home
  action:
    - service: script.autolight_mode_home_2

- alias: "Autolight Away 1"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      hours: 19
      minutes: 30
      seconds: 0
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Away
  action:
    - service: script.autolight_mode_away_1

- alias: "Autolight Away 2"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      hours: 20
      minutes: 45
      seconds: 0
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Away
  action:
    - service: script.autolight_mode_away_2

- alias: "Autolight Away 3"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      hours: 21
      minutes: 0
      seconds: 0
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Away
  action:
    - service: script.autolight_mode_away_3

- alias: "Autolight Vacation 1"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      hours: 19
      minutes: 30
      seconds: 0
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Vacation
  action:
    - service: script.autolight_mode_vacation_1

- alias: "Autolight Vacation 2"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      hours: 20
      minutes: 45
      seconds: 0
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Vacation
  action:
    - service: script.autolight_mode_vacation_2

- alias: "Autolight Vacation 3"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      hours: 21
      minutes: 0
      seconds: 0
  condition:
    - condition: state
      entity_id: input_select.homemode
      state: Vacation
  action:
    - service: script.autolight_mode_vacation_3

### Dune

# - alias: "Dune Not Playing"
#   initial_state: true
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: media_player.dune
#       from: "playing"
#       to: "idle"
#   condition:
#     condition: state
#     entity_id: sun.sun
#     state: "below_horizon"
#   action:
#     - service: scene.turn_on
#       entity_id: scene.common_room_alive
#
# - alias: "Dune Playing"
#   initial_state: true
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: media_player.dune
#       from: "idle"
#       to: "playing"
#   condition:
#     condition: state
#     entity_id: sun.sun
#     state: "below_horizon"
#   action:
#     - service: scene.turn_on
#       entity_id: scene.common_room_dim
