- alias: "Loop Light Bedroom"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: time
      minutes: "/1"
      seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.loop_light_bedroom
    state: "on"
  action:
    - service: light.turn_on
      entity_id: light.bedroom_3
      data:
        effect: random
        transition: 1
        brightness: 100
    - service: light.turn_on
      entity_id: light.bedroom_4
      data:
        effect: random
        transition: 1
        brightness: 100
    - service: notify.tv
      data:
        title: "Loop Bedroom Lights"
        message: 'Two lights in Bedroom are set to colour looping [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Loop Light Common Room"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: time
      minutes: "/1"
      seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.loop_light_common_room
    state: "on"
  action:
    - service: light.turn_on
      entity_id: light.lightstrip
      data:
        effect: random
        transition: 2
        brightness: 255
    - service: light.turn_on
      entity_id: light.hallway
      data:
        effect: random
        transition: 2
        brightness: 255
    - service: notify.tv
      data:
        title: "Loop Common Room Lights"
        message: 'Two lights in Common Room are set to colour looping [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Loop Light Hallway"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: time
      minutes: "/1"
      seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.loop_light_hallway
    state: "on"
  action:
    - service: light.turn_on
      entity_id: light.hallway
      data:
        effect: random
        transition: 2
        brightness: 255
    - service: notify.tv
      data:
        title: "Loop Hallway Light"
        message: 'Hallway light is set to colour looping [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"
