- alias: "Sunset 1"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: sun
      event: sunset
      offset: "-02:00:00"
  action:
    - service: notify.tv
      data:
        title: "Sunset in 2 hours"
        message: 'Sunset can be expected in approx. two hours [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Sunset 2"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  action:
    - service: notify.tv
      data:
        title: "Sunset in 1 hour"
        message: 'Sunset can be expected in approx. one hour [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Sunset 3"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: notify.tv
      data:
        title: "Sunset in 30 minutes"
        message: 'Sunset can be expected in approx. 30 minutes [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Sunset 4"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: sun
      event: sunset
      offset: "+00:00:00"
  action:
    - service: notify.tv
      data:
        title: "The sun is down now"
        message: 'Sunset is happening now, another goodbye to the day [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

# - alias: "Software update"
#   initial_state: false
#   hide_entity: true
#   trigger:
#     - platform: state
#       entity_id: updater.updater
#   action:
#     - service: notify.tv
#       data:
#         title: "Home Assistant Update"
#         message: "Software update for Home Assistant is now available"
#
# - alias: "Notify CR 1"
#   initial_state: true
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: light.common_room_1
#       to: 'on'
#       from: 'off'
#   action:
#     - service: notify.email
#       data:
#         title: "Auto-message"
#         message: 'Common Room Light #1 has been set to On [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
#     - service: notify.tv
#       data:
#         title: "Auto-message"
#         message: 'Common Room Light #1 has been set to On [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
#
# - alias: "Notify CR 2"
#   initial_state: true
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: light.common_room_2
#       to: 'on'
#       from: 'off'
#   action:
#     - service: notify.email
#       data:
#         title: "Auto-message"
#         message: 'Common Room Light #2 has been set to On [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
#     - service: notify.tv
#       data:
#         title: "Auto-message"
#         message: 'Common Room Light #2 has been set to On [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
#
# - alias: "Notify BR 1"
#   initial_state: true
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: light.bedroom_3
#       to: 'on'
#       from: 'off'
#   action:
#     - service: notify.email
#       data:
#         title: "Auto-message"
#         message: 'Bedroom Light #3 has been set to On [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
#     - service: notify.tv
#       data:
#         title: "Auto-message"
#         message: 'Bedroom Light #3 has been set to On [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
#
# - alias: "Notify BR 2"
#   initial_state: true
#   hide_entity: false
#   trigger:
#     - platform: state
#       entity_id: light.bedroom_4
#       to: 'on'
#       from: 'off'
#   action:
#     - service: notify.email
#       data:
#         title: "Auto-message"
#         message: 'Bedroom Light #4 has been set to On [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
#     - service: notify.tv
#       data:
#         title: "Auto-message"
#         message: 'Bedroom Light #4 has been set to On [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
