- alias: "Software update"
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.tv
      data:
        title: "Home Assistant Update"
        message: "Software update for Home Assistant is now available"

# - alias: "Notify CR 1"
#   trigger:
#     platform: state
#     entity_id: light.common_room_1
#     to: 'on'
#     from: 'off'
#   action:
#     - service: notify.tv
#       data:
#         title: "Notify from pe"
#         message: "Light Common Room 1 is on"
#         data:
#           displaytime: 20000
#           icon: "warning"
#
# - alias: "Notify CR 2"
#   trigger:
#     platform: state
#     entity_id: light.common_room_2
#     to: 'on'
#     from: 'off'
#   action:
#     - service: notify.tv
#       data:
#         title: "Notify from pe"
#         message: "Light Common Room 2 is on"
#
# - alias: "Notify BR 1"
#   trigger:
#     platform: state
#     entity_id: light.bedroom_3
#     to: 'on'
#     from: 'off'
#   action:
#     - service: notify.tv
#       data:
#         title: "Notify from pe"
#         message: "Light Bedroom 3 is on"
#
# - alias: "Notify BR 2"
#   trigger:
#     platform: state
#     entity_id: light.bedroom_4
#     to: 'on'
#     from: 'off'
#   action:
#     - service: notify.tv
#       data:
#         title: "Notify from pe"
#         message: "Light Bedroom 4 is on"
