- alias: "Sunset 1"
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "-02:00:00"
  action:
    - service: notify.tv
      data:
        title: "Sunset in 2 hours"
        message: 'Sunset can be expected in approx. two hours [{{now().strftime("%d.%m.%Y")}} at {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Sunset 2"
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    - service: notify.tv
      data:
        title: "Sunset in 1 hour"
        message: 'Sunset can be expected in approx. one hour [{{now().strftime("%d.%m.%Y")}} at {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Sunset 3"
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    - service: notify.tv
      data:
        title: "Sunset in 30 minutes"
        message: 'Sunset can be expected in approx. 30 minutes [{{now().strftime("%d.%m.%Y")}} at {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Sunset 4"
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "+00:00:00"
  action:
    - service: notify.tv
      data:
        title: "The sun is down now"
        message: 'Sunset is happening now, another goodbye to the day [{{now().strftime("%d.%m.%Y")}} at {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Autolight for sunset 1"
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.pesiphone6
        state: home
      - condition: state
        entity_id: device_tracker.juesiphone6splus
        state: home
  action:
    - service: light.turn_on
      entity_id: light.lightstrip
      data:
        transition: 5
        brightness: 178
        xy_color: [0.1794, 0.0964]
    # - service: light.turn_on
    #   entity_id: light.garage
    #   data:
    #     transition: 5
    #     brightness: 178
    - service: notify.tv
      data:
        title: "Lightstrip has been turned on"
        message: 'Automatically turn on 30 minutes before sunset only when someone is home [{{now().strftime("%d.%m.%Y")}} at {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Autolight for sunset 2"
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.pesiphone6
        state: not_home
      - condition: state
        entity_id: device_tracker.juesiphone6splus
        state: not_home
  action:
    # - service: light.turn_on
    #   entity_id: light.lightstrip
    #   data:
    #     transition: 5
    #     brightness: 178
    #     xy_color: [0.1794, 0.0964]
    - service: light.turn_on
      entity_id: light.garage
      data:
        transition: 5
        brightness: 178
    - service: notify.tv
      data:
        title: "Garage light has been turned on"
        message: 'Automatically turn on 30 minutes before sunset only when noone is home [{{now().strftime("%d.%m.%Y")}} at {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Autolight for sunset 3"
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: "+02:00:00"
  # condition:
  #   condition: and
  #   conditions:
  #     - condition: state
  #       entity_id: device_tracker.pesiphone6
  #       state: not_home
  #     - condition: state
  #       entity_id: device_tracker.juesiphone6splus
  #       state: not_home
  action:
    - service: light.turn_off
      entity_id: light.lightstrip
      data:
        transition: 5
      #   brightness: 178
      #   xy_color: [0.1794, 0.0964]
    - service: light.turn_off
      entity_id: light.garage
      data:
        transition: 5
        # brightness: 178
    - service: notify.tv
      data:
        title: "Auto light(s) has been turned off"
        message: 'Automatically turn off all auto light(s) 2 hors after sunset [{{now().strftime("%d.%m.%Y")}} at {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"
