- alias: "Jue Leaves Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.juesiphone6splus
      event: leave
      zone: zone.home
  action:
    - service: notify.tv
      data:
        title: "Jue has left Home"
        message: 'Jue has left Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Jue Arrives Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.juesiphone6splus
      event: enter
      zone: zone.home
  action:
    - service: notify.tv
      data:
        title: "Jue has arrived home"
        message: 'Jue has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Jue Leaves Malaiwan"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.juesiphone6splus
      event: leave
      zone: zone.malaiwan
  action:
    - service: notify.tv
      data:
        title: "Jue has left Malaiwan"
        message: 'Jue has left Malaiwan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Jue Arrives Malaiwan"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.juesiphone6splus
      event: enter
      zone: zone.malaiwan
  action:
    - service: notify.tv
      data:
        title: "Jue has arrived Malaiwan"
        message: 'Jue has arrived Malaiwan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Pe Leaves Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.pesiphone6
      event: leave
      zone: zone.home
  action:
    - service: notify.tv
      data:
        title: "Pe has left Home"
        message: 'Pe has left Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Pe Arrives Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.pesiphone6
      event: enter
      zone: zone.home
  action:
    - service: notify.tv
      data:
        title: "Pe has arrived home"
        message: 'Pe has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Pe Leaves Benjawan"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.pesiphone6
      event: leave
      zone: zone.benjawan
  action:
    - service: notify.tv
      data:
        title: "Pe has left Benjawan"
        message: 'Pe has left Benjawan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"

- alias: "Pe Arrives Benjawan"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.pesiphone6
      event: enter
      zone: zone.benjawan
  action:
    - service: notify.tv
      data:
        title: "Pe has arrived Benjawan"
        message: 'Pe has arrived Benjawan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
        data:
          displaytime: 2000
          icon: "warning"
