- alias: "Jue Leaves Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.juesiphone6splus
      event: leave
      zone: zone.home
  action:
    - service: script.notifying
      data:
        title: "Jue has left home"
        message: 'Jue has left home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Jue Gets Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('proximity.jue_home', 'dir_of_travel', 'towards') }}"
  condition:
    - condition: numeric_state
      entity_id: proximity.jue_home
      below: 3000
      above: 1500
  action:
    - service: script.flashing_long
      data:
        title: "Jue is on the way home"
        message: 'Jue is on the way home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Jue Arrives Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.juesiphone6splus
      event: enter
      zone: zone.home
  action:
    - service: script.flashing_long
      data:
        title: "Jue has arrived home"
        message: 'Jue has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - service: input_select.select_option
      data:
        entity_id: input_select.homemode
        option: Home

- alias: "Jue Leaves Malaiwan"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.juesiphone6splus
      event: leave
      zone: zone.malaiwan
  action:
    - service: script.flashing_short
      data:
        title: "Jue has left Malaiwan"
        message: 'Jue has left Malaiwan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Jue Arrives Malaiwan"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.juesiphone6splus
      event: enter
      zone: zone.malaiwan
  action:
    - service: script.flashing_short
      data:
        title: "Jue has arrived Malaiwan"
        message: 'Jue has arrived Malaiwan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Pe Leaves Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.pesiphone6
      event: leave
      zone: zone.home
  action:
    - service: script.notifying
      data:
        title: "Pe has left home"
        message: 'Pe has left home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Pe Gets Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('proximity.pe_home', 'dir_of_travel', 'towards') }}"
  condition:
    - condition: numeric_state
      entity_id: proximity.pe_home
      below: 3000
      above: 1500
  action:
    - service: script.flashing_long
      data:
        title: "Pe is on the way home"
        message: 'Pe is on the way home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Pe Arrives Home"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.pesiphone6
      event: enter
      zone: zone.home
  action:
    - service: script.flashing_long
      data:
        title: "Pe has arrived home"
        message: 'Pe has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - service: input_select.select_option
      data:
        entity_id: input_select.homemode
        option: Home

- alias: "Pe Leaves Benjawan"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.pesiphone6
      event: leave
      zone: zone.benjawan
  action:
    - service: script.flashing_long
      data:
        title: "Pe has left Benjawan"
        message: 'Pe has left Benjawan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Pe Arrives Benjawan"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.pesiphone6
      event: enter
      zone: zone.benjawan
  action:
    - service: script.flashing_short
      data:
        title: "Pe has arrived Benjawan"
        message: 'Pe has arrived Benjawan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Away Mode"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: device_tracker.pesiphone6, device_tracker.juesiphone6splus
      state: 'not_home'
      for:
        hours: 1
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.homemode
        option: Away
    - service: notify.email
      data:
        title: "Away Mode is now active"
        message: 'Away Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Vacation Mode"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: device_tracker.pesiphone6, device_tracker.juesiphone6splus
      state: 'not_home'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.homemode
        option: Vacation
    - service: notify.email
      data:
        title: "Vacation Mode is now active"
        message: 'Vacation Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

- alias: "Benjy Arrives"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.benjysiphone6
      zone: zone.home
      event: "enter"
  action:
    - service: script.flashing_long
      data:
        title: "Benjy arrives"
        message: 'Benjy visits and she has arrived [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - service: input_boolean.turn_on
      entity_id: input_boolean.benjy_visits

- alias: "Benjy Leaves"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: zone
      entity_id: device_tracker.benjysiphone6
      zone: zone.home
      event: "leave"
  action:
    - service: script.flashing_short
      data:
        title: "Benjy leaves"
        message: 'Benjy has left [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
    - service: input_boolean.turn_off
      entity_id: input_boolean.benjy_visits
