automation:

  - alias: "Auto Air-conditioning Bedroom Powerful"
    trigger:
      - platform: state
        entity_id: switch.bedroom_air_cond
        from: 'off'
        to: 'on'
        for:
          minutes: 3
    condition:
      - condition: template
        value_template: '{{ states.sensor.pandora_temperature.state | float > 30 }}'
    action:
      - service: script.bedroom_ac_control
        data:
          packet: "powerful"
