switch:

  # - platform: broadlink
  #   name: "RM Pro"
  #   host: !secret rmpro_ip
  #   mac: !secret rmpro_mac
  #   timeout: 30
  #   switches:
  #     common_room_air_cond:
  #       friendly_name: "Common Room Air Cond"
  #       command_on: 'JgCaAAc0AAEnlhQ4FhEUORMSFRIUExURFRIUOBQTFBMTOBUSFBQTExQSFDgUEhY3FBIUExQ4FBIWERQTFDcVOBQSFTcVExM5FBIUEhQTFBIVOBQ3FjcVNhUSFhEVEhQTFDcUExQSFTcWEhMSFRIUExQ4FTcUORU2FhAVOBQ4FTcVNxU3FTcUORM4FDgUOBQTFDgUNxU4FREUERUADQUAAAAAAAAAAAAAAAAAAA=='
  #       command_off: 'JgCcAAABKJYTOBUSFDkTEhUSFBQTEhQTFREUExURFRMTFBQSFBIVEhQ3FRIVNxUSFBMVNhUSFRMTExQ3FjgTEhQ4FBMUOBUTExIUExQTEzgWNhU4ExQVERQSFRIVEhQ3FhITExU4FBIUEhUSFBIUOBQ4FjYUFBMSFTkTORM4FTcUORM4FDgUOBYRFBMUNxURFjYVEhQTFDYVAAWNCAANBQAAAAAAAAAAAAAAAA=='
  #     common_room_fan:
  #       friendly_name: "Common Room Fan"
  #       command_on: 'JgAiASoNKQ0QJysNKQ4OKRAnECgOKg0qDSkr6ioNKQ0QKCoNKwwPKA8oDygPKQ0rDycq6ikOKg0PKSkNLAsQKQ4oDygQKA4pDigq6ioOKwwQJysNKgwRJg8pDygPKQ4qDicq7CgOKQ0RJyoNKg4OKA8pDycPKQ8pDycq6ioOKQ4OKCoNLAwOKg4pDigOKg8oDygr6SkOKQ4PKSkOKQ0QKQ0pDioNKRAoDigs6SkOKg0PKCoNKw0OKQ4pDygOKQ4pDygq6isMKw0QJysMKg4NKREmECcQKA8oDykp6yoNKgwQKCoOKQ0PKQ8oDigPKBAoECgq6ioMKw0PKCkNKwwQKA8oDygOKQ8qDSkp6iwNKA4PKCoNKw0PKA4pDikOKQ4rDCoqAA0FAAAAAAAA'
  #       command_off: 'JgDyACsOKgwPKSkNKwwPKQ4pDikOKQ4pDiks6SwKKg8OKCkPKwwOKA8pDioOKA8oDikr6SoNKg0PKCsNKQ4PKA8pDSoPKA8oECcs6SkNKw0OKCsMLQsPKQ4oECcOKQ8qDigr6SoNKg0QKSoLKg0PKg4pDycOKg0pDygr6ioMLAwPKCoNKw0OKBAnECkOKA4pDygq6isMKw0QJykOKg0OKRAnECkOKA8oDykq6isLLA0MKSoNKg4PKA8oECgPKQ4oDygq6iwLKg0PKCsMKg0QKQ4oDykOKQ8pDicq6isNKg4PJyoNKwwQJxEnDygPKA4pECgpAA0FAAAAAAAA'
  #     common_room_tv:
  #       friendly_name: "Common Room TV"
  #       command_on: 'JgDkAAYAAdxQEikTFBEqERUTKBMUDhoRKhEVExMVExMUAANKURIpERYRKREWEykSExQUEioQFRIXEhQSFgADSFASKxAUFCgSFRIpEhQSFRMpExQTExIVExUAA0lQEioRFBMpEhUSKhAVExQTKBIUExUSFRMWAANJURApEhYRKxETEygTFBIVEysQFBMUExQTFgADSVEQKhEVEioRFBMpEhQTFBMpERUUExMUExYAA0hREikRFRQoERUTKRIUExQSKREWEhYRFRIWAANKUBEpEhYSKRAVEisQFRIWEikRFRIWERUSFgANBQAAAAA='
  #       command_off: 'JgDEAFATKhAUFCgSFBQoEhUSFBMqEBUUExMWERUAA0pRESgTFRIpERYRKhEVExQTKBIVEhQTFRMVAANKTxMpERQTKBIWESkTFBIWEycSFBMUExUTFgADSFATKRITFCgRFRMoExQTFBIqERQTFRMUEhYAA0lRESoRFBQoEhQTKREWERUTKBMTFBMTFRMUAANKUBIpEhQTKhEUEygSFRIVEikSFBQUEhUUFAADSVASKRIUEykRFRQnExQTFBIqERQTFBQUExUADQUAAAAA'
  #     common_room_android_box:
  #       friendly_name: "Common Room Android Box"
  #       command_on: 'JgBYAAABKJIUERYPFBEUERU1ExIUERMSEzgSNxQ1FTUUERU1FDYTNxM3FBEUNhM4EjYUERQ3ExISEhU1FBETEhMSEzgUEBQ3EgAFEwABJ0sSAAxKAAEpSRMADQU='
  #       command_off: 'JgBcAAgACe4AASiSFBAUERMSFBEUNhMTEhIUERQ2FDcSNxM2FBEUNhQ2EzcTNxMTFTQTNxM2FBEUNhQSExIUNxESExMTEhQ1ExITNxMABRMAAShKEgAMSgABJ0oTAA0FAAAAAAAAAAAAAAAA'

  - platform: broadlink
    name: "RM Mini A"
    host: !secret rmmini_a_ip
    mac: !secret rmmini_a_mac
    timeout: 30
    switches:
      bedroom_air_cond:
        friendly_name: "Bedroom Air Cond"
        command_on: 'JgC8AXE4DyoODg4ODg8OKg8ODg4ODg4ODisPDQ4rDSsPDg0rDyoOKg8qDioPDg0PDioODw0PDg4ODg4PDQ8PKg4qDyoNKw8NDg8ODg4ODg8ODg4ODg4ODw0PDw0ODg8ODg4PDQ4PDQ8ODg8NDg8NDw4ODw4NDw0PDisODg4ODg4ODw0PDg4OAAPMcTkOKg4PDQ8PDQ8qDg4ODg4PDQ8OKg8ODioPKg0PDisNKw8qDioPKg4ODw0PKg4ODw0PDg0PDg4ODw4ODg4ODg8ODg4ODg4ODg8ODg4ODg8NDw0rDw4NDw4ODisNKw8ODg4ODg4ODg8NKw8NDisPDQ4PDQ8NDw8NDw4NDw4ODg4ODw0rDyoNKw4rDg4PKg4ODyoOKg4rDSsPKg4ODg4ODw0PDg4ODg4PDQ8ODg4ODw4NDw8NDg8ODg4ODg4ODw0PDg4ODg4PDQ8ODg4PDQ8ODg4ODg8NDw4ODg4ODw0PDg4ODw0PDg4ODg4PDQ8ODg4ODg8ODg4ODg8ODg4ODw0PKg4qDw4NDw4ODg8NDw4ODw0PDg0PDg4ODg4PDQ8PDQ4PDQ8NKw4PDQ8OKg8ODioOKw4qDwANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgC8AXA5DyoODg4ODg8NKw4ODg8NDw4ODisODg4rDSsODg4rDioPKg4rDioPDQ4PDSsODw0PDQ8ODg4PDQ8OKg8qDioPKg8NDg8NDw4ODg4ODw0PDg4ODw0PDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw0PDg4ODw0PDioODw0PDg4ODw0PDQ8OAAPMcTkOKg4PDQ8ODg4rDg4ODg4ODg8NKw4PDSsOKw4ODioOKw4rDSsOKw0PDg4OKw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8NDw4ODg8NDw4ODg4ODw0PDg4ODg4PDSsPKg4ODg4ODw0PDg4OKw0PDisODg4ODg4ODw0PDg4ODw0PDQ8ODg4rDioPKg4qDw4NKw4PDSsPKg0rDisOKg8ODQ8ODg4ODg8NDw4ODg8NDw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8NDw4ODg8NDw4ODg4ODw0PDg4ODw0PDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw0PDg4ODw0PDg4ODg4PDQ8OKg4rDg4ODw0PDg4ODg4PDQ8ODg4PDQ8NDw4ODg8NDw4ODg4ODw0PDg4OKw0PDisNKw8qDgANBQAAAAAAAAAAAAAAAA=='
        # command_on: 'JgC8AXI4DioODw4ODg4PKg4ODg4ODg8ODioPDg0rDyoNDw8pDisOKw0rDyoODg4ODyoODg8NDw4ODg4ODg4OKw8pDyoPKg0PDg4ODg4PDg4PDQ4PDQ8ODg4ODg8NDw4ODw0PDg4ODg4ODw0PDg4PDQ8ODg4ODg8NDyoPDQ8ODQ8ODg4ODg8NAAPNcDkPKg4ODg4PDg4qDw4NDw4ODw0OKw4ODisOKg4PDioPKg4qDyoOKg8ODg4OKg4PDQ8ODg8ODg4ODg4ODg8ODg4ODw0ODw4ODw0PDg0PDg4ODg4rDg4PDQ4PDSsPKg4ODg4PDg4ODg4PKg4ODisODg4ODg4ODw4ODg4PDg4ODg4PDQ4rDioPKg8pDg8NKw4PDioPKg4qDyoOKg4PDQ8ODg4ODg8NDw4ODw4NDw4ODw0ODw4ODg4ODg4PDg4PDQ8ODg4ODg8NDg8NDw4ODg4ODw0PDw0PDg4ODg4PDQ8ODg4PDQ8ODg4ODg4ODw4NDw4ODg4PDg4ODg4PDg0PDg4PKg4qDw0PDg4ODw0ODw0PDg4PDQ4PDg4ODg4ODw4NDw8NDg8OKg8NDw4NKw4ODisPKg4qDwANBQAAAAAAAAAAAAAAAA=='
        # command_off: 'JgC8AXE5DioPDg0PDg4PKg4ODg4ODw4ODioPDg0rDyoODg4rDioPKg4qDyoODg8NDisPDQ4ODg8NDw4ODw4NKw4rDioPKg4ODg4ODw0PDg4ODg4PDg4ODg8ODQ8ODg4ODg8ODg4ODg4PDg0PDw0ODxAMDg4ODg8ODSsPDQ4PDQ8ODg4PDQ8OAAPMcTkOKg8NDg8ODg4qDg8NDw4ODw4NKw8NDisOKg8ODSsPKg4qDyoPKQ8ODg4OKw4ODg4ODg4PDg4ODg8ODQ8ODg4ODg8NDw4ODg4PDg4ODg4ODw0PDg4ODg4PDSsOKw4OEAwODw0PDg4OKw4ODioPDg4ODg4ODw0PDg4ODg4PDQ8ODg4rDioPKg4qDw4NKw8ODioPKg4qDyoOKg8ODQ8ODg4ODg8NDw4ODg4ODw0PDg4RDA4ODg4ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODg4ODw0PDg4ODw4ODg4ODg4PDQ8ODg8NDg8NDw4ODg8NDw4ODg4PDg4ODg4ODg4PDg4OKw0rDw0ODw0PDg4ODg4PDQ8ODg8ODg4ODg4ODg8NDw4ODw0ODw0PDw0OKw4ODisOKg8qDgANBQAAAAAAAAAAAAAAAA=='
      bedroom_tv:
        friendly_name: "Bedroom TV"
        command_on: 'JgBGAJWaEzYSOBI3EhUSExEUEhMRFhE4ETkSNxIVERQRFBETEhUSExE5ERMSFRITERMSFBEWEDkRExI4EjoROBI4ETgSNxAADQUAAA=='
        command_off: 'JgCMAJaZEzYSOBI4ERUSFBETEhMRFhE4EjgSNxIVERQSExETEhUSExE5ERMSFRITEhMRFBEWETgSExE4EjoRORE4EjgRNxAABdaWmRE4EjgROBIVERMSFBAUEhUSNxI4EjcSFRITERQRFBEWERMSOBEUERYRExITERQRFRI4EhMRORE6EjcSOBI3EjgQAA0FAAAAAAAAAAAAAAAA'
      bedroom_denon:
        friendly_name: "Bedroom Denon"
        command_on: 'JgCIAAcbCTwJGQoZCRkKOwoZCRkKGQkZCTwJPAk8CRoJGQkABZ8JGgk8CRkKGQkZChkJPAk8CTwJOwoZChkJGQk8CTwJAAWfCRoJOwoZCRoJGQk8CRoJGQoZCRkJPAk8CTwJGQoZCQAFnwkaCTwJGQkaCRkJGgk8CTsKOwo7ChkJGQoZCTwJPAkADQU='
        command_off: 'JgDMAAcbCTwJGQoZCRkKGQk8CRkKGQkZCjsJPAo7CRoJGQoABZ4KGQk8CRkKGQkZCjsJGgk8CTwJPAkZCRoJGQk8CTwJAAWfCRoJPAkZChkJGQoZCTwJGQoZCRkJPAk8CTwJGgkZCQAFnwoZCTwJGQoZCRkKOwkaCTwJOwo7ChkJGQoZCTwJPAkABZ8JGgk8CRkJGgkZChkJOwoZCRoJGQk8CTwJPAkZChkJAAWfCRoJOwoZCRoJGQo7CRkKOwo7CjoLGQkZChkJPAk8CQANBQAAAAAAAAAAAAAAAA=='

  - platform: broadlink
    name: "RM Mini B"
    host: !secret rmmini_b_ip
    mac: !secret rmmini_b_mac
    timeout: 30
    switches:
      common_room_air_cond:
        friendly_name: "Common Room Air Cond"
        command_on: 'JgCYAAABKJcUOBQSFDgUExQSFBMUExQSFDgWERQTFDgUEhQTFBIWERQ4FRIVNxURFDgWERMUExMUExMTExQTFBU3FRETFBM5FRISFBYRFTcVEhU3FREVEhURExQVEhI6FRETFBIUEzkWERIVEhQSOhYRFTcTFBIUFjYTORM5EzkWNhY3FTcTORMTFjYWERUREzkTORU3ExITAA0F'
        command_off: 'JgCYAAABJ5cTORMUEzkTFBMTEhUTExMUExQSFBIVEhQTFBMUExMSFRI6ExQSORQTEzkTFBIWEhMTFBIUExQUExE6FBMTFBM5ExMUExMUEjoTExM5ExQTFBIUExQSFBI6EhUTFBMTEzkTFBMUExMSOhMUEjoSFBMUEzkTORM5EzkTORM5FDgTORU3FDkSFBI6EzkSOhM5ExITAA0F'
      common_room_fan:
        friendly_name: "Common Room Fan"
        command_on: 'JgCSACoOKQ4NKSoPKA8NKQ4pDikPKA8pDikq6ikPKQ4NKSoPKA8NKQ4pDikOKQ4pDykp6ioPKQ4NKSoOKQ8MKQ8pDikOKQ4pDikq6ioPKA8NKSoOKQ4NKQ8pDikOKQ4pDikq6ioOKQ8NKSkPKQ4NKQ4pDikPKQ4pDikq6SoPKQ4NKSoPKA8NKQ4pDikOKQ8pDikqAA0FAAAAAAAA'
        command_off: 'JgCSACkQJxAMKigQJxAMKg8oDSsNKg0qDSop6ykPKBALKygQJxAMKg0qDSoNKw0qDikp6ykPKA8MKikQJxANKQ4pDikOKQ4qDikp6ykPKA8NKSoOKQ8NKQ4pDikOKQ4pDikq6ioPKA8NKSoOKQ4NKQ8pDikOKQ4pDikq6ioPKA8NKSkPKQ4NKQ4pDykOKQ4pDikqAA0FAAAAAAAA'
      common_room_tv:
        friendly_name: "Common Room TV"
        command_on: 'JgDEAE0VKBMRFiYVExQnExIWExQnExIVFBMSFhQAA0pNFSgTExUnExMVJhQTExIWJxMUExQUERcRAANMThQoExIVKBMTFScTERYTFCYUEhYRFhEWFAADSk4VJxMUEygTExQoExMUERYoExEWExQTFBIAA0xQEycTFBQlFRMVJxMTFBMUKBMRFhMUExQUAANLTxMmFRMUJxMUEygTExQSFSgTExQTFBQTFAADS00VJhUTFCcTEhYlFRIVEhUmFRIVEhUSFhIADQUAAAAA'
        command_off: 'JgCoAFATJhUTEygTExQoExMUExQmFREWERYTFBQAA0pOFScTFBMoExMUJhYQFhEWKBMTFRAXEBYUAANKUBMnExQUJxMUEygTERcRFSgTExQTFBIVFAADS08TKBMTFCcTEhUoExMUEhUmFRMUExQSFRMAA0tOFiYTFBQnExMUKBMTFRAWKBMTFBMUExQUAANKUBMmFBQTKBMSFSgTExQRFigTExQTFBIVFAANBQ=='
      common_room_android_box:
        friendly_name: "Common Room Android Box"
        command_on: 'JgBQAAABJ5MRFBEUERQRFBE5ExIRFBEUEzcTNxE5EjgRFBE5EjcTNxM3ExIROBQ3EzcRFBE5ERQRFBI4EhMSExEUEjcRFBM3EQAFFgABJ0oTAA0FAAAAAAAAAAA='
        command_off: 'JgBYAAABJ5MUERQRFBETEhM2FBITEhMRFDYUNhQ2FDYUERQ2FDYUNhQ2ExITNxM2FDYUERQ2FBEUERQ2FBEUERQRFDYUERQ2FAAFEwABJ0kTAAxMAAEnShEADQU='

binary_sensor:
  - platform: trend
    sensors:
      common_room_warmer:
        friendly_name: 'Common Room Warmer'
        entity_id: sensor.mimas_temperature
        sample_duration: 180
        min_gradient: 0.00055555555
        device_class: heat
      common_room_colder:
        friendly_name: 'Common Room Colder'
        entity_id: sensor.mimas_temperature
        sample_duration: 180
        min_gradient: -0.00055555555
        device_class: cold
  # - platform: threshold
  #   threshold: 25
  #   type: upper
  #   entity_id: sensor.mimas_temperature
  #   name: 'Common Room is getting hot'
  #   device_class: heat
  - platform: trend
    sensors:
      bedroom_warmer:
        friendly_name: 'Bedroom Warmer'
        entity_id: sensor.pandora_temperature
        sample_duration: 180
        min_gradient: 0.00055555555
        device_class: heat
      bedroom_colder:
        friendly_name: 'Bedroom Colder'
        entity_id: sensor.pandora_temperature
        sample_duration: 180
        min_gradient: -0.00055555555
        device_class: cold
  # - platform: threshold
  #   threshold: 25
  #   type: upper
  #   entity_id: sensor.pandora_temperature
  #   name: 'Bedroom is getting hot'
  #   device_class: heat
