switch:
  - platform: broadlink
    mac: !secret rmmini_a_mac
    switches:
      - name: "Bedroom Air Cond"
        command_on: 'JgC8AXE4DisPDQ8ODg4OKg8ODQ8ODg4PDSsPDQ8qDioPDg0rDyoOKg8qDioPDg0PDioPDg4ODg4PDg0PDg4PKg4qDyoOKg8ODQ8ODg4ODg8ODg8NDw4NDw0PDg4ODw4ODg4ODg4PDg4ODg8ODQ8NDw4ODw4ODg4ODisODg4ODw4NDw0PDg4PAAPLcTkOKg4PDg4PDQ8qDg4PDQ4PDQ8OKg8ODioPKg4ODisOKg4rDSsPKg4ODg4OKw4ODw0ODw4ODw0PDg0PDg4PDQ4PDQ8ODg8NDw4ODg8NDw4ODg4qDw4ODg4ODyoOKg8ODg4ODg8NDw4NKw8NDyoPDQ8ODg4ODg4ODw4NDw4ODw0PDg0rDyoOKg8qDg4OKw4ODioPKg8qDioPKg4ODw0PDQ8ODg4ODg8ODQ8ODg8NDg8NDw4ODg4PDg4ODw0ODw4ODg4PDQ8ODQ8ODg8NDw4NDw4ODg8NDw4ODw0PDg0PDw0ODg8ODQ8PDQ4PDg4ODg8NDw4NDw4ODg4ODw4ODw0PKg4qDw4ODg4ODg4PDg0PDw0PDg4ODg4PDQ8ODQ8ODg4ODw4NKw8ODQ8OKg8ODSsOKw4qDwANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgC8AXE5DyoODg8NDg8NKw8NDg8ODg4ODisODg4qDyoPDQ8qDioPKg8pDyoPDQ4PDioPDQ8ODg4ODg4PDg4OKg8qDioPKg8NDw0PDg0PDw0ODw4ODg4PDQ4PDQ8ODg8NDw4ODg8NDg8NDw4ODw0PDg0PDg4PDQ8ODioPDg4ODg4PDQ8ODg4OAAPMcTkOKg8NDw4ODg4qDw4ODg8NDw4OKg8NDisOKg8ODioPKg4qDyoOKg8ODg4OKg8ODg4PDQ4PDg4ODg4ODw4ODg4ODg8ODg4ODw0ODw4ODg4PDQ8ODg4PDQ8ODSsPKg4ODg4PDQ8ODg4OKg8ODioPDg4ODg4PDQ8ODQ8ODg8ODg4ODg8qDioPKg4qDw0PKg8NDyoOKg8qDykPKg8NDg8ODg4ODg4PDg4ODg4PDQ8ODg4PDQ8ODg4ODg8NDg8ODg4ODw0ODw4ODg4ODw4ODg4PDQ4PDg4ODg4ODg8ODg8NDw4ODg4ODw0PDg4ODg4ODg8ODg4PDQ8ODQ8ODg8NDw4OKg8qDg4ODg8ODQ8ODg4ODg8ODg4ODg4ODw4ODw0ODw4ODg4PDQ4PDg4OKg8ODioPKg4qDwANBQAAAAAAAAAAAAAAAA=='
      - name: "Bedroom TV"
        command_on: 'JgBGAJWaEzYSOBI3EhUSExEUEhMRFhE4ETkSNxIVERQRFBETEhUSExE5ERMSFRITERMSFBEWEDkRExI4EjoROBI4ETgSNxAADQUAAA=='
        command_off: 'JgCMAJaZEzYSOBI4ERUSFBETEhMRFhE4EjgSNxIVERQSExETEhUSExE5ERMSFRITEhMRFBEWETgSExE4EjoRORE4EjgRNxAABdaWmRE4EjgROBIVERMSFBAUEhUSNxI4EjcSFRITERQRFBEWERMSOBEUERYRExITERQRFRI4EhMRORE6EjcSOBI3EjgQAA0FAAAAAAAAAAAAAAAA'
      - name: "Bedroom Denon"
        command_on: 'JgCIAAcbCTwJGQoZCRkKOwoZCRkKGQkZCTwJPAk8CRoJGQkABZ8JGgk8CRkKGQkZChkJPAk8CTwJOwoZChkJGQk8CTwJAAWfCRoJOwoZCRoJGQk8CRoJGQoZCRkJPAk8CTwJGQoZCQAFnwkaCTwJGQkaCRkJGgk8CTsKOwo7ChkJGQoZCTwJPAkADQU='
        command_off: 'JgDMAAcbCTwJGQoZCRkKGQk8CRkKGQkZCjsJPAo7CRoJGQoABZ4KGQk8CRkKGQkZCjsJGgk8CTwJPAkZCRoJGQk8CTwJAAWfCRoJPAkZChkJGQoZCTwJGQoZCRkJPAk8CTwJGgkZCQAFnwoZCTwJGQoZCRkKOwkaCTwJOwo7ChkJGQoZCTwJPAkABZ8JGgk8CRkJGgkZChkJOwoZCRoJGQk8CTwJPAkZChkJAAWfCRoJOwoZCRoJGQo7CRkKOwo7CjoLGQkZChkJPAk8CQANBQAAAAAAAAAAAAAAAA=='
  - platform: broadlink
    mac: !secret rmmini_b_mac
    switches:
      - name: "Common Room Air Cond"
        command_on: 'JgDoAGVkZZETNhMREzYTEhISEzYSNxISEzYTEhISExETNhM2ExETEhISExISEhMRExISEhMSEhITERMSEhITEhISEhITEhISExETNhMSEhITEhISEhITEhISExETNhMSEhITEhISEhITEhISExISEhISExISEhMRExISEhM2ExETEhISExISEhMRExISEhMSEhISEhMSEhITEhISERMTEhISERMTEhISExISEhMRExISEhMSEhISEhMSEhITERMSEhITEhISExETEhISExISEhMRExISNxISEzYTERM2EzYTEhI2ExISEhMADQU='
        command_off: 'JgDoAGVjZZETNhMSEzYTERMSEjYTNhMSEzUTEhMSEhITERMSEhITERMSExETEhISExETEhISExISEhMRExISEhMRExISEhMSEhITERMSEhITEhISExETEhISExETNhMSEhITEhISEhITEhISExETEhISExISEhMRExISEhM2ExESExMRExISEhMRExISEhMSEhITERMSEhISExISEhISExISExETEhETEhMRExISEhMRExITERMSEhITERMSEhITERMSExETEhISExETEhMRExISEjcSExE3EhMROBE4ERMSNxISETgROBIADQU='
      - name: "Common Room Fan"
        command_on: 'JgDCACkOKQ8MKygPKg4MKw0qDSsMKw0qDSso7CgQKQ4NKioOKA8NKg0rDCsMKw0rDCso7CkPKQ4NKygPKQ4PKA0rDCsMKw0rDCsp7CkOKQ4OKigPKQ4OKgwrDCsNKwwrDiko7SkOKg4OKSgPKg4NKgwrDSsMKw0qDSop7CgQKQ4NKikPKQ4NKg0qDSsNKg8oDiop6ykPKQ4NKigQKQ4NKg0rDSoNKg4qDSop7CgPKQ4NKygPKQ4OKgwrDSoOKg0qDSooAA0FAAAAAAAA'
        command_off: 'JgDCACoNKQ8MKyoNKQ8MKw4pDSoPKQ4pDSoq6yoOKA8MKygPKQ8OKQ8oDykOKQ4pDykq6isNKA8NKioOKA8NKg8pDikOKQ8pDikq6isNKA8OKikOKA8PKA0rDikOKQ8pDikq6yoNKBAOKSoNKBAMKw4pDikPKQ4pDCsq6ygPKQ8MKyoNKQ8MKw4pDykOKQ4pDykq6ioOKA8MKygQKA8MKw4pDykOKQ4pDSsq6ioOKA8NKikPKA8NKg8pDikOKQ8pDikqAA0FAAAAAAAA'
      - name: "Common Room TV"
        command_on: 'JgBYAAABKZIUERMRFBETERMRFBETNhQREzcTNhQ2EzcTNhM3ExEUNhMRFDYTERQREzYUERMRFBETNhQREzYUNhMRFDYTNxM2FAAFLQABKUgUAAxYAAEpSBQADQU='
        command_off: 'JgBYAAABKZIUERMRExEUERMRFBAUNhQREzYUNhM2FDYUNhM2FBETNhQREzYUERMRFDYTERQRExEUNhMRFDYTNhQREzcTNhQ2EwAFLgABKEkTAAxZAAEoSRMADQU='
      - name: "Common Room Android Box"
        command_on: 'JgBYAAABJpYRFBEUERQRFBI4EhMSExITEjkRORE5EjgSExI4EjkRORE5ERQSOBI4EjgSFBE5ERQRFBE5EhMSExITEjkRFBE5EgAFGgABJksSAAxYAAEmTBEADQU='
        command_off: 'JgBYAAABJpUSExIUERQRFBE5ERQSExITEjgSOBI5ETkRFBE5EjgSOBI4EhQRORE5ETkSExI4EhQRFBE5ERQRFBEUEjgSExI4EgAFGgABJkwRAAxYAAEnSxIADQU='
  - platform: broadlink
    mac: !secret rmmini_c_mac
    switches:
      - name: "First Floor Air Cond"
        command_on: 'JgC8AXM4DykPDg8NDw4OKg8ODw0PDQ8ODykPDg8qDykPDg8pDyoPKg8qDykPDg8NDisPDQ8ODw0ODg8ODw0PKg8qDykPKg8NDw4PDQ8ODw0PDQ8ODw0PDQ8ODw0PDg8NDw0PDg8NDw0PDg8NDw4PDQ8NDw4PDQ8NDyoPDg8NDw0PDg8NDw0PAAPPcjgPKg8NDw4PDQ8qDw0PDRANDw0PKg8NDyoPKg8NDyoPKRApDyoPKg8NDw4PKQ8ODw0PDRANDw0PDRANDw0PDg8NDw0PDg8NDw0QDQ8NDw4PDQ8qDw0PDRANDykQKQ8ODw0PDRApDw4PKQ8ODykQDQ8NDw0QDQ8NDw4PDQ8NEA0PDQ8qDykQKRApDw0QKQ8ODykQDQ8NDw0QDQ8NDw4PDQ8NDw4PDQ8NEA0PDQ8NEA0PDQ8ODw0PDRANDw0PDRANDw0PDg8NDw0PDg8NDw0QDQ8NDw4PDQ8NDw4PDQ8NDw4PDQ8NEA0PDQ8ODw0PDQ8ODw0PDQ8ODw0PDg8NDw0PKg8qDw0PDg4ODw0PDg8NDw0PDg8NDw0PDg4ODw4PDQ8NDw4PDQ8NDyoPKg8qDw0PKg8pEAANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgC8AXI5DioODw8NDg4PKg8ODg4ODg4PDioPDg4qECkODw8pDyoPKg4rDioPDg8NDisPDQ8ODg4ODg4PDg4OKw4qDyoOKw4ODw4ODg4PDg4ODg4PDg4ODg4PDg4ODg8ODg4ODw4ODg4ODw4ODg4PDg4ODg8ODg4ODisODg8ODg4ODw4ODg4OAAPQcTkPKg8NDw0QDQ8pEA0PDQ8ODw0PKg8NDyoPKg8NDyoPKRApDyoPKg8NDw0QKQ8ODw0PDRANDw0PDRANDw0PDg8NDw0QDQ8NDw0QDQ8NDw0QDQ8NDw4PDQ8NECkPKg8NDw4PDQ8qDw0PKg8NDyoPDRANDw0PDRANDw0PDRANDw0PDg8pECkPKg8pEA0PKg8NDyoPDQ8ODw0PDQ8ODw0PDRANDw0PDg8NDw0PDg8NDw0QDQ8NDw0QDQ8NDw4PDQ8NEA0PDQ8NEA0PDQ8ODw0PDQ8ODw0PDRANDw0PDg8NDw0PDg8NDw0QDQ8NDw4PDQ8NDw4PDQ8NEA0PDQ8NEA0PKRApDw4PDQ8NEA0PDQ8ODw0PDQ8ODw0PDRANDw0PDg8NDw0PKg8qDw0PKg8qDw0PKg8pEAANBQAAAAAAAAAAAAAAAA=='
  - platform: broadlink
    mac: !secret rmmini_d_mac
    switches:
      - name: "Bedroom2 Air Cond"
        command_on: 'JgBMAaJICT0JGQkaCRkJPQkZCRoJGQkZCT0JGQk9CT0JGQk9CTwJPQk9CTwJGgkZCT0JGQkaCRkJGQkaCRkJPQk8CT0JPQk9CRkJPQk8CRoJGQkZCRoJGQkZCRoJGQkaCBoJGQkaCTwJPQk9CTwJGgkZCRkJGgkAA8WjSAk9CRkJGQkaCTwKGQkZCRoJGQk9CRkJPQk8CRoJPAk9CT0JPAk9CRoJGQk9CRkJGQkaCRkJGQkaCRkJGQkaCRkJPQk9CRkJGQk9CRkJPQk9CTwJGgkZCRoIPQk9CRkJGgk8CRoJGQkZCT0JPQk8CT0JGQkaCRkJGggaCRkJGgkZCRkJGgkZCRkJGgkZCRkJGgkZCT0JPQkZCT0JGQkZCRoJPAk9CT0JGQkZCRoJGQkaCBoJGQkaCTwJGgkZCRkJGgkZCRkJPQk9CRkJPQkZCRoJAA0F'
        command_off: 'JgBMAaNICjwKGAkZCRoJPAoZCRkJGQkaCT0JGQk9CTwKGQk8CjwKPAo7CjwKGQkZCTwKGQoYCRoJGQoYCRoJPAo8CjwKOwo8ChgKPAo8ChgKGQkZCRkJGgkZChgKGQkZCRkJGgkZCT0LOwk8DDoKGAoZCRkJGQkAA8aiSQo7ChkJGQkZCjwKGAoZCRkJGgk8ChkJPAo8ChgKPAo8CjwJPAo8ChgJGgk8ChkJGQkZCRoKGAkZCRoJGQkZCRoJPAo8DBYKGQk9CRkJPQk8DBcKGAkZCRoKOwo8ChgJGgo7ChkJGQkaCTwKPAo8CjsMFwoYCRkJGgoYCRkKGQkZCRoJGQoYCRoJGQoYChkKGAkZCjwKPAsXDDoKGAkaCRkJPQk8CjwKGAkaChgKGAoZChgJGgkZCT0JGQoYCRoKGAk9CjsKGQo7ChkJPAoZCRkJAA0F'
  - platform: template
    switches:
      common_room_haier:
        value_template: '{{ (states("sensor.ganymede_dht11_temperature") | float > 25) and (states("sensor.ganymede_dht11_temperature") | float < 29) }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.common_room_air_cond
        turn_off:
          service: switch.turn_off
          entity_id: switch.common_room_air_cond
      bedroom_daikin:
        value_template: '{{ (states("sensor.hyperion_dht11_temperature") | float > 25) and (states("sensor.hyperion_dht11_temperature") | float < 29) }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.bedroom_air_cond
        turn_off:
          service: switch.turn_off
          entity_id: switch.bedroom_air_cond
      ff_daikin:
        value_template: '{{ (states("sensor.phoebe_am2301_temperature") | float > 25) and (states("sensor.phoebe_am2301_temperature") | float < 29) }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.first_floor_air_cond
        turn_off:
          service: switch.turn_off
          entity_id: switch.first_floor_air_cond
      bedroom2_daikin:
        value_template: '{{ (states("sensor.charon_dht11_temperature") | float > 25) and (states("sensor.charon_dht11_temperature") | float < 29) }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.bedroom2_air_cond
        turn_off:
          service: switch.turn_off
          entity_id: switch.bedroom2_air_cond

automation:

  - alias: "Auto Air-conditioning Powerful Bedroom"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: switch.bedroom_air_cond
        from: 'off'
        to: 'on'
        for:
          minutes: 3
    condition:
      - condition: template
        value_template: '{{ states("sensor.hyperion_dht11_temperature") | float > 30 }}'
    action:
      - service: script.bedroom_ac_control
        data:
          packet: "powerful"

  - alias: "Auto Air-conditioning Powerful First Floor"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: switch.first_floor_air_cond
        from: 'off'
        to: 'on'
        for:
          minutes: 3
    condition:
      - condition: template
        value_template: '{{ states("sensor.phoebe_am2301_temperature") | float > 30 }}'
    action:
      - service: script.first_floor_ac_control
        data:
          packet: "powerful"

script:
  rm_mini_commonroom:
    sequence:
      - service: remote.learn_command
        target:
          entity_id: remote.rm_common_room_remote
        data:
          device: airconditioning
          # alternative: true
          command:
            - haier turn on
            - haier turn off
      - service: remote.learn_command
        target:
          entity_id: remote.rm_common_room_remote
        data:
          device: hometheatre
          # alternative: true
          command:
            - common room tv turn on
            - common room tv turn off
            - common room androidbox turn on
            - common room androidbox turn off
            - common room androidbox ok
            - common room denon turn on
            - common room denon turn off
            - common room denon mute
            - common room denon unmute
  rm_mini_bedroom:
    sequence:
      - service: remote.learn_command
        target:
          entity_id: remote.rm_bedroom_remote
        data:
          device: airconditioning
          # alternative: true
          command:
            - bedroom daikin turn on
            - bedroom daikin turn off
            - bedroom daikin 24
            - bedroom daikin 21
            - bedroom daikin 18
            - bedroom daikin powerful
      - service: remote.learn_command
        target:
          entity_id: remote.rm_bedroom_remote
        data:
          device: hometheatre
          # alternative: true
          command:
            - bedroom denon turn on
            - bedroom denon turn off
            - bedroom denon mute
            - bedroom denon unmute
  rm_mini_firstfloor:
    sequence:
      - service: remote.learn_command
        target:
          entity_id: remote.rm_first_floor_remote
        data:
          device: airconditioning
          # alternative: true
          command:
            - firstfloor daikin turn on
            - firstfloor daikin turn off
            - firstfloor daikin 24
            - firstfloor daikin 21
            - firstfloor daikin 18
            - firstfloor daikin powerful
  rm_mini_bedroom2:
    sequence:
      - service: remote.learn_command
        target:
          entity_id: remote.rm_bedroom2_remote
        data:
          device: airconditioning
          # alternative: true
          command:
            - bedroom2 daikin turn on
            - bedroom2 daikin turn off
            - bedroom2 daikin 24
            - bedroom2 daikin 21
            - bedroom2 daikin 18
