script:
  mute_common_room:
    alias: "Mute Common Room"
    sequence:
      - service: broadlink.send_packet_192_168_1_13
        data:
          packet:
            - 'JgDMAG82Dw0PDg0pDg0OKg0ODikPDA4ODikODg8MDikOKQ4ODwwPDQ4NDg4ODw4MDg0OKQ8NDikODw0ODQ4ODg4oDw0ODQ8pDigQKA4ODSsNDQ4NDg4ODQ8oDygPDQ4qDSkOKQ8ODQAJj283DQ4ODQ4pDw0OKQ8MDygQDA8ODSkODQ8NDikOKQ4NDw0ODQ8ODQ4ODwwODwwOKQ8ODSkODQ8NDg0PDg0pDg4ODQ8oDikPKA8NECcPDA8NDg4PDA4rDCkPDg0qDigOKQ4ODwANBQAAAAAAAAAAAAAAAA=='
  mute_bedroom:
    alias: "Mute Bedroom"
    sequence:
      - service: broadlink.send_packet_192_168_1_14
        data:
          packet:
            - 'JgDMAAgaCjsKGQkZChkJGgkZCRoJGQk8CTwJPAk8CRkKGQkABZ8KGQk8CxcJGgkZCTwKOwo7CTwJGgkZCRoJGQk8CTwKAAWeChkJPAkZChkJGQoZCRkKGQkZCjsKOwo7CjsKGQkZCgAFnwoYCTwLGAkZCRoJPAk7CjsMOQwXCRkKGQkZCjsKOwwABZ0KGAo7CRoJGQkaCRkJGgkZCRoJPAk8CTwJPAkZCRoJAAWfChgKOwoZCRkKGQk8CTwJPAs6CRkKGQkZChkJPAk8CwANBQAAAAAAAAAAAAAAAA=='
  bedroom_ac_24:
    alias: "Bedroom Air Condition 24"
    sequence:
      - service: broadlink.send_packet_192_168_1_14
        data:
          packet:
            - 'JgC8AXA5DyoODg4ODg8NKw4ODg8NDw4ODisODg4rDSsODw0rDisNKw4rDSsPDg0PDioPDg0PDg4ODg4PDQ8OKw0rDyoNKw8NDg8NDw4ODg8NDw4ODg4ODw0PDg4ODw0PDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODisODg4ODg4ODw0PDg4OAAPMcTkPKg0PDg4ODg4rDg4ODg4PDQ8OKw0PDioOKw4ODisNKw4rDioPKg4ODg4OKw4ODg8NDw4ODg4ODw0PDg4ODw0PDg4ODg4PDQ8ODg4ODg8NDw4rDg4ODg4ODisOKg8ODQ8ODg4PDQ8ODg4rDSsPDg0PDQ8ODg4PDQ8ODg4ODg8NDw4rDSsPKg4qDg4OKw4ODisOKg8qDioOKw4ODg8NDw4ODg4ODw0PDg4ODw0PDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODg4ODw0PDg4ODg4PDQ8ODg4PDQ8ODg4ODg8NDw4ODg4ODw0PDg4ODw0PDg4ODg4PDQ8ODg4ODg8NKw4rDg4ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODg4ODw0PDg4OKw4ODg4ODw0rDisOKg4rDgANBQAAAAAAAAAAAAAAAA=='
  bedroom_ac_21:
    alias: "Bedroom Air Condition 21"
    sequence:
      - service: broadlink.send_packet_192_168_1_14
        data:
          packet:
            - 'JgC8AXE5DioPDQ4PDQ8OKw4ODg4ODg4PDSsPDQ4rDyoNDw4qDyoOKg8qDyoODg4ODisODg4ODg8NDw0PDg4OKw4qDisOKw0PDg4ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODg4ODw0PDg4ODw0PDQ8ODg4PDQ8ODg4ODisODg4PDQ8NDw4ODg8NAAPNcDkOKw4ODg4ODw0rDg8NDw0PDg4OKw4ODisOKg8ODSsOKw4qDisOKg4PDQ8OKg4PDQ8ODg4PDQ8NDw4ODg8NDw4ODg4ODw0PDg4ODw0PDQ8ODg4rDg4ODg4PDSsOKw0PDg4ODw0rDw0OKw8NDisODg4ODg8NDw4ODg8NDw0PDg4ODw0rDyoNKw8qDQ8OKw0PDioOKw4rDSsPKg4ODg4ODg4PDQ8ODg4PDQ8ODg4ODg8NDw4ODg4ODw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8NDw4ODg8NDw4ODg4ODw0PDg4ODw0PDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODg4OKw4qDw4NDw4ODg8NDw4ODg4ODw0PDg4ODw0PDQ8ODg4PDQ8OKg4rDg4OKw4ODisNKw8qDgANBQAAAAAAAAAAAAAAAA=='
  bedroom_ac_18:
    alias: "Bedroom Air Condition 18"
    sequence:
      - service: broadlink.send_packet_192_168_1_14
        data:
          packet:
            - 'JgC8AXA5DyoODg4ODg8NKw8ODQ8ODg4ODisODg4rDioPDg0rDisOKg4rDioPDg0PDioPDg0PDg4ODw0PDg4OKw0rDyoNKw8ODQ8ODg4ODg8NDw4ODw4NDw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8NDw4ODg8NDw4ODisNDw4ODg8NDw4ODg4OAAPMcTkPKg0PDg4ODg4rDg4ODw0PDg4OKw4ODioOKw8NDisOKg8qDioOKw4ODg8NKw4ODg8NDw4ODg8NDw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8ODg4rDg4ODg4ODisOKg8ODg4ODg4PDSsODg4PDSsODw0PDg4ODg4PDQ8ODg4PDQ8NDw4rDioPKg4qDw4NKw8NDisOKg4rDyoOKg8NDg8NDw4ODg4ODw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8NDw4ODg8NDw4ODg4ODw0PDg4ODw0PDg4ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODg4ODw0PDg4ODg4PDQ8ODg4PDQ8OKg8qDg4ODg4PDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODg4OKw4ODisNDw4ODisOKg8qDgANBQAAAAAAAAAAAAAAAA=='
  bedroom_ac_powerful:
    alias: "Bedroom Air Condition Powerful"
    sequence:
      - service: script.bedroom_ac_18
      - delay: 00:00:15
      - service: broadlink.send_packet_192_168_1_14
        data:
          packet:
            - 'JgC8AXE5DioPDQ8ODQ8PKg4ODg4PDQ8ODioODg4rDyoODg4qDyoOKg8qDykPDg4ODisNDw4ODg4ODw0PDw0PKg4qDyoOKg8ODQ8PDQ4PDQ8ODg4ODg8ODg4ODw0PDg4ODw0PDg0PDg4ODg8ODQ8ODg4ODg8NDw8NDisODg4ODw4NDw4ODg4OAAPMcTkPKg0PDg4ODg8qDg4ODw4ODg4OKw4ODioPKg8NDisOKg4rDioPKg8NDw4NKw8NDw4ODg4ODw0ODw4ODw0PDg0PDg4PDQ8ODg4ODg8NDw4ODg4rDg4ODg8NDyoOKg4PDg4PDQ8ODg4OKg8ODSsPDQ8ODg4ODg8ODg4ODg4ODg8NDw4qDyoPKg4qDw0OKw8NDisOKg8qDioPKg8NDw0ODw4ODw0PDg0PDg4ODg8ODg4PDQ4ODw4ODg4ODw4ODg4ODg4PDg4ODw0PDQ4PDg4ODg4PDioPDQ4PDg4ODg4PDQ8ODg8NDw4ODg4ODw0ODw4ODg4PDg4ODQ8PDQ4PDg4OKg8qDw0PDg4ODg4PDQ4PDg4ODg4ODw4ODg8NDw4NDw0PDw0PDg4qDw0PKg8NDisOKg4rDgANBQAAAAAAAAAAAAAAAA=='
  bedroom_ac_control:
    alias: "Bedroom Air Condition Control"
    sequence:
      - service_template: '{% if packet == "24" %}script.bedroom_ac_24{% elif packet == "21" %}script.bedroom_ac_21{% elif packet == "18" %}script.bedroom_ac_18{% elif packet == "powerful" %}script.bedroom_ac_powerful{% else %}{% endif %}'

sensor:
  - platform: broadlink
    update_interval: 60
    name: "Common Room"
    host: !secret rmpro_ip
    mac: !secret rmpro_mac
    monitored_conditions:
      - temperature
  - platform: statistics
    entity_id: sensor.common_room_temperature
    name: "Common Room Temperature"

switch:
  - platform: broadlink
    name: "RM Pro"
    host: !secret rmpro_ip
    mac: !secret rmpro_mac
    switches:
      common_room_air_cond:
        friendly_name: "Common Room Air Cond"
        command_on: 'JgCaAAc0AAEnlhQ4FhEUORMSFRIUExURFRIUOBQTFBMTOBUSFBQTExQSFDgUEhY3FBIUExQ4FBIWERQTFDcVOBQSFTcVExM5FBIUEhQTFBIVOBQ3FjcVNhUSFhEVEhQTFDcUExQSFTcWEhMSFRIUExQ4FTcUORU2FhAVOBQ4FTcVNxU3FTcUORM4FDgUOBQTFDgUNxU4FREUERUADQUAAAAAAAAAAAAAAAAAAA=='
        command_off: 'JgCcAAABKJYTOBUSFDkTEhUSFBQTEhQTFREUExURFRMTFBQSFBIVEhQ3FRIVNxUSFBMVNhUSFRMTExQ3FjgTEhQ4FBMUOBUTExIUExQTEzgWNhU4ExQVERQSFRIVEhQ3FhITExU4FBIUEhUSFBIUOBQ4FjYUFBMSFTkTORM4FTcUORM4FDgUOBYRFBMUNxURFjYVEhQTFDYVAAWNCAANBQAAAAAAAAAAAAAAAA=='
      common_room_fan:
        friendly_name: "Common Room Fan"
        command_on: 'JgCSACoPKA8NKSsNKQ4NKQ8pDikOKQ8oDiop6ykOKQ4PKSgPKA8NKQ4pDygPKA8oDykq6ioNKg8NKCoOKQ4OKQ4pDikOKg4oDygq7CgNKg8NKSoOKQ4NKw0pDikOKQ8oECcq6ioNKg4OKSoOKg0NKQ8qDSgPKQ8oECcq6ioOKQ4NKSoOKg4OKBAnECgNKw0pDikqAA0FAAAAAAAA'
        command_off: 'JgDCACoNKw0QKCoMKwwOKQ4pDyoNKg8nDikq6ykNKg0PKSkOKg0OKRAnDygPKQ4pDikr6ioNKQ4OKigNKg4PKQ0pDikPKA8pDygq6ioPKQ0OKCsNKRAMKQ4pDikPKA4pDiop6iwNKA8OKCsNKg0OKBAoDygOKRAoDioo6ioOKQ4OKSoPKQ0NKg0rDCkQKQ4oDikr6SoOKg0OKCsNKw4MKQ4pDikQJw8pDiop6ioOKQ4NKygOKg4OKQ0pDikPKA8oDykpAA0FAAAAAAAA'
        # command_on: 'JgAiASsNKg0NKikOKg0PKBAnDikOKQ8qDigq6ioOKQ0PKigNKg4PKA8oDioOKQ0pDykp6ykOKQ4OKSsMKg0QJw8pDikOKQ4pDiop6ioNKg4RJioNKg0OKw0oDyoNKQ4pDygr6SoNKwwPKSkOKw0NKg0qDigQKA4pDikq6ykOKQ0PKCwMKQ4PKA4pDygQJxAoDiop6ioNKg0OKygNKg4PKA8oDioNKg4oDykp6ioPKQ0OKSoNKg4OKBApDSoOKA8pDigr6SsMKg4OKSoOKQ0OKw0oDykOKQ4pDygq6ioNKw4NKSoNKg0QKA8nDygQKA4pDioq6SoNKg0QJysNKg0PKA4rDSgPKBApDSop6ykNKg0PKSkOKQ4PKA4pDikPKQ4oDykqAA0FAAAAAAAA'
        # command_off: 'JgAiASoOKQ4OKSoNKg0PKQ4pDikOKQ4pDygq6ykNKg0QKCoOKQ0OKw4nDykOKQ4qDSoq6ikOKgwOKSsOKQ0PKBAoDygPKQ0qDSop6ioOKgwOKSoOKwwOKQ4pDikQKA4qDikp6ioNKg4PJyoPKA0QKA4pDioNKQ8oDygr6SoPKQ0QJyoNKg4OKQ8oDikOKQ8pDSoq6ygOKQ8NKSkOKg0OKRAnDykOKQ4qDSoq6SoNKg0PKCoOKQ8NKRApDicPKg0pDikr6SoNKwwOKisLKg4PKA4pDikPKQ4pDikp6yoNKw0NKygNLQoQKA4pDygQJw8pDycq6yoOKA4OKikNKg8MKg8oDioPKQ0oECcq6isNKQ4OKSoNKw0NKQ8oDykPKA4pECcqAA0FAAAAAAAA'
      common_room_tv:
        friendly_name: "Common Room TV"
        command_on: 'JgDEAE0TKBQTEygSFRMnExQUExMoExUTExMVEhQAA0pOEygTFREoExQTKBIVEhUTKBIUExYSFBMUAANITxQmFBQTJxUSFCcVExEVEycUFBIUExUSFQADSE8TKBMUEigUFBIoFRMSFBMoExUSFBMUEhYAA0dREicVEhMpEhQSKBQTExYSJxQTFBQSFBQTAANJTxMnFRMTJxMUEycUFRIVFCUUExQTFBMUFAADSU8SKBMTFSYUExQnExUSFBMnFBMUExUTExMADQUAAAAA'
        command_off: 'JgCMAE4UJxQTEycUFBIpExMTFBMoExUSFRIVEhQAA0lPFCgSFBMnExQUJxQTFBMTKBMTFBMUFBMUAANITxUmFBIVJxIUFCcTFRIUEycUFRIUExMUFAADSU4VJhMUEycVExQmFRITFBMoExMTFRIVEhYAA0hOFCcTFRInFBURKBQTExQUKBMTExYRFBMUAA0FAAAAAAAAAAAAAAAA'
        # command_on: 'JgDEAFERKREVEygSFBMqERUSFBMpERUTFRMTExUAA0lRESoRFRMoExMTKhETExUTKBIVEhUUExQUAANJUREpExMTKBIVEygSFRMUEygSFBQTFRMSFgADSVASKREVEygTExMpExMTFBMpEhQTFBMVEhYAA0hRESkUExQnEhUSKRIUExQTKREUExUTFBMVAANJUBMoEhQTKBIVEygSFBMVEikSFBMUExUSFQADSVESKBIVFCcSFRMoEhQTFRQoEhMTFRIUExYADQUAAAAA'
        # command_off: 'JgDIAAoAB8JSESoSEhMpExQSKRIUFBMTKRIVEhUTFBIVAANJURIoEhQTKhEUEygSFRIVEygSFBUTEhUTFgADSFERKRIUFCcTFBIrEBYRFRIpEhUTExMUExYAA0pPEioQFRMoExQSKRIVExQTKBIVExMTFBMVAANKUREoEhUSKRIUEykSFBMUEygTFBQTFBMTFQADSVATKBIVEikSFRIoEhUUExQnEhUTFREWEhUAA0lQEikTExMpERUTKBIUFRMSKRIUExQTFRIVAA0F'
      common_room_android_box:
        friendly_name: "Common Room Android Box"
        command_on: 'JgBYAAABKJIUERYPFBEUERU1ExIUERMSEzgSNxQ1FTUUERU1FDYTNxM3FBEUNhM4EjYUERQ3ExISEhU1FBETEhMSEzgUEBQ3EgAFEwABJ0sSAAxKAAEpSRMADQU='
        command_off: 'JgBcAAgACe4AASiSFBAUERMSFBEUNhMTEhIUERQ2FDcSNxM2FBEUNhQ2EzcTNxMTFTQTNxM2FBEUNhQSExIUNxESExMTEhQ1ExITNxMABRMAAShKEgAMSgABJ0oTAA0FAAAAAAAAAAAAAAAA'
  - platform: broadlink
    name: "RM Mini"
    host: !secret rmmini_ip
    mac: !secret rmmini_mac
    switches:
      bedroom_air_cond:
        friendly_name: "Bedroom Air Cond"
        command_on: 'JgC8AXI4DioODw4ODg4PKg4ODg4ODg8ODioPDg0rDyoNDw8pDisOKw0rDyoODg4ODyoODg8NDw4ODg4ODg4OKw8pDyoPKg0PDg4ODg4PDg4PDQ4PDQ8ODg4ODg8NDw4ODw0PDg4ODg4ODw0PDg4PDQ8ODg4ODg8NDyoPDQ8ODQ8ODg4ODg8NAAPNcDkPKg4ODg4PDg4qDw4NDw4ODw0OKw4ODisOKg4PDioPKg4qDyoOKg8ODg4OKg4PDQ8ODg8ODg4ODg4ODg8ODg4ODw0ODw4ODw0PDg0PDg4ODg4rDg4PDQ4PDSsPKg4ODg4PDg4ODg4PKg4ODisODg4ODg4ODw4ODg4PDg4ODg4PDQ4rDioPKg8pDg8NKw4PDioPKg4qDyoOKg4PDQ8ODg4ODg8NDw4ODw4NDw4ODw0ODw4ODg4ODg4PDg4PDQ8ODg4ODg8NDg8NDw4ODg4ODw0PDw0PDg4ODg4PDQ8ODg4PDQ8ODg4ODg4ODw4NDw4ODg4PDg4ODg4PDg0PDg4PKg4qDw0PDg4ODw0ODw0PDg4PDQ4PDg4ODg4ODw4NDw8NDg8OKg8NDw4NKw4ODisPKg4qDwANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgC8AXE5DioPDg0PDg4PKg4ODg4ODw4ODioPDg0rDyoODg4rDioPKg4qDyoODg8NDisPDQ4ODg8NDw4ODw4NKw4rDioPKg4ODg4ODw0PDg4ODg4PDg4ODg8ODQ8ODg4ODg8ODg4ODg4PDg0PDw0ODxAMDg4ODg8ODSsPDQ4PDQ8ODg4PDQ8OAAPMcTkOKg8NDg8ODg4qDg8NDw4ODw4NKw8NDisOKg8ODSsPKg4qDyoPKQ8ODg4OKw4ODg4ODg4PDg4ODg8ODQ8ODg4ODg8NDw4ODg4PDg4ODg4ODw0PDg4ODg4PDSsOKw4OEAwODw0PDg4OKw4ODioPDg4ODg4ODw0PDg4ODg4PDQ8ODg4rDioPKg4qDw4NKw8ODioPKg4qDyoOKg8ODQ8ODg4ODg8NDw4ODg4ODw0PDg4RDA4ODg4ODg4PDQ8ODg4ODg8NDw4ODg8NDw4ODg4ODw0PDg4ODw4ODg4ODg4PDQ8ODg8NDg8NDw4ODg8NDw4ODg4PDg4ODg4ODg4PDg4OKw0rDw0ODw0PDg4ODg4PDQ8ODg8ODg4ODg4ODg8NDw4ODw0ODw0PDw0OKw4ODisOKg8qDgANBQAAAAAAAAAAAAAAAA=='
      bedroom_tv:
        friendly_name: "Bedroom TV"
        command_on: 'JgBGAJWaEzYSOBI3EhUSExEUEhMRFhE4ETkSNxIVERQRFBETEhUSExE5ERMSFRITERMSFBEWEDkRExI4EjoROBI4ETgSNxAADQUAAA=='
        command_off: 'JgCMAJaZEzYSOBI4ERUSFBETEhMRFhE4EjgSNxIVERQSExETEhUSExE5ERMSFRITEhMRFBEWETgSExE4EjoRORE4EjgRNxAABdaWmRE4EjgROBIVERMSFBAUEhUSNxI4EjcSFRITERQRFBEWERMSOBEUERYRExITERQRFRI4EhMRORE6EjcSOBI3EjgQAA0FAAAAAAAAAAAAAAAA'
      bedroom_denon:
        friendly_name: "Bedroom Denon"
        command_on: 'JgCIAAcbCTwJGQoZCRkKOwoZCRkKGQkZCTwJPAk8CRoJGQkABZ8JGgk8CRkKGQkZChkJPAk8CTwJOwoZChkJGQk8CTwJAAWfCRoJOwoZCRoJGQk8CRoJGQoZCRkJPAk8CTwJGQoZCQAFnwkaCTwJGQkaCRkJGgk8CTsKOwo7ChkJGQoZCTwJPAkADQU='
        command_off: 'JgDMAAcbCTwJGQoZCRkKGQk8CRkKGQkZCjsJPAo7CRoJGQoABZ4KGQk8CRkKGQkZCjsJGgk8CTwJPAkZCRoJGQk8CTwJAAWfCRoJPAkZChkJGQoZCTwJGQoZCRkJPAk8CTwJGgkZCQAFnwoZCTwJGQoZCRkKOwkaCTwJOwo7ChkJGQoZCTwJPAkABZ8JGgk8CRkJGgkZChkJOwoZCRoJGQk8CTwJPAkZChkJAAWfCRoJOwoZCRoJGQo7CRkKOwo7CjoLGQkZChkJPAk8CQANBQAAAAAAAAAAAAAAAA=='
