sensor:

  - platform: moon

  - platform: time_date
    name: Date & Time
    display_options:
      - 'time'
      - 'date'

  - platform: template
    sensors:
      day_night:
        friendly_name: "Day/Night"
        icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
        value_template: '{% if is_state("sun.sun", "above_horizon") %}Day{% else %}Night{% endif %}'
      solar_angle:
        friendly_name: 'Sun Angle'
        icon_template: mdi:weather-sunset
        value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
        unit_of_measurement: '°'


group:
  daylight:
    view: no
    name: "Daylight"
    icon: mdi:weather-sunny
    entities:
      - sensor.date
      - sensor.time
      - sensor.day_night
      - sun.sun
      - sensor.solar_angle
      - sensor.moon

automation:

  - alias: "Sunset 1"
    initial_state: true
    hide_entity: true
    trigger:
      - platform: sun
        event: sunset
        offset: "-02:00:00"
    action:
      - service: script.flashing_once
        data:
          title: "Sunset in 2 hours"
          message: 'Sunset is expected in two hours [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Sunset 2"
    initial_state: true
    hide_entity: true
    trigger:
      - platform: sun
        event: sunset
        offset: "-01:00:00"
    action:
      - service: script.flashing_once
        data:
          title: "Sunset in 1 hour"
          message: 'Sunset is expected in one hour [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Sunset 3"
    initial_state: true
    hide_entity: true
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    action:
      - service: script.flashing_once
        data:
          title: "Sunset in 30 minutes"
          message: 'Sunset is expected in 30 minutes [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Sunset 4"
    initial_state: true
    hide_entity: true
    trigger:
      - platform: sun
        event: sunset
        offset: "+00:00:00"
    action:
      - service: script.flashing_short
        data:
          title: "The sun is down now"
          message: 'Sunset is happening now, another goodbye to the day [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
