sensor:
  - platform: moon
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: template
    sensors:
      solar_angle:
        friendly_name: 'Sun Angle'
        icon_template: mdi:weather-sunset
        # value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        unit_of_measurement: 'degrees'
        # unit_of_measurement: '°'
      sunrise:
        friendly_name: 'Sun Rise'
        # value_template: "{{ states.sun.sun.attributes.next_rising }}"
        value_template: "{{ state_attr('sun.sun', 'next_rising') }}"

automation:

  - alias: "Sunset 1"
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on") }}'
    action:
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          line: "true"
          speak: "true"
          audio: "chime"
          light: "false"
          mobile: "false"
          message: "Sunset is expected in 30 minutes"

  - alias: "Sunset 2"
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: "+00:00:00"
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on") }}'
    action:
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          line: "true"
          speak: "true"
          audio: "chime"
          light: "false"
          mobile: "false"
          message: "Sun is setting now"
