sensor:

  - platform: moon

  - platform: time_date
    name: Date & Time
    display_options:
      - 'time'
      - 'date'

  - platform: template
    sensors:
      day_night:
        friendly_name: "Day/Night"
        icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
        value_template: '{% if is_state("sun.sun", "above_horizon") %}Day{% else %}Night{% endif %}'
      solar_angle:
        friendly_name: 'Sun Angle'
        icon_template: mdi:weather-sunset
        value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
        unit_of_measurement: '°'

automation:

  - alias: "Sunset 1"
    trigger:
      - platform: sun
        event: sunset
        offset: "-01:00:00"
    action:
      - service: script.flashing_once
        data:
          title: "Sunset is expected in 1 hour"
          message: 'Sunset is expected in 1 hour [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Sunset 2"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    action:
      - service: script.flashing_once
        data:
          title: "Sunset is expected in 30 minutes"
          message: 'Sunset is expected in 30 minutes [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Sunset 3"
    trigger:
      - platform: sun
        event: sunset
        offset: "+00:00:00"
    action:
      - service: script.flashing_short
        data:
          title: "Sun is setting now"
          message: 'Sun is setting now [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
