sensor:
  - platform: moon
  - platform: time_date
    name: Date & Time
    display_options:
      - 'time'
      - 'date'
  - platform: template
    sensors:
      solar_angle:
        friendly_name: 'Sun Angle'
        icon_template: mdi:weather-sunset
        value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
        unit_of_measurement: '°'

automation:

  - alias: "Sunset 1"
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    action:
      - service: script.notifying
        data:
          email: "false"
          tv: "true"
          speak: "true"
          audio: "pip"
          light: "false"
          mobile: "false"
          title: "Sunset is expected in 30 minutes"
          message: 'Sunset is expected in 30 minutes [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Sunset 2"
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: "+00:00:00"
    action:
      - service: script.notifying
        data:
          email: "false"
          tv: "true"
          speak: "true"
          audio: "pip"
          light: "false"
          mobile: "false"
          title: "Sun is setting now"
          message: 'Sun is setting now [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
