sensor:
  - platform: moon
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: template
    sensors:
      solar_angle:
        friendly_name: 'Sun Angle'
        icon_template: mdi:weather-sunset
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        unit_of_measurement: 'degrees'
      sunrise:
        friendly_name: 'Sun Rise'
        value_template: "{{ state_attr('sun.sun', 'next_rising') }}"

group:
  daylight:
    name: "Daylight"
    icon: mdi:weather-sunny
    control: "hidden"
    view: false
    entities:
      - sensor.date
      - sensor.time
      - sun.sun
      - sensor.solar_angle
      - sensor.moon

automation:

  - alias: "Sunset 1"
    # initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on") }}'
    action:
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          line: "true"
          speak: "true"
          audio: "chime"
          light: "false"
          mobile: "false"
          message: "Sunset is expected in 30 minutes"

  - alias: "Sunset 2"
    # initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: "+00:00:00"
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on") }}'
    action:
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          line: "true"
          speak: "true"
          audio: "chime"
          light: "false"
          mobile: "false"
          message: "Sun is setting now"
