sensor:
  - platform: moon
  - platform: time_date
    name: Date & Time
    display_options:
      - 'time'
      - 'date'
  - platform: template
    sensors:
      solar_angle:
        friendly_name: 'Sun Angle'
        icon_template: mdi:weather-sunset
        value_template: '{{ "%+.1f"|format(states.sun.sun.attributes.elevation) }}'
        unit_of_measurement: '°'
      sunrise:
        value_template: "{{ states.sun.sun.attributes.next_rising }}"

automation:

  - alias: "Sunset 1"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on") }}'
    action:
      - service: script.notifying
        data_template:
          email: '{% if is_state("input_boolean.presence_pe", "off") %}true{% else %}false{% endif %}'
          tv: '{% if is_state("binary_sensor.android_box", "on") %}true{% else %}false{% endif %}'
          line: '{% if is_state("input_boolean.presence_pe", "off") %}pe{% else %}false{% endif %}'
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          message: "Sunset is expected in 30 minutes"

  - alias: "Sunset 2"
    trigger:
      - platform: sun
        event: sunset
        offset: "+00:00:00"
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on") }}'
    action:
      - service: script.notifying
        data_template:
          email: '{% if is_state("input_boolean.presence_pe", "off") %}true{% else %}false{% endif %}'
          tv: '{% if is_state("binary_sensor.android_box", "on") %}true{% else %}false{% endif %}'
          line: '{% if is_state("input_boolean.presence_pe", "off") %}pe{% else %}false{% endif %}'
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          message: "Sun is setting now"
