# input_slider:
#   volume_common_room:
#     name: Volume Common Room
#     initial: 0.35
#     min: 0.0
#     max: 0.5
#     step: 0.05
#     icon: mdi:volume-high
#   volume_bedroom:
#     name: Volume Bedroom
#     initial: 0.25
#     min: 0.0
#     max: 0.5
#     step: 0.05
#     icon: mdi:volume-high

switch:
  - platform: template
    switches:
      androidtv:
        value_template: "{{ is_state('switch.titan', 'on') and states.sensor.titan_current_consumption.state.split(' ')[0] | float > 150 }}"
        turn_on:
          service: script.turnon_tv_androidbox
        turn_off:
          service: script.turnoff_tv_androidbox
      bedroomsound:
        value_template: "{{ is_state('switch.europa', 'on') and states.sensor.europa_current_consumption.state.split(' ')[0] | float > 40 }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.bedroom_denon
        turn_off:
          service: switch.turn_off
          entity_id: switch.bedroom_denon

sensor:
  - platform: template
    sensors:
      denon_source:
        # value_template: '{% if states.media_player.denon %}{{ states.media_player.denon.attributes["source"] }}{% else %}Off{% endif %}'
        # value_template: '{% if states.media_player.denon.state == "off" %}Off{% else %}{{ states.media_player.denon.attributes["source"] }}{% endif %}'
        value_template: '{% if states.media_player.denon.attributes["source"] %}{{ states.media_player.denon.attributes["source"] }}{% else %}Off{% endif %}'
        # friendly_name: 'Denon Source'

shell_command:
  # d_deviceinfo: '/bin/curl -X GET http://192.168.1.66/goform/Deviceinfo.xml'
  # d_mainzone: '/bin/curl -X GET http://192.168.1.66/goform/formMainZone_MainZoneXml.xml'
  # d_mainzone_status: '/bin/curl -X GET http://192.168.1.66/goform/formMainZone_MainZoneXmlStatus.xml'
  # d_mainzone_statuslite: '/bin/curl -X GET http://192.168.1.66/goform/formMainZone_MainZoneXmlStatusLite.xml'
  # d_zone2_status: '/bin/curl -X GET http://192.168.1.66/goform/formZone2_Zone2XmlStatus.xml'
  # d_zone2_statuslite: '/bin/curl -X GET http://192.168.1.66/goform/formZone2_Zone2XmlStatusLite.xml'
  d_power_on: '/bin/curl -k http://192.168.1.66/goform/formiPhoneAppVolume.xml?PWON'
  d_power_off: '/bin/curl -k http://192.168.1.66/goform/formiPhoneAppVolume.xml?PWSTADBY'
  d_volume_40: '/bin/curl -k http://192.168.1.66/goform/formiPhoneAppVolume.xml?MV40'
  d_volume_50: '/bin/curl -k http://192.168.1.66/goform/formiPhoneAppVolume.xml?MV30'
  d_mute_on: '/bin/curl -k http://192.168.1.66/goform/formiPhoneAppVolume.xml?MUON'
  d_mute_off: '/bin/curl -k http://192.168.1.66/goform/formiPhoneAppVolume.xml?MUOFF'
  d_source_dune: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?SIBD'
  d_source_appletv: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?SIMPLAY'
  d_source_satcbl: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?SISAT/CBL'
  d_source_music: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?SICD'
  d_source_usbipod: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?SIUSB/IPOD'
  d_source_mediaserver: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?SISERVER'
  d_source_mode_auto: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?SDAUTO'
  d_source_mode_analog: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?SDANALOG'

script:
  turnon_tv_androidbox:
    alias: "Turn on TV and Android Box"
    sequence:
      - service: switch.turn_on
        entity_id: switch.common_room_tv
      - service: switch.turn_on
        entity_id: switch.common_room_android_box
  turnoff_tv_androidbox:
    alias: "Turn off TV and Android Box"
    sequence:
      - service: switch.turn_off
        entity_id: switch.common_room_android_box
      - service: switch.turn_off
        entity_id: switch.common_room_tv
  xdjrx_turnon:
    alias: "XDJ-RX is on entering DJ mode"
    sequence:
      - service: switch.turn_on
        entity_id: switch.common_room_subwoofer
      - delay: 00:00:01
      - service: shell_command.d_source_music
      # - service: media_player.select_source
      #   data:
      #     entity_id: media_player.denon
      #     source: 'Music'
      - delay: 00:00:02
      - service: shell_command.d_source_mode_analog
      - delay: 00:00:02
      - service: media_player.volume_set
        data:
          entity_id: media_player.denon
          volume_level: 0.4
      - delay: 00:00:02
      - service: script.notifying
        data_template:
          title: '{{ title }}'
          message: '{{ message }}'
  xdjrx_turnoff:
    alias: "XDJ-RX is off exiting DJ mode"
    sequence:
      - service: switch.turn_off
        entity_id: switch.common_room_subwoofer
      - delay: 00:00:01
      - service: media_player.volume_set
        data:
          entity_id: media_player.denon
          volume_level: 0.3
      - delay: 00:00:02
      - service: shell_command.d_source_satcbl
      # - service: media_player.select_source
      #   data:
      #     entity_id: media_player.denon
      #     source: 'SAT/CBL'
      - delay: 00:00:02
      - service: shell_command.d_source_mode_auto
      - delay: 00:00:02
      - service: script.notifying
        data_template:
          title: '{{ title }}'
          message: '{{ message }}'

automation:

  - alias: "Auto Double Subwoofer On"
    trigger:
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "Music") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "MPLAY") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "BD") %}true{% else %}{% endif %}'
    condition:
      - condition: and
        conditions:
          - condition: template
            value_template: '{% if is_state("switch.titan", "on") %}true{% else %}{% endif %}'
          - condition: template
            value_template: '{% if is_state("media_player.denon", "on") %}true{% else %}{% endif %}'
    action:
      - service: switch.turn_on
        entity_id: switch.common_room_subwoofer

  - alias: "Auto Double Subwoofer Off"
    trigger:
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "SAT/CBL") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "NET") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "DVD") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "Game") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "AUX1") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "USB/IPOD") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "TUNER") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "TV") %}true{% else %}{% endif %}'
      - platform: template
        value_template: '{% if is_state("sensor.denon_source", "Internet Radio") %}true{% else %}{% endif %}'
      - platform: state
        entity_id: switch.titan
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: media_player.denon
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.common_room_subwoofer

  - alias: "Turn on XDJ-RX"
    trigger:
      - platform: state
        entity_id: binary_sensor.xdjrx
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: device_tracker.xdj_rx
        from: 'not_home'
        to: 'home'
    condition:
      - condition: template
        value_template: '{% if not is_state_attr("media_player.denon", "source", "Music") %}true{% else %}{% endif %}'
    action:
      - service: script.xdjrx_turnon
        data:
          title: "XDJ-RX is on, entering DJ mode"
          message: 'XDJ-RX is on, entering DJ mode [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Turn off XDJ-RX"
    trigger:
      - platform: state
        entity_id: binary_sensor.xdjrx
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: device_tracker.xdj_rx
        from: 'home'
        to: 'not_home'
    condition:
      - condition: template
        value_template: '{% if is_state_attr("media_player.denon", "source", "Music") %}true{% else %}{% endif %}'
    action:
      - service: script.xdjrx_turnoff
        data:
          title: "XDJ-RX is off, exiting DJ mode"
          message: 'XDJ-RX is off, exiting DJ mode [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  # - alias: "Change AVR Source"
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.denon_source
  #   # condition:
  #   #   - condition: template
  #   #     value_template: '{{ trigger.to_state.attributes.volume_level != trigger.from_state.attributes.volume_level }}'
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.avrmode
  #         value: '{{ states.media_player.denon.attributes["source"] }}'

  - alias: "Denon Source Cable TV"
    initial_state: 'off'
    # hide_entity: True
    trigger:
      - platform: template
        value_template: '{% if is_state_attr("media_player.denon", "source", "SAT/CBL") %}true{% else %}{% endif %}'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{% if is_state("input_boolean.presence_pe", "on") %}true{% else %}{% endif %}'
        - condition: template
          value_template: '{% if is_state("input_select.homemode", "Home") %}true{% else %}{% endif %}'
        - condition: or
          conditions:
            - condition: state
              entity_id: sun.sun
              state: 'below_horizon'
            - condition: time
              after: '18:00:00'
              before: '06:00:00'
    action:
      - service: light.turn_on
        entity_id: light.hallway
        data:
          transition: 5
          brightness: 88
          xy_color: [0.3581,0.2871]

  - alias: "Denon Source Music"
    initial_state: 'off'
    # hide_entity: True
    trigger:
      - platform: template
        value_template: '{% if is_state_attr("media_player.denon", "source", "Music") %}true{% else %}{% endif %}'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{% if is_state("input_boolean.presence_pe", "on") %}true{% else %}{% endif %}'
        - condition: template
          value_template: '{% if is_state("input_select.homemode", "Home") %}true{% else %}{% endif %}'
        - condition: or
          conditions:
            - condition: state
              entity_id: sun.sun
              state: 'below_horizon'
            - condition: time
              after: '18:00:00'
              before: '06:00:00'
    action:
      - service: light.turn_on
        entity_id: light.hallway
        data:
          transition: 5
          brightness: 88
          xy_color: [0.3944,0.2952]

  - alias: "Lights Dune Pauses/Stops"
    trigger:
      - platform: state
        entity_id: media_player.dune
        from: 'playing'
        to: 'idle'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{% if is_state("input_boolean.presence_pe", "on") %}true{% else %}{% endif %}'
        - condition: template
          value_template: '{% if is_state("input_select.homemode", "Home") %}true{% else %}{% endif %}'
        - condition: or
          conditions:
            - condition: state
              entity_id: sun.sun
              state: 'below_horizon'
            - condition: time
              after: '18:00:00'
              before: '06:00:00'
    action:
      - service: scene.turn_on
        entity_id: scene.common_room_alive

  - alias: "Lights Dune Plays"
    trigger:
      - platform: state
        entity_id: media_player.dune
        from: 'idle'
        to: 'playing'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{% if is_state("input_boolean.presence_pe", "on") %}true{% else %}{% endif %}'
        - condition: template
          value_template: '{% if is_state("input_select.homemode", "Home") %}true{% else %}{% endif %}'
        - condition: or
          conditions:
            - condition: state
              entity_id: sun.sun
              state: 'below_horizon'
            - condition: time
              after: '18:00:00'
              before: '06:00:00'
    action:
        service: scene.turn_on
        entity_id: scene.common_room_dim

  # - alias: Volume Common Room
  #   trigger:
  #     - platform: state
  #       entity_id: media_player.denon
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.volume_common_room
  #         value: '{{ trigger.to_state.attributes.volume_level }}'

  # - alias: Volume Adjust Common Room
  #   trigger:
  #     - platform: state
  #       entity_id: input_slider.volume_common_room
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: media_player.volume_set
  #       data_template:
  #         entity_id: media_player.denon
  #         volume_level: "{{ states('input_slider.volume_common_room') }}"

  # - alias: Volume Bedroom
  #   trigger:
  #     - platform: state
  #       entity_id: media_player.itunes
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.itunes', 'volume_level', states('input_slider.volume_bedroom')) }}"
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.volume_bedroom
  #         value: '{{ trigger.to_state.attributes.volume_level }}'

  # - alias: Volume Adjust Bedroom
  #   trigger:
  #     - platform: state
  #       entity_id: input_slider.volume_bedroom
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: media_player.volume_set
  #       data_template:
  #         entity_id: media_player.itunes
  #         volume_level: "{{ states('input_slider.volume_bedroom') }}"
