switch:

  - platform: denonxml
    host: 192.168.1.66
    port: 1
    scan_interval: 5

  - platform: denonxml
    host: 192.168.1.66
    port: 2
    scan_interval: 5


shell_command:

  set_denon_volume: '/bin/curl -k http://192.168.1.66/goform/formiPhoneAppVolume.xml?{{ zone }}+{{ volume | float - 80 }}'
  set_denon_source: '/bin/curl -X GET http://192.168.1.66/goform/formiPhoneAppDirect.xml?{{ source }}'


group:

  denon:
    name: Denon AVR
    entities:
      - switch.denon_zone1
      - switch.denon_zone2


homeassistant:

  customize:
    switch.denon_zone1:
      friendly_name: Common Room
      icon: mdi:video
      custom_ui_state_card: custom_source
    switch.denon_zone2:
      friendly_name: Zone2
      icon: mdi:volume-high
      custom_ui_state_card: custom_source
