mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret my_password
  client_id: home-assistant
  keepalive: 60
  protocol: 3.1
  #tls_insecure: True
  #tls_version: 1.2
  discovery: true
  discovery_prefix: homeassistant

ifttt:
  key: !secret ifttt_key

switch:
  - platform: mqtt
    state_topic: "homeassistant/killhass"
    command_topic: "homeassistant/killhass"
    name: "KillHass"
    qos: 0
    payload_on: "ON"
    payload_of: "OFF"
    optimistic: false

script:
  restart_hass:
    alias: "Restart hass if Hue is not found for 15 minutes"
    sequence:
      - delay:
          minutes: 15
      - service: script.notify_pesiphone6
        data:
          title: "Philips Hue is not found, restarting hass"
          message: 'Philips Hue is not found, restarting hass [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.flashing_once
        data:
          title: "Philips Hue is not found, restarting hass"
          message: 'Philips Hue is not found, restarting hass [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: switch.turn_on
        data:
          entity_id: switch.killhass

automation:

  - alias: "Restart hass if Hue is not found for 15 minutes"
    trigger:
      - platform: state
        entity_id: binary_sensor.moon
        from: 'on'
        to: 'off'
    condition:
      # - condition: template
      #   value_template: '{% if states.switch.titan %}false{% else %}true{% endif %}'
      - condition: state
        entity_id: script.restart_hass
        state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: script.restart_hass

  - alias: 'Stop hass from running'
    trigger:
      - platform: state
        entity_id: switch.killhass
        to: 'on'
    action:
      - service: homeassistant.stop

  - alias: 'Stop restarting hass is Hue is found'
    trigger:
      - platform: template
        # value_template: '{% if states.binary_sensor.moon %}true{% else %}false{% endif %}'
        value_template: '{% if is_state("binary_sensor.moon", "on") %}true{% else %}false{% endif %}'
    condition:
      - condition: state
        entity_id: script.restart_hass
        state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: script.restart_hass
