input_select:
  homemode:
    name: "Home Mode"
    options:
     - Home
     - Away
     - Vacation # alarm clock off
     - Visitor # no autolight off
    initial: Home
    icon: mdi:home-outline

# input_slider:
#   volume_common_room:
#     name: Volume Common Room
#     initial: 0.35
#     min: 0.0
#     max: 0.5
#     step: 0.05
#     icon: mdi:volume-high
#   volume_bedroom:
#     name: Volume Bedroom
#     initial: 0.25
#     min: 0.0
#     max: 0.5
#     step: 0.05
#     icon: mdi:volume-high

automation:

  - alias: "Set Home Mode"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'off'
        to: 'on'
        for:
          minutes: 10
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'off'
        to: 'on'
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Home
      - service: script.notifying
        data:
          title: "Home Mode is now active"
          message: 'Home Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 1"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'on'
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: input_boolean.presence_jue
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Away
      - service: notify.notifying
        data:
          title: "Away Mode #1 is now active"
          message: 'Away Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 2"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'on'
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: input_boolean.presence_pe
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Away
      - service: notify.notifying
        data:
          title: "Away Mode #2 is now active"
          message: 'Away Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 1"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'on'
        to: 'off'
        for:
          hours: 20
    condition:
      - condition: state
        entity_id: input_boolean.presence_jue
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Vacation
      - service: notify.notifying
        data:
          title: "Vacation Mode #1 is now active"
          message: 'Vacation Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 2"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'on'
        to: 'off'
        for:
          hours: 20
    condition:
      - condition: state
        entity_id: input_boolean.presence_pe
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Vacation
      - service: notify.notifying
        data:
          title: "Vacation Mode #2 is now active"
          message: 'Vacation Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight All Off 1"
    hide_entity: True
    trigger:
      - platform: time
        at: '00:01:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: light.turn_off
        entity_id: group.all_lights
      - service: script.flashing_once
        data:
          title: "All lights has been turned off"
          message: 'All lights are off after midnight everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight All Off 2"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_select.homemode
        to: Away
      - platform: state
        entity_id: input_select.homemode
        to: Vacation
    action:
      - service: light.turn_off
        entity_id: group.all_lights
      - service: script.notifying
        data:
          title: "All lights has been turned off"
          message: 'All lights are off when noboby is home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Sunset Home A"
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:15:00"
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: light.turn_on
        entity_id: light.lightstrip
        data:
          transition: 5
          brightness: 200
          xy_color: [0.1794, 0.0964]
      - service: script.flashing_once
        data:
          title: "Lightstrip has been turned on"
          message: '15 minutes before sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Sunset Home B"
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: "+01:00:00"
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: light.turn_off
        entity_id: light.lightstrip
      - service: script.flashing_once
        data:
          title: "Lightstrip has been turned off"
          message: '1.5 hours after sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Sunset Away A"
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:15:00"
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_on
        entity_id: light.garage
        data:
          transition: 5
          brightness: 255
      - service: script.notifying
        data:
          title: "Garage light has been turned on"
          message: '15 minutes before sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Sunset Away B"
    hide_entity: True
    trigger:
      - platform: sun
        event: sunset
        offset: "+01:00:00"
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_off
        entity_id: light.garage
      - service: script.notifying
        data:
          title: "Garage light has been turned off"
          message: '1.5 hours after sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Home 1A"
    hide_entity: True
    trigger:
      - platform: time
        at: '19:30:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: light.turn_on
        entity_id: light.front_1
        data:
          transition: 5
          brightness: 200
      - service: script.flashing_once
        data:
          title: "Downstairs Light has been turned on"
          message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Home 1B"
    hide_entity: True
    trigger:
      - platform: time
        at: '20:00:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: light.turn_off
        entity_id: light.front_1
      - service: script.flashing_once
        data:
          title: "Downstairs Light has been turned off"
          message: 'At 20:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Home 2A"
    hide_entity: True
    trigger:
      - platform: time
        at: '21:30:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lw
        data:
          transition: 5
          brightness: 100
      - service: script.flashing_once
        data:
          title: "Bedroom LW has been turned on"
          message: 'At 21:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Home 2B"
    hide_entity: True
    trigger:
      - platform: time
        at: '23:15:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: light.turn_off
        entity_id: light.bedroom_lw
      - service: script.flashing_once
        data:
          title: "Bedroom LW has been turned off"
          message: 'At 23:15pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Away 1A"
    hide_entity: True
    trigger:
      - platform: time
        at: '19:30:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_on
        entity_id: light.garage
        data:
          transition: 1
          brightness: 255
      - service: script.notifying
        data:
          title: "Garage Light has been turned on"
          message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Away 1B"
    hide_entity: True
    trigger:
      - platform: time
        at: '20:15:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_off
        entity_id: light.garage
      - service: script.notifying
        data:
          title: "Garage Light has been turned off"
          message: 'At 20:15pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Away 2A"
    hide_entity: True
    trigger:
      - platform: time
        at: '20:00:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_on
        entity_id: light.front_2
        data:
          transition: 1
          brightness: 255
      - service: script.notifying
        data:
          title: "Downstairs Light has been turned on"
          message: 'At 20:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Away 2B"
    hide_entity: True
    trigger:
      - platform: time
        at: '20:45:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_off
        entity_id: light.front_2
      - service: script.notifying
        data:
          title: "Downstairs Light has been turned off"
          message: 'At 20:45pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Away 3A"
    hide_entity: True
    trigger:
      - platform: time
        at: '21:30:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lw
        data:
          transition: 1
          brightness: 255
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned on"
          message: 'At 21:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Away 3B"
    hide_entity: True
    trigger:
      - platform: time
        at: '22:00:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_off
        entity_id: light.bedroom_lw
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned off"
          message: 'At 22:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Away 4A"
    hide_entity: True
    trigger:
      - platform: time
        at: '22:40:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lw
        data:
          transition: 1
          brightness: 255
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned on"
          message: 'At 22:40pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Away 4B"
    hide_entity: True
    trigger:
      - platform: time
        at: '23:10:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: light.turn_off
        entity_id: light.bedroom_lw
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned off"
          message: 'At 23:10pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Vacation 1A"
    hide_entity: True
    trigger:
      - platform: time
        at: '19:30:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: light.turn_on
        entity_id: light.garage
        data:
          transition: 1
          brightness: 255
      - service: script.notifying
        data:
          title: "Garage Light has been turned on"
          message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Vacation 1B"
    hide_entity: True
    trigger:
      - platform: time
        at: '20:00:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: light.turn_off
        entity_id: light.garage
      - service: script.notifying
        data:
          title: "Garage Light has been turned off"
          message: 'At 20:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Vacation 2A"
    hide_entity: True
    trigger:
      - platform: time
        at: '20:15:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: light.turn_on
        entity_id: light.front_2
        data:
          transition: 1
          brightness: 255
      - service: script.notifying
        data:
          title: "Downstairs Light has been turned on"
          message: 'At 20:15pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Vacation 2B"
    hide_entity: True
    trigger:
      - platform: time
        at: '20:55:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: light.turn_off
        entity_id: light.front_2
      - service: script.notifying
        data:
          title: "Downstairs Light has been turned off"
          message: 'At 20:55pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Vacation 3A"
    hide_entity: True
    trigger:
      - platform: time
        at: '21:15:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: light.turn_on
        entity_id: light.common_room_1
        data:
          transition: 1
          brightness: 255
      - service: script.notifying
        data:
          title: "Common Room 1 has been turned on"
          message: 'At 21:15pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Vacation 3B"
    hide_entity: True
    trigger:
      - platform: time
        at: '21:45:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: light.turn_off
        entity_id: light.common_room_1
      - service: script.notifying
        data:
          title: "Common Room 1 has been turned off"
          message: 'At 21:45pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Vacation 4A"
    hide_entity: True
    trigger:
      - platform: time
        at: '22:00:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lw
        data:
          transition: 1
          brightness: 255
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned on"
          message: 'At 22:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Vacation 4B"
    hide_entity: True
    trigger:
      - platform: time
        at: '22:30:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: light.turn_off
        entity_id: light.bedroom_lw
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned off"
          message: 'At 22:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  # - alias: Volume Common Room
  #   trigger:
  #     - platform: state
  #       entity_id: media_player.denon
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.volume_common_room
  #         value: '{{ trigger.to_state.attributes.volume_level }}'
  # - alias: Volume Adjust Common Room
  #   trigger:
  #     - platform: state
  #       entity_id: input_slider.volume_common_room
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: media_player.volume_set
  #       data_template:
  #         entity_id: media_player.denon
  #         volume_level: "{{ states('input_slider.volume_common_room') }}"
  # - alias: Volume Bedroom
  #   trigger:
  #     - platform: state
  #       entity_id: media_player.itunes
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.itunes', 'volume_level', states('input_slider.volume_bedroom')) }}"
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.volume_bedroom
  #         value: '{{ trigger.to_state.attributes.volume_level }}'
  # - alias: Volume Adjust Bedroom
  #   trigger:
  #     - platform: state
  #       entity_id: input_slider.volume_bedroom
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: media_player.volume_set
  #       data_template:
  #         entity_id: media_player.itunes
  #         volume_level: "{{ states('input_slider.volume_bedroom') }}"
