input_select:
  homemode:
    name: "Home Mode"
    options:
     - Home
     - Away
     - Vacation # alarm clock off
     - Visitor # no autolight off
    initial: Home
    icon: mdi:home-outline

automation:

  - alias: "Set Home Mode"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'off'
        to: 'on'
        for:
          minutes: 10
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'off'
        to: 'on'
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Home'
      - service: script.notifying
        data:
          title: "Home Mode is now active"
          message: 'Home Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 1"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'on'
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: template
        value_template: '{% if is_state("input_boolean.presence_jue", "off") %}true{% else %}{% endif %}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Away'
      - service: notify.notifying
        data:
          title: "Away Mode #1 is now active"
          message: 'Away Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 2"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'on'
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: template
        value_template: '{% if is_state("input_boolean.presence_pe", "off") %}true{% else %}{% endif %}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Away'
      - service: notify.notifying
        data:
          title: "Away Mode #2 is now active"
          message: 'Away Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 1"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'on'
        to: 'off'
        for:
          hours: 20
    condition:
      - condition: template
        value_template: '{% if is_state("input_boolean.presence_jue", "off") %}true{% else %}{% endif %}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Vacation'
      - service: notify.notifying
        data:
          title: "Vacation Mode #1 is now active"
          message: 'Vacation Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 2"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'on'
        to: 'off'
        for:
          hours: 20
    condition:
      - condition: template
        value_template: '{% if is_state("input_boolean.presence_pe", "off") %}true{% else %}{% endif %}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Vacation'
      - service: notify.notifying
        data:
          title: "Vacation Mode #2 is now active"
          message: 'Vacation Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
