# Profiles HASS Module
#
# Provides several profiles that manage settings.

# - Standard:
#     Uses reports, alarms, etc according to configuration.
# - Relax:
#     Disables reports, changes volumes, starts hue. Disables welcome music. Shut down PC if not in use? (wake on lan?)
# - Sleep:
#     Disable all welcome messages. Disable texting and voice messages.
#     Keep alarm clock on. Keep room covers down and don't move the other.
#     Disable mode automatically if alarm clock triggers.
# - Guests:
#     Disables automatic shutdown of media players and lights on leaving the house, or when turning on other mediaplayers.
#     Keeps covers open.
# - Nobody:
#     Mode when everyone is out (temporarily). Heating and such keep working. Covers are not moved (may be summer?).
# - Away:
#     When on holidays or away from home. Disables alarm clock, reports, etc, keep media shut down. Heating, covers.
#     When back, emits a permanent notification and changes mode to Standard?

input_select:
  homemode:
    name: "Home Mode"
    options:
     - Home
     - Guest # no autolight off
     - Away
     - Vacation # alarm clock off
    initial: Home
    icon: mdi:home-outline

input_slider:
  volume_common_room:
    name: Volume Common Room
    initial: 0.35
    min: 0.0
    max: 0.5
    step: 0.05
    icon: mdi:volume-high
  volume_bedroom:
    name: Volume Bedroom
    initial: 0.2
    min: 0.0
    max: 1.0
    step: 0.05
    icon: mdi:volume-high

# script:
#   homeconfig:
#     alias: "Home Mode Configuration"
#     sequence:
#       - service_template: "input_boolean.{{ 'turn_on' if welcome_music == 'True' else 'turn_off' }}"
#         entity_id: input_boolean.welcome_music
#       - service_template: "input_boolean.{{ 'turn_on' if welcome_report == 'True' else 'turn_off' }}"
#         entity_id: input_boolean.welcome_report
#       - service_template: "input_boolean.{{ 'turn_on' if periodic_report == 'True' else 'turn_off' }}"
#         entity_id: input_boolean.periodic_report
#       - service_template: "input_boolean.{{ 'turn_on' if leaving_media_stop == 'True' else 'turn_off' }}"
#         entity_id: input_boolean.leaving_media_stop
#       - service_template: "input_boolean.{{ 'turn_on' if warnings_enabled == 'True' else 'turn_off' }}"
#         entity_id: input_boolean.warnings_enabled
#       - service: input_slider.select_value
#         entity_id: input_slider.volume_common_room
#         data_template:
#           value: '{{ volume_common_room }}'
#       - service: input_slider.select_value
#         entity_id: input_slider.volume_bedroom
#         data_template:
#           value: '{{ volume_bedroom }}'

automation:
  - alias: "Set Home Mode 1"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'not_home'
        to: 'home'
        for:
          hours: 0
          minutes: 10
          seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.juesiphone6splus
        state: 'home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Home
      - service: script.flashing_once
        data:
          title: "Home Mode is now active"
          message: 'Home Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Home Mode 2"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'not_home'
        to: 'home'
        for:
          hours: 0
          minutes: 10
          seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.pesiphone6
        state: 'home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Home
      - service: script.flashing_once
        data:
          title: "Home Mode is now active"
          message: 'Home Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 1"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'home'
        to: 'not_home'
        for:
          hours: 1
          minutes: 0
          seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.juesiphone6splus
        state: 'not_home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Away
      - service: notify.email
        data:
          title: "Away Mode is now active"
          message: 'Away Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 2"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'home'
        to: 'not_home'
        for:
          hours: 1
          minutes: 0
          seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.pesiphone6
        state: 'not_home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Away
      - service: notify.email
        data:
          title: "Away Mode is now active"
          message: 'Away Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 1"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'home'
        to: 'not_home'
        for:
          hours: 20
          minutes: 0
          seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.juesiphone6splus
        state: 'not_home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Vacation
      - service: notify.email
        data:
          title: "Vacation Mode is now active"
          message: 'Vacation Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 2"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'home'
        to: 'not_home'
        for:
          hours: 20
          minutes: 0
          seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.pesiphone6
        state: 'not_home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Vacation
      - service: notify.email
        data:
          title: "Vacation Mode is now active"
          message: 'Vacation Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  # - alias: Home Mode Change
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #   action:
  #     - service: script.notify
  #       data_template:
  #         notify_text: "Perfil: {{ states.input_select.homemode.state }}'"
  #         notify_mobile: False

  # - alias: Profile Home
  #   initial_state: false
  #   hide_entity: false
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #     state: Home
  #   action:
  #     - service: script.homeconfig
  #       data_template:
  #         welcome_music: True
  #         welcome_report: True
  #         periodic_report: True
  #         warnings_enabled: True
  #         leaving_media_stop: True
  #         volume_common_room: 20
  #         volume_bedroom: 20
  #
  # - alias: Profile Guest
  #   initial_state: false
  #   hide_entity: false
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #     state: Guest
  #   action:
  #     - service: script.homeconfig
  #       data_template:
  #         welcome_music: True
  #         welcome_report: False
  #         periodic_report: False
  #         warnings_enabled: False
  #         leaving_media_stop: False
  #         volume_common_room: 30
  #         volume_bedroom: 20
  #
  # - alias: Profile Away
  #   initial_state: false
  #   hide_entity: false
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #     state: Away
  #   action:
  #     - service: script.homeconfig
  #       data_template:
  #         welcome_music: False
  #         welcome_report: False
  #         periodic_report: False
  #         warnings_enabled: False
  #         leaving_media_stop: True
  #         volume_common_room: 0
  #         volume_bedroom: 10
  #
  # - alias: Profile Vacation
  #   initial_state: false
  #   hide_entity: false
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #     state: Vacation
  #   action:
  #     - service: script.homeconfig
  #       data_template:
  #         welcome_music: False
  #         welcome_report: False
  #         periodic_report: False
  #         warnings_enabled: False
  #         leaving_media_stop: True
  #         volume_common_room: 0
  #         volume_bedroom: 0

  - alias: Volume Common Room
    trigger:
      - platform: state
        entity_id: input_slider.volume_common_room
    action:
      - service: media_player.volume_set
        entity_id:
          - media_player.denon
        data_template:
          volume_level: "{{ states.input_slider.volume_common_room.state }}"

  - alias: Volume Bedroom
    trigger:
      - platform: state
        entity_id: input_slider.volume_bedroom
    action:
      - service: media_player.volume_set
        entity_id:
          - media_player.itunes
        data_template:
          volume_level: "{{ states.input_slider.volume_bedroom.state }}"

  # - alias: Volume Common Room
  #   trigger:
  #     - platform: state
  #       entity_id: media_player.denon
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.volume_common_room
  #         value: "{{ states.media_player.denon.attributes.volume_level }}"
  #
  # - alias: Volume Bedroom
  #   trigger:
  #     - platform: state
  #       entity_id: media_player.itunes
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.volume_bedroom
  #         value: "{{ states.media_player.itunes.attributes.volume_level }}"
