input_select:
  homemode:
    name: "Home Mode"
    options:
     - Home
     - Away
     - Vacation # alarm clock off
     - Visitor # no autolight off
    # initial: Home
    icon: mdi:home-outline

# input_slider:
#   volume_common_room:
#     name: Volume Common Room
#     initial: 0.35
#     min: 0.0
#     max: 0.5
#     step: 0.05
#     icon: mdi:volume-high
#   volume_bedroom:
#     name: Volume Bedroom
#     initial: 0.25
#     min: 0.0
#     max: 0.5
#     step: 0.05
#     icon: mdi:volume-high

script:

  autolight_sunset_home:
    alias: "Autolight Sunset Home"
    sequence:
      - service: script.flashing_once
        data:
          title: "Lightstrip has been turned on"
          message: '15 minutes before sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.lightstrip
        data:
          transition: 300
          brightness: 200
          xy_color: [0.1794, 0.0964]
      - delay: 01:15:00
      - service: script.flashing_once
        data:
          title: "Lightstrip has been turned off"
          message: '1.5 hours after sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.lightstrip

  autolight_sunset_away:
    alias: "Autolight Sunset Away"
    sequence:
      - service: script.notifying
        data:
          title: "Garage light has been turned on"
          message: '15 minutes before sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.garage
        data:
          transition: 300
          brightness: 255
      - delay: 01:15:00
      - service: script.notifying
        data:
          title: "Garage light has been turned off"
          message: '1.5 hours after sunset [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.garage

  autolight_mode_home_1:
    alias: "Autolight Home 1"
    sequence:
      - service: script.flashing_once
        data:
          title: "Downstairs Light has been turned on"
          message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.front_1
        data:
          transition: 5
          brightness: 200
      - delay: 00:30:00
      - service: script.flashing_once
        data:
          title: "Downstairs Light has been turned off"
          message: 'At 20:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.front_1

  autolight_mode_home_2:
    alias: "Autolight Home 2"
    sequence:
      - service: script.flashing_once
        data:
          title: "Bedroom LW has been turned on"
          message: 'At 21:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.bedroom_lw
        data:
          transition: 5
          brightness: 100
      - delay: 01:45:00
      - service: script.flashing_once
        data:
          title: "Bedroom LW has been turned off"
          message: 'At 23:15pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.bedroom_lw

  autolight_mode_away_1:
    alias: "Autolight Away 1"
    sequence:
      - service: script.notifying
        data:
          title: "Garage Light has been turned on"
          message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.garage
        data:
          transition: 1
          brightness: 255
      - delay: 00:45:00
      - service: script.notifying
        data:
          title: "Garage Light has been turned off"
          message: 'At 20:15pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.garage

  autolight_mode_away_2:
    alias: "Autolight Away 2"
    sequence:
      - service: script.notifying
        data:
          title: "Downstairs Light has been turned on"
          message: 'At 20:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.front_2
        data:
          transition: 1
          brightness: 255
      - delay: 00:45:00
      - service: script.notifying
        data:
          title: "Downstairs Light has been turned off"
          message: 'At 20:45pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.front_2

  autolight_mode_away_3:
    alias: "Autolight Away 3"
    sequence:
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned on"
          message: 'At 21:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.bedroom_lw
        data:
          transition: 1
          brightness: 255
      - delay: 00:30:00
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned off"
          message: 'At 22:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.bedroom_lw

  autolight_mode_away_4:
    alias: "Autolight Away 4"
    sequence:
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned on"
          message: 'At 22:40pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.bedroom_lw
        data:
          transition: 1
          brightness: 255
      - delay: 00:30:00
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned off"
          message: 'At 23:10pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.bedroom_lw

  autolight_mode_vacation_1:
    alias: "Autolight Vacation 1"
    sequence:
      - service: script.notifying
        data:
          title: "Garage Light has been turned on"
          message: 'At 19:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.garage
        data:
          transition: 1
          brightness: 255
      - delay: 00:30:00
      - service: script.notifying
        data:
          title: "Garage Light has been turned off"
          message: 'At 20:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.garage

  autolight_mode_vacation_2:
    alias: "Autolight Vacation 2"
    sequence:
      - service: script.notifying
        data:
          title: "Downstairs Light has been turned on"
          message: 'At 20:15pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.front_2
        data:
          transition: 1
          brightness: 255
      - delay: 00:40:00
      - service: script.notifying
        data:
          title: "Downstairs Light has been turned off"
          message: 'At 20:55pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.front_2

  autolight_mode_vacation_3:
    alias: "Autolight Vacation 3"
    sequence:
      - service: script.notifying
        data:
          title: "Common Room 1 has been turned on"
          message: 'At 21:15pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.common_room_1
        data:
          transition: 1
          brightness: 255
      - delay: 00:30:00
      - service: script.notifying
        data:
          title: "Common Room 1 has been turned off"
          message: 'At 21:45pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.common_room_1

  autolight_mode_vacation_4:
    alias: "Autolight Vacation 4"
    sequence:
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned on"
          message: 'At 22:00pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_on
        entity_id: light.bedroom_lw
        data:
          transition: 1
          brightness: 255
      - delay: 00:30:00
      - service: script.notifying
        data:
          title: "Bedroom LW has been turned off"
          message: 'At 22:30pm everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: light.turn_off
        entity_id: light.bedroom_lw

automation:

  - alias: "Set Home Mode 1"
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'off'
        to: 'on'
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.presence_jue
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Home
      - service: script.flashing_once
        data:
          title: "Home Mode is now active"
          message: 'Home Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Home Mode 2"
    trigger:
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'off'
        to: 'on'
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.presence_pe
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Home
      - service: script.flashing_once
        data:
          title: "Home Mode is now active"
          message: 'Home Mode is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 1"
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'on'
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: input_boolean.presence_jue
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Away
      - service: notify.email
        data:
          title: "Away Mode #1 is now active"
          message: 'Away Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 2"
    trigger:
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'on'
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: input_boolean.presence_pe
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Away
      - service: notify.email
        data:
          title: "Away Mode #2 is now active"
          message: 'Away Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 1"
    trigger:
      - platform: state
        entity_id: input_boolean.presence_pe
        from: 'on'
        to: 'off'
        for:
          hours: 20
    condition:
      - condition: state
        entity_id: input_boolean.presence_jue
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Vacation
      - service: notify.email
        data:
          title: "Vacation Mode #1 is now active"
          message: 'Vacation Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 2"
    trigger:
      - platform: state
        entity_id: input_boolean.presence_jue
        from: 'on'
        to: 'off'
        for:
          hours: 20
    condition:
      - condition: state
        entity_id: input_boolean.presence_pe
        state: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Vacation
      - service: notify.email
        data:
          title: "Vacation Mode #2 is now active"
          message: 'Vacation Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolights All Off 1"
    trigger:
      - platform: time
        after: '00:01:00'
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: light.turn_off
        entity_id: group.all_lights
      - service: script.flashing_once
        data:
          title: "All lights has been turned off"
          message: 'All lights are off after midnight everyday [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolights All Off 2"
    trigger:
      - platform: state
        entity_id: input_select.homemode
        to: Away
      - platform: state
        entity_id: input_select.homemode
        to: Vacation
    action:
      - service: light.turn_off
        entity_id: group.all_lights
      - service: script.notifying
        data:
          title: "All lights has been turned off"
          message: 'All lights are off when noboby is home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Autolight Sunset Home"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:15:00"
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: script.autolight_sunset_home

  - alias: "Autolight Sunset Away"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:15:00"
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: script.autolight_sunset_away

  - alias: "Autolight Home 1"
    trigger:
      - platform: time
        hours: 19
        minutes: 30
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: script.autolight_mode_home_1

  - alias: "Autolight Home 2"
    trigger:
      - platform: time
        hours: 21
        minutes: 30
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Home
    action:
      - service: script.autolight_mode_home_2

  - alias: "Autolight Away 1"
    trigger:
      - platform: time
        hours: 19
        minutes: 30
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: script.autolight_mode_away_1

  - alias: "Autolight Away 2"
    trigger:
      - platform: time
        hours: 20
        minutes: 0
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: script.autolight_mode_away_2

  - alias: "Autolight Away 3"
    trigger:
      - platform: time
        hours: 21
        minutes: 30
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: script.autolight_mode_away_3

  - alias: "Autolight Away 4"
    trigger:
      - platform: time
        hours: 22
        minutes: 40
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Away
    action:
      - service: script.autolight_mode_away_4

  - alias: "Autolight Vacation 1"
    trigger:
      - platform: time
        hours: 19
        minutes: 30
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: script.autolight_mode_vacation_1

  - alias: "Autolight Vacation 2"
    trigger:
      - platform: time
        hours: 20
        minutes: 15
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: script.autolight_mode_vacation_2

  - alias: "Autolight Vacation 3"
    trigger:
      - platform: time
        hours: 21
        minutes: 15
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: script.autolight_mode_vacation_3

  - alias: "Autolight Vacation 4"
    trigger:
      - platform: time
        hours: 22
        minutes: 0
        seconds: 0
    condition:
      - condition: state
        entity_id: input_select.homemode
        state: Vacation
    action:
      - service: script.autolight_mode_vacation_4

  # - alias: Volume Common Room
  #   trigger:
  #     - platform: state
  #       entity_id: media_player.denon
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.volume_common_room
  #         value: '{{ trigger.to_state.attributes.volume_level }}'
  # - alias: Volume Adjust Common Room
  #   trigger:
  #     - platform: state
  #       entity_id: input_slider.volume_common_room
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: media_player.volume_set
  #       data_template:
  #         entity_id: media_player.denon
  #         volume_level: "{{ states('input_slider.volume_common_room') }}"
  # - alias: Volume Bedroom
  #   trigger:
  #     - platform: state
  #       entity_id: media_player.itunes
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.itunes', 'volume_level', states('input_slider.volume_bedroom')) }}"
  #   action:
  #     - service: input_slider.select_value
  #       data_template:
  #         entity_id: input_slider.volume_bedroom
  #         value: '{{ trigger.to_state.attributes.volume_level }}'
  # - alias: Volume Adjust Bedroom
  #   trigger:
  #     - platform: state
  #       entity_id: input_slider.volume_bedroom
  #   condition:
  #     - condition: template
  #       value_template: "{{ not is_state_attr('media_player.denon', 'volume_level', states('input_slider.volume_common_room')) }}"
  #   action:
  #     - service: media_player.volume_set
  #       data_template:
  #         entity_id: media_player.itunes
  #         volume_level: "{{ states('input_slider.volume_bedroom') }}"
