# Profiles HASS Module
#
# Provides several profiles that manage settings.

# - Standard:
#     Uses reports, alarms, etc according to configuration.
# - Relax:
#     Disables reports, changes volumes, starts hue. Disables welcome music. Shut down PC if not in use? (wake on lan?)
# - Sleep:
#     Disable all welcome messages. Disable texting and voice messages.
#     Keep alarm clock on. Keep room covers down and don't move the other.
#     Disable mode automatically if alarm clock triggers.
# - Guests:
#     Disables automatic shutdown of media players and lights on leaving the house, or when turning on other mediaplayers.
#     Keeps covers open.
# - Nobody:
#     Mode when everyone is out (temporarily). Heating and such keep working. Covers are not moved (may be summer?).
# - Away:
#     When on holidays or away from home. Disables alarm clock, reports, etc, keep media shut down. Heating, covers.
#     When back, emits a permanent notification and changes mode to Standard?

input_select:

  homemode:
    name: "Home Mode"
    options:
     - Home
     - Away
     - Visitor # no autolight off
     - Vacation # alarm clock off
    initial: Home
    icon: mdi:home-outline


input_slider:

  volume_common_room:
    name: Volume Common Room
    initial: 0.35
    min: 0.0
    max: 0.5
    step: 0.05
    icon: mdi:volume-high

  volume_bedroom:
    name: Volume Bedroom
    # initial: 0.2
    min: 0.0
    max: 0.5
    step: 0.05
    icon: mdi:volume-high


# script:
#   homeconfig:
#     alias: "Home Configuration"
#     sequence:
#       - service_template: "input_boolean.{{ 'turn_on' if alarmclock == 'true' else 'turn_off' }}"
#         entity_id: input_boolean.activate_alarm
#       - service_template: "script.{{ 'turn_on' if autolighthome == 'true' else 'turn_off' }}"
#         entity_id: script.autolight_mode_home_1
#       - service_template: "script.{{ 'turn_on' if autolighthome == 'true' else 'turn_off' }}"
#         entity_id: script.autolight_mode_home_2
#       - service_template: "script.{{ 'turn_on' if autolightaway == 'true' else 'turn_off' }}"
#         entity_id: script.autolight_mode_away_1
#       - service_template: "script.{{ 'turn_on' if autolightaway == 'true' else 'turn_off' }}"
#         entity_id: script.autolight_mode_away_2
#       - service_template: "script.{{ 'turn_on' if autolightaway == 'true' else 'turn_off' }}"
#         entity_id: script.autolight_mode_away_3
#       - service_template: "script.{{ 'turn_on' if autolightvacation == 'true' else 'turn_off' }}"
#         entity_id: script.autolight_mode_vacation_1
#       - service_template: "script.{{ 'turn_on' if autolightvacation == 'true' else 'turn_off' }}"
#         entity_id: script.autolight_mode_vacation_2
#       - service_template: "script.{{ 'turn_on' if autolightvacation == 'true' else 'turn_off' }}"
#         entity_id: script.autolight_mode_vacation_3
#       - service: input_slider.select_value
#         entity_id: input_slider.volume_common_room
#         data_template:
#           value: '{{ volume_common_room }}'
#       - service: input_slider.select_value
#         entity_id: input_slider.volume_bedroom
#         data_template:
#           value: '{{ volume_bedroom }}'


automation:

  # - alias: Home Mode Change
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #   action:
  #     - service: script.flashing_short
  #       data:
  #         title: "Home mode has been changed"
  #         message: 'Home mode has been changed to {{ states.input_select.homemode.state }} [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  # - alias: Profile Home
  #   initial_state: false
  #   hide_entity: false
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #     state: Home
  #   action:
  #     - service: script.homeconfig
  #       data_template:
  #         alarmclock: true
  #         autolighthome: true
  #         autolightaway: false
  #         autolightvacation: false
  #         volume_common_room: 0.3
  #         volume_bedroom: 0.2
  #
  # - alias: Profile Visitor
  #   initial_state: false
  #   hide_entity: false
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #     state: Visitor
  #   action:
  #     - service: script.homeconfig
  #       data_template:
  #         alarmclock: true
  #         autolighthome: false
  #         autolightaway: false
  #         autolightvacation: false
  #         volume_common_room: 0.4
  #         volume_bedroom: 0.2
  #
  # - alias: Profile Away
  #   initial_state: false
  #   hide_entity: false
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #     state: Away
  #   action:
  #     - service: script.homeconfig
  #       data_template:
  #         alarmclock: false
  #         autolighthome: false
  #         autolightaway: true
  #         autolightvacation: false
  #         volume_common_room: 0.35
  #         volume_bedroom: 0.3
  #
  # - alias: Profile Vacation
  #   initial_state: false
  #   hide_entity: false
  #   trigger:
  #     platform: state
  #     entity_id: input_select.homemode
  #     state: Vacation
  #   action:
  #     - service: script.homeconfig
  #       data_template:
  #         alarmclock: false
  #         autolighthome: false
  #         autolightaway: false
  #         autolightvacation: true
  #         volume_common_room: 0.0
  #         volume_bedroom: 0.0

  - alias: Volume Common Room
    trigger:
      - platform: state
        entity_id: media_player.denon
    action:
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.volume_common_room
          value: '{{ states.media_player.denon.attributes.volume_level }}'

  - alias: Volume Adjust Common Room
    trigger:
      - platform: state
        entity_id: input_slider.volume_common_room
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.denon
          volume_level: '{{ states.input_slider.volume_common_room.state }}'

  - alias: Volume Bedroom
    trigger:
      - platform: state
        entity_id: media_player.itunes
    action:
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.volume_bedroom
          value: '{{ states.media_player.itunes.attributes.volume_level }}'

  - alias: Volume Adjust Bedroom
    trigger:
      - platform: state
        entity_id: input_slider.volume_bedroom
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.itunes
          volume_level: '{{ states.input_slider.volume_bedroom.state }}'

  - alias: "Set Home Mode 1"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'not_home'
        to: 'home'
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: device_tracker.juesiphone6splus
        state: 'home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Home
      - service: script.flashing_once
        data:
          title: "Home Mode #1 is now active"
          message: 'Home Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Home Mode 2"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'not_home'
        to: 'home'
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: device_tracker.pesiphone6
        state: 'home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Home
      - service: script.flashing_once
        data:
          title: "Home Mode #2 is now active"
          message: 'Home Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 1"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'home'
        to: 'not_home'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: device_tracker.juesiphone6splus
        state: 'not_home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Away
      - service: notify.email
        data:
          title: "Away Mode #1 is now active"
          message: 'Away Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Away Mode 2"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'home'
        to: 'not_home'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: device_tracker.pesiphone6
        state: 'not_home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Away
      - service: notify.email
        data:
          title: "Away Mode #2 is now active"
          message: 'Away Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 1"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'home'
        to: 'not_home'
        for:
          hours: 20
    condition:
      - condition: state
        entity_id: device_tracker.juesiphone6splus
        state: 'not_home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Vacation
      - service: notify.email
        data:
          title: "Vacation Mode #1 is now active"
          message: 'Vacation Mode #1 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Set Vacation Mode 2"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'home'
        to: 'not_home'
        for:
          hours: 20
    condition:
      - condition: state
        entity_id: device_tracker.pesiphone6
        state: 'not_home'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: Vacation
      - service: notify.email
        data:
          title: "Vacation Mode #2 is now active"
          message: 'Vacation Mode #2 is now active [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
