# Fade the Light On Over 5 Seconds - light.turn_on
#
# {
# 	"entity_id": "light.wemos",
# 	"brightness": 150,
# 	"color_name": "blue",
# 	"transition": "5"
# }
#
# Flash The Light - light.turn_on
#
# {
# 	"entity_id": "light.wemos",
# 	"color_name": "green",
# 	"brightness": 255,
# 	"flash": "short"
# }
#
# Call Rainbow Effect with Slow Animation Speed - light.turn_on
#
# {
# 	"entity_id": "light.wemos",
# 	"transition": "50",
# 	"brightness": 255,
# 	"effect": "rainbow"
# }
#
# Fade the Light Off Over 5 Seconds - light.turn_off
#
# {
# 	"entity_id": "light.wemos",
# 	"transition": "50"
# }

light:
  - platform: mqtt_json
    name: "LED"
    state_topic: "led/state"
    command_topic: "led/set"
    effect: true
    effect_list:
      - applause
      - bpm
      - candy cane
      - confetti
      - cyclone rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      # - noise
      - police all
      - police one
      - rainbow
      - rainbow glitter
      # - ripple
      - sinelon
      - solid
      - strobe
      - twinkle
    # brightness: true
    # flash: true
    # rgb: true
    # optimistic: false
    # qos: 0
    brightness: true
    color_temp: true
    flash_time_long: 10
    flash_time_short: 2
    optimistic: false
    qos: 0
    # retain: true
    rgb: true
    white_value: false
    xy: false

input_number:
  led_animation_speed:
    name: "Animation Speed"
    initial: 5
    min: 1
    max: 10
    step: 1

automation:
  - alias: "LED Animation Speed"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_number.led_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "led/set"
          payload: '{"transition": {{ trigger.to_state.state | int }}}'
