# sensor:
#   - platform: template
#     sensor:
#       motion_summary:
#         value_template: >
#           {%-for state in states.binary_sensor
#             if(state.attributes.device_class=="motion" and state.state=="on")-%}
#               {%-if loop.last-%}
#                 {%-if loop.index > 0-%}
#                   {%-for state in states.binary_sensor if(state.attributes.device_class=="motion" and state.state =="on")-%}
#                     {{state.name}}{%-if not loop.last -%}{%-if(loop.index+1==loop.length)%} & {%else%}, {%endif-%}{%-else%} active{%endif-%}
#                   {%-endfor-%}
#                 {%-endif-%}
#               {%-endif-%}
#             {%-else-%}
#               all clear
#           {%-endfor-%}
#         icon_template: >
#           {%-for state in states.binary_sensor
#             if(state.attributes.device_class=="motion" and state.state=="on")-%}
#               {%-if loop.last-%}
#                 {%-if loop.index > 0-%}
#                     mdi:alert
#                 {%-endif-%}
#               {%-endif-%}
#             {%-else-%}
#               mdi:check
#           {%-endfor-%}

# Fade the Light On Over 5 Seconds - light.turn_on
#
# {
# 	"entity_id": "light.wemos",
# 	"brightness": 150,
# 	"color_name": "blue",
# 	"transition": "5"
# }
#
# Flash The Light - light.turn_on
#
# {
# 	"entity_id": "light.wemos",
# 	"color_name": "green",
# 	"brightness": 255,
# 	"flash": "short"
# }
#
# Call Rainbow Effect with Slow Animation Speed - light.turn_on
#
# {
# 	"entity_id": "light.wemos",
# 	"transition": "50",
# 	"brightness": 255,
# 	"effect": "rainbow"
# }
#
# Fade the Light Off Over 5 Seconds - light.turn_off
#
# {
# 	"entity_id": "light.wemos",
# 	"transition": "50"
# }

# light:
#   - platform: mqtt
#     name: "Wemos"
#     command_topic: "wemos/setpower"
#     state_topic: "wemos/setpowerpub"
#     rgb_state_topic: "wemos/setcolorpub"
#     rgb_command_topic: "wemos/setcolor"
#     brightness_state_topic: "wemos/setbrightnesspub"
#     brightness_command_topic: "wemos/setbrightness"
#     optimistic: false
#
# input_select:
#   wemos_effect:
#     name: "Wemos Effect"
#     options:
#      - "BPM"
#      - "Candy Cane"
#      - "Confetti"
#      - "Cyclon Rainbow"
#      - "Dots"
#      - "Fire"
#      - "Glitter"
#      - "Juggle"
#      - "Lightning"
#      - "Noise"
#      - "Police All"
#      - "Police One"
#      - "Rainbow"
#      - "Rainbow with Glitter"
#      - "Ripple"
#      - "Sinelon"
#      - "Solid"
#      - "Strobe"
#      - "Twinkle"
#     initial: "Solid"
#
# input_slider:
#   wemos_animation_speed:
#     name: "Wemos Animation Speed"
#     initial: 150
#     min: 1
#     max: 150
#     step: 10
#
# automation:
#   - alias: "Wemos Input Effect"
#     initial_state: True
#     hide_entity: False
#     trigger:
#       - platform: state
#         entity_id: input_select.wemos_effect
#     action:
#       - service: mqtt.publish
#         data_template:
#           topic: "wemos/seteffect"
#           payload: '{{ trigger.to_state.state | string }}'
#
#   - alias: "Wemos Animation Speed"
#     initial_state: True
#     hide_entity: False
#     trigger:
#       - platform: state
#         entity_id: input_slider.wemos_animation_speed
#     action:
#       - service: mqtt.publish
#         data_template:
#           topic: "wemos/setanimationspeed"
#           payload: '{{ trigger.to_state.state | int }}'

light:
  - platform: mqtt_json
    name: "Wemos"
    state_topic: "wemos/state"
    command_topic: "wemos/set"
    effect: true
    effect_list:
      - applause
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - solid
      - strobe
      - twinkle
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

input_slider:
  wemos_animation_speed:
    name: "Wemos Animation Speed"
    initial: 150
    min: 1
    max: 150
    step: 10

automation:
  - alias: "Wemos Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_slider.wemos_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "wemos/set"
          payload: '{"transition": {{ trigger.to_state.state | int }}}'
