light:
  - platform: mqtt_json
    name: "Party"
    state_topic: "party/state"
    command_topic: "party/set"
    qos: 1
    flash_time_long: 15
    flash_time_short: 5
    effect: true
    effect_list:
      - applause
      - bpm
      - candy cane
      - confetti
      - cyclone rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow glitter
      - ripple
      - sidefill
      - sinelon
      - solid
      - strobe
      - twinkle
    brightness: true
    color_temp: true
    rgb: true
    optimistic: false
    white_value: false
    xy: false
    hs: false
    retain: false
    unique_id: 411dabf4-aaa9-4012-977c-73f836b4695e

input_number:
  party_animation_speed:
    name: "Animation Speed"
    initial: 100
    min: 1
    max: 150
    step: 10

group:
  party:
    name: "Party Light"
    icon: mdi:led-strip
    control: hidden
    entities:
      - light.party
      - input_number.party_animation_speed

automation:

  - alias: "LED Animation Speed"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_number.party_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "party/set"
          payload: '{"transition": {{ trigger.to_state.state | int }}}'

  - alias: "Set LED Animation Speed"
    trigger:
      - platform: mqtt
        topic: "party/set"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.party_animation_speed
          value: '{{ trigger.payload }}'

#   - alias: "Party Brightness Control mqtt"
#     trigger:
#       - platform: mqtt
#         topic: "party"
#         # Optional
#         # payload: "on"
#     action:
#       - service_template: light.turn_{{ trigger.payload_json.action }}
#         data_template:
#           entity_id: light.{{ trigger.payload_json.device }}
#           brightness: '{{ trigger.payload_json.brightness }}'
#
# {
# 	"device": "party ",
# 	"action": "on",
# 	"brightness": 30
# }

# Fade the Light On Over 5 Seconds - light.turn_on
#
# {
# 	"entity_id": "light.party",
# 	"brightness": 150,
# 	"color_name": "blue",
# 	"transition": "5"
# }
#
# Flash The Light - light.turn_on
#
# {
# 	"entity_id": "light.party",
# 	"color_name": "green",
# 	"brightness": 255,
# 	"flash": "short"
# }
#
# Call Rainbow Effect with Slow Animation Speed - light.turn_on
#
# {
# 	"entity_id": "light.party",
# 	"transition": "50",
# 	"brightness": 255,
# 	"effect": "rainbow"
# }
#
# Fade the Light Off Over 5 Seconds - light.turn_off
#
# {
# 	"entity_id": "light.party",
# 	"transition": "50"
# }
