device_tracker:
  - platform: life360
    username: phumin
    password: !secret my_password
    interval_seconds: 10
    filename: life360.conf
    show_as_state: places, driving, moving
    max_update_wait:
      minutes: 30

automation:

  - alias: "Life360 Overdue Update"
    trigger:
      - platform: event
        event_type: device_tracker.life360_update_overdue
    action:
      - service: persistent_notification.create
        data_template:
          title: "Life360 update overdue"
          message: 'Update for {{ state_attr("trigger.event.data.entity_id", "friendly_name") }} is overdue.'

  - alias: "Life360 Update Restored"
    trigger:
      - platform: event
        event_type: device_tracker.life360_update_restored
    action:
      - service: persistent_notification.create
        data_template:
          title: "Life360 update restored"
          message: 'Update for {{ state_attr("trigger.event.data.entity_id", "friendly_name") }} restored after {{ trigger.event.data.wait }}.'
