group:
  hue_all:
    name: "Lights"
    icon: mdi:lightbulb-outline
    entities:
      - light.whites_a1
      - light.whites_a2
      - light.whites_a3
      - light.whites_a4
      - light.hallway
      - light.tv
      - light.hue_1
      - light.hue_2
      - light.hue_3
      - light.hue_4
      - light.mood
      - light.whites_w
      - light.pandora
      - light.whites_b1
      - light.whites_b2
      - light.hue_w1
      - light.hue_w2
      - light.phoebe
      - light.garage
  hue_common_room_all:
    name: "Common Room Lights"
    icon: mdi:lightbulb-outline
    entities:
      - light.whites_a1
      - light.whites_a2
      - light.whites_a3
      - light.whites_a4
      - light.hallway
      - light.tv
  hue_common_room_main:
    name: "Common Room Main Lights"
    icon: mdi:lightbulb
    entities:
      - light.whites_a1
      - light.whites_a2
      - light.whites_a3
      - light.whites_a4
  hue_bedroom_all:
    name: "Bedroom Lights"
    icon: mdi:lightbulb-outline
    entities:
      - light.hue_1
      - light.hue_2
      - light.hue_3
      - light.hue_4
      - light.mood
      - light.whites_w
      - light.pandora
  hue_bedroom_main:
    name: "Bedroom Main Lights"
    icon: mdi:lightbulb
    entities:
      - light.hue_1
      - light.hue_2
      - light.hue_3
      - light.hue_4
  hue_first_floor_all:
    name: "First Floor Lights"
    icon: mdi:lightbulb-outline
    entities:
      - light.whites_b1
      - light.whites_b2
      - light.hue_w1
      - light.hue_w2
      - light.phoebe
      - light.garage
  hue_first_floor_main:
    name: "First Floor Main Lights"
    icon: mdi:lightbulb
    entities:
      - light.whites_b1
      - light.whites_b2
      - light.hue_w1
      - light.hue_w2
  flashlights:
    name: "Flash Lights"
    icon: mdi:alarm-light
    entities:
      - light.hue_3
      - light.hue_4
      - light.whites_a3
      - light.whites_a4
      - light.whites_b1
      - light.whites_b2
  common_room_scenes:
    name: "Common Room Light Scenes"
    icon: mdi:duck
    control: hidden
    entities:
      - scene.common_room_off
      - scene.common_room_bright
      - scene.common_room_dim
  bedroom_scenes:
    name: "Bedroom Light Scenes"
    icon: mdi:duck
    control: hidden
    entities:
      - scene.bedroom_off
      - scene.bedroom_very_bright
      - scene.bedroom_bright
      - scene.bedroom_night
      - scene.bedroom_sleep
      - scene.bedroom_blossom
      - scene.bedroom_savanna
      - scene.bedroom_twilight
      - scene.bedroom_aurora
  first_floor_scenes:
    name: First Floor Light Scenes
    icon: mdi:duck
    control: hidden
    entities:
      - scene.first_floor_off
      - scene.first_floor_bright
      - scene.first_floor_dim

automation:

  - alias: "Autolight All Off"
    trigger:
      - platform: time
        at: '00:01:00'
    condition:
      - condition: template
        value_template: '{{ not is_state("input_select.homemode", "Visitor") }}'
    action:
      - service: script.all_lights_off_but_pandora
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: "All lights are off after midnight"

  - alias: "Autolight Sunset A"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:15:00"
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") or is_state("input_select.homemode", "Away") }}'
    action:
      - service: light.turn_on
        data_template:
          entity_id: '{% if is_state("input_select.homemode", "Home") %}light.tv{% elif is_state("input_select.homemode", "Away") %}light.garage{% elif is_state("input_select.homemode", "Vacation") %}light.garage{% endif %}'
          transition: '{% if is_state("input_select.homemode", "Home") %}5{% elif is_state("input_select.homemode", "Away") %}5{% elif is_state("input_select.homemode", "Vacation") %}5{% endif %}'
          brightness: '{% if is_state("input_select.homemode", "Home") %}255{% elif is_state("input_select.homemode", "Away") %}255{% elif is_state("input_select.homemode", "Vacation") %}255{% endif %}'
          color_name: '{% if is_state("input_select.homemode", "Home") %}blue{% elif is_state("input_select.homemode", "Away") %}{% elif is_state("input_select.homemode", "Vacation") %}{% endif %}'
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data_template:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: '{% if is_state("input_select.homemode", "Home") %}Lightstrip TV{% elif is_state("input_select.homemode", "Away") %}Garage light{% endif %} has been turned on 15 minutes before sunset'

  - alias: "Autolight Sunset B"
    trigger:
      - platform: sun
        event: sunset
        offset: "+01:00:00"
    condition:
      - condition: template
        value_template: '{{ is_state("light.tv", "on") or is_state("light.garage", "on") }}'
    action:
      - service: light.turn_off
        data_template:
          entity_id: '{% if is_state("light.tv", "on") %}light.tv{% elif is_state("light.garage", "on") %}light.garage{% endif %}'
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data_template:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn off {% if is_state("input_select.homemode", "Home") %}Lightstrip TV{% elif is_state("input_select.homemode", "Away") %}Garage light{% endif %} after sunset for 1 hour'

  - alias: "Autolight 1A"
    trigger:
      - platform: time
        at: '19:30:00'
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") or is_state("input_select.homemode", "Away") or is_state("input_select.homemode", "Vacation") }}'
    action:
      - service: light.turn_on
        data_template:
          entity_id: '{% if is_state("input_select.homemode", "Home") %}light.whites_B1{% elif is_state("input_select.homemode", "Away") %}light.garage{% elif is_state("input_select.homemode", "Vacation") %}light.whites_B2{% endif %}'
          transition: '{% if is_state("input_select.homemode", "Home") %}5{% elif is_state("input_select.homemode", "Away") %}1{% elif is_state("input_select.homemode", "Vacation") %}1{% endif %}'
          brightness: '{% if is_state("input_select.homemode", "Home") %}200{% elif is_state("input_select.homemode", "Away") %}255{% elif is_state("input_select.homemode", "Vacation") %}255{% endif %}'
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data_template:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn on {% if is_state("input_select.homemode", "Home") %}Front 1 light{% elif is_state("input_select.homemode", "Away") %}Garage light{% elif is_state("input_select.homemode", "Vacation") %}Front 2 light{% endif %} at 7:30pm'

  - alias: "Autolight 1B"
    trigger:
      - platform: time
        at: '20:15:00'
    condition:
      - condition: template
        value_template: '{{ is_state("light.whites_B1", "on") or is_state("light.garage", "on") or is_state("light.whites_B2", "on") }}'
    action:
      - service: light.turn_off
        data_template:
          entity_id: '{% if is_state("light.whites_B1", "on") %}light.whites_B1{% elif is_state("light.garage", "on") %}light.garage{% elif is_state("light.whites_B2", "on") %}light.whites_B2{% endif %}'
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data_template:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn off {% if is_state("input_select.homemode", "Home") %}Front 1 light{% elif is_state("input_select.homemode", "Away") %}Garage light{% elif is_state("input_select.homemode", "Vacation") %}Front 2 light{% endif %} at 8:15pm'

  - alias: "Autolight 2A"
    trigger:
      - platform: time
        at: '20:00:00'
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") or is_state("input_select.homemode", "Away") or is_state("input_select.homemode", "Vacation") }}'
    action:
      - service: light.turn_on
        data_template:
          entity_id: '{% if is_state("input_select.homemode", "Home") %}light.phoebe{% elif is_state("input_select.homemode", "Away") %}light.whites_B2{% elif is_state("input_select.homemode", "Vacation") %}light.whites_B1{% endif %}'
          transition: '{% if is_state("input_select.homemode", "Home") %}5{% elif is_state("input_select.homemode", "Away") %}1{% elif is_state("input_select.homemode", "Vacation") %}1{% endif %}'
          brightness: '{% if is_state("input_select.homemode", "Home") %}200{% elif is_state("input_select.homemode", "Away") %}255{% elif is_state("input_select.homemode", "Vacation") %}255{% endif %}'
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data_template:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn on {% if is_state("input_select.homemode", "Home") %}Kitchen light{% elif is_state("input_select.homemode", "Away") %}Front 2 light{% elif is_state("input_select.homemode", "Vacation") %}Front 1 light{% endif %} at 8:00pm'

  - alias: "Autolight 2B"
    trigger:
      - platform: time
        at: '21:00:00'
    condition:
      - condition: template
        value_template: '{{ is_state("light.phoebe", "on") or is_state("light.whites_B2", "on") or is_state("light.whites_B1", "on") }}'
    action:
      - service: light.turn_off
        data_template:
          entity_id: '{% if is_state("light.phoebe", "on") %}light.phoebe{% elif is_state("light.whites_B2", "on") %}light.whites_B2{% elif is_state("light.whites_B1", "on") %}light.whites_B1{% endif %}'
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data_template:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn off {% if is_state("input_select.homemode", "Home") %}Kitchen light{% elif is_state("input_select.homemode", "Away") %}Front 2 light{% elif is_state("input_select.homemode", "Vacation") %}Front 1 light{% endif %} at 9:00pm'

  - alias: "Autolight 3A"
    trigger:
      - platform: time
        at: '21:30:00'
    condition:
      - condition: template
        value_template: '{{ is_state("input_select.homemode", "Home") or is_state("input_select.homemode", "Away") or is_state("input_select.homemode", "Vacation") }}'
    action:
      - service: light.turn_on
        data_template:
          entity_id: '{% if is_state("input_select.homemode", "Home") %}light.whites_w{% elif is_state("input_select.homemode", "Away") %}light.whites_w{% elif is_state("input_select.homemode", "Vacation") %}light.whites_A1{% endif %}'
          transition: '{% if is_state("input_select.homemode", "Home") %}5{% elif is_state("input_select.homemode", "Away") %}1{% elif is_state("input_select.homemode", "Vacation") %}1{% endif %}'
          brightness: '{% if is_state("input_select.homemode", "Home") %}100{% elif is_state("input_select.homemode", "Away") %}255{% elif is_state("input_select.homemode", "Vacation") %}255{% endif %}'
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data_template:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn on {% if is_state("input_select.homemode", "Home") %}Warm light{% elif is_state("input_select.homemode", "Away") %}Warm light{% elif is_state("input_select.homemode", "Vacation") %}Common Room 1 light{% endif %} at 9:30pm'

  - alias: "Autolight 3B"
    trigger:
      - platform: time
        at: '23:00:00'
    condition:
      - condition: template
        value_template: '{{ is_state("light.whites_w", "on") or is_state("light.whites_A1", "on") }}'
    action:
      - service: light.turn_off
        data_template:
          entity_id: '{% if is_state("light.whites_w", "on") %}light.whites_w{% elif is_state("light.whites_A1", "on") %}light.whites_A1{% endif %}'
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data_template:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn off {% if is_state("input_select.homemode", "Home") %}Warm light{% elif is_state("input_select.homemode", "Away") %}Warm light{% elif is_state("input_select.homemode", "Vacation") %}Common Room 1 light{% endif %} at 11:00pm'

  - alias: "Autolight Bedroom 1A"
    trigger:
      - platform: time
        at: '18:00:00'
    condition:
      - condition: template
        value_template: '{{ is_state("light.pandora", "off") and (is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on")) }}'
    action:
      - service: light.turn_on
        entity_id: light.pandora
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn on Bedroom Night light at 6:00pm'

  - alias: "Autolight Bedroom 1B"
    trigger:
      - platform: time
        at: '19:30:00'
    condition:
      - condition: template
        value_template: '{{ is_state("light.pandora", "on") and (is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on")) }}'
    action:
      - service: light.turn_off
        entity_id: light.pandora
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn off Bedroom Night light at 7:30pm'

  - alias: "Autolight Bedroom 2A"
    trigger:
      - platform: time
        at: '22:30:00'
    condition:
      - condition: template
        value_template: '{{ is_state("light.pandora", "off") and (is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on")) }}'
    action:
      - service: light.turn_on
        entity_id: light.pandora
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn on Bedroom Night light again at 10:30pm'

  - alias: "Autolight Bedroom 2B"
    trigger:
      - platform: time
        at: '23:00:00'
    condition:
      - condition: template
        value_template: '{{ is_state("light.pandora", "on") and (is_state("input_select.homemode", "Home") and is_state("input_boolean.presence_pe", "on")) }}'
    action:
      - service: light.turn_off
        entity_id: light.pandora
      - service_template: '{% if is_state("script.notifying", "off") %}script.notifying{% endif %}'
        data:
          email: "false"
          tv: "true"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "false"
          line: "false"
          message: 'Turn off Bedroom Night light again at 11:00pm'

  - alias: "Auto off Welcome light"
    trigger:
      - platform: template
        value_template: '{{ (is_state("light.hallway", "on") and is_state_attr("light.hallway", "rgb_color", (255,106,88))) and (is_state("light.tv", "on") and is_state_attr("light.tv", "rgb_color", (255,104,92))) }}'
      - platform: template
        value_template: '{{ (is_state("light.hallway", "on") and is_state_attr("light.hallway", "rgb_color", (220,239,68))) and (is_state("light.tv", "on") and is_state_attr("light.tv", "rgb_color", (163,255,93))) }}'
    action:
      - service: script.welcome_light_off

  - alias: "Auto off Distance light"
    trigger:
      - platform: template
        value_template: '{{ is_state("light.hallway", "on") and is_state_attr("light.hallway", "rgb_color", (235,255,67)) }}'
      - platform: template
        value_template: '{{ is_state("light.hallway", "on") and is_state_attr("light.hallway", "rgb_color", (255,165,39)) }}'
      - platform: template
        value_template: '{{ is_state("light.hallway", "on") and is_state_attr("light.hallway", "rgb_color", (255,68,0)) }}'
    action:
      - service: script.distance_light_off

  - alias: "Auto off Reset Light Bedroom 1"
    trigger:
      - platform: template
        value_template: '{{ is_state("light.hue_1", "on") and is_state_attr("light.hue_1", "rgb_color", (255,207,120)) }}'
    action:
      - service: light.turn_off
        entity_id: light.hue_1

  - alias: "Auto off Reset Light Bedroom 2"
    trigger:
      - platform: template
        value_template: '{{ is_state("light.hue_2", "on") and is_state_attr("light.hue_2", "rgb_color", (255,207,120)) }}'
    action:
      - service: light.turn_off
        entity_id: light.hue_2

  - alias: "Auto off Reset Light Bedroom 3"
    trigger:
      - platform: template
        value_template: '{{ is_state("light.hue_3", "on") and is_state_attr("light.hue_3", "rgb_color", (255,207,120)) }}'
    action:
      - service: light.turn_off
        entity_id: light.hue_3

  - alias: "Auto off Reset Light Bedroom 4"
    trigger:
      - platform: template
        value_template: '{{ is_state("light.hue_4", "on") and is_state_attr("light.hue_4", "rgb_color", (255,207,120)) }}'
    action:
      - service: light.turn_off
        entity_id: light.hue_4

  - alias: "Auto off Reset Light Hallway"
    trigger:
      - platform: template
        value_template: '{{ is_state("light.hallway", "on") and is_state_attr("light.hallway", "rgb_color", (255,207,120)) }}'
    action:
      - service: light.turn_off
        entity_id: light.hallway
