binary_sensor:

  - platform: ping
    host: 192.168.1.1
    name: "Deeper"

  - platform: ping
    host: 192.168.1.2
    name: "Pluto"

  - platform: ping
    host: 192.168.1.3
    name: "Neptune"

  - platform: ping
    host: 192.168.1.4
    name: "Uranus"

  - platform: ping
    host: 192.168.1.5
    name: "Mercury"

  - platform: ping
    host: 192.168.1.11
    name: "Higher"

  - platform: ping
    host: 192.168.1.13
    name: "Broadlink RM Pro"

  - platform: ping
    host: 192.168.1.14
    name: "Broadlink RM Mini"

  - platform: ping
    host: 192.168.1.16
    name: "Titan"

  - platform: ping
    host: 192.168.1.17
    name: "Europa"

  - platform: ping
    host: 192.168.1.18
    name: "Callisto"

  - platform: ping
    host: 192.168.1.19
    name: "Ganymede"

  - platform: ping
    host: 192.168.1.22
    name: "Moon"

  - platform: ping
    host: 192.168.1.44
    name: "Printer"

  - platform: ping
    host: 192.168.1.78
    name: "Foscam Black"

  - platform: ping
    host: 192.168.1.79
    name: "Foscam White"

##########################################

  - platform: ping
    host: 192.168.1.45
    name: "XDJ_RX"

  - platform: ping
    host: 192.168.1.55
    name: "Apple_TV"

  - platform: ping
    host: 192.168.1.66
    name: "Denon"

  - platform: ping
    host: 192.168.1.77
    name: "Dune"

  - platform: ping
    host: 192.168.1.88
    name: "Android_Box"

##########################################

automation:

  # - alias: 'Device status offline'
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.deeper, binary_sensor.higher, binary_sensor.pluto, binary_sensor.neptune, binary_sensor.uranus, binary_sensor.mercury, binary_sensor.moon, binary_sensor.broadlink_rm_pro, binary_sensor.broadlink_rm_mini, binary_sensor.foscam_black, binary_sensor.foscam_white, binary_sensor.printer, binary_sensor.titan, binary_sensor.europa, binary_sensor.callisto, binary_sensor.xdj_rx, binary_sensor.apple_tv, binary_sensor.denon, binary_sensor.dune, binary_sensor.android_box
  #       from: 'on'
  #       to: 'off'
  #       for:
  #         minutes: 5
  #   action:
  #     - service: script.notifying
  #       data_template:
  #         title: '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}'
  #         message: '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }} [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  #
  # - alias: 'Device status online'
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.deeper, binary_sensor.higher, binary_sensor.pluto, binary_sensor.neptune, binary_sensor.uranus, binary_sensor.mercury, binary_sensor.moon, binary_sensor.broadlink_rm_pro, binary_sensor.broadlink_rm_mini, binary_sensor.foscam_black, binary_sensor.foscam_white, binary_sensor.printer, binary_sensor.titan, binary_sensor.europa, binary_sensor.callisto, binary_sensor.xdj_rx, binary_sensor.apple_tv, binary_sensor.denon, binary_sensor.dune, binary_sensor.android_box
  #       from: 'off'
  #       to: 'on'
  #       for:
  #         minutes: 1
  #   action:
  #     - service: script.notifying
  #       data_template:
  #         title: '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}'
  #         message: '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }} [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Deeper"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.deeper
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "The primary gateway is offline"
          message: 'The primary gateway is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Higher"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.higher
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "The secondary gateway is offline"
          message: 'The secondary gateway is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Pluto"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.pluto
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Airport Extreme is offline"
          message: 'Airport Extreme is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Neptune"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.neptune
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Airport Express Bedroom is offline"
          message: 'Airport Express Bedroom is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Uranus"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.uranus
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Airport Express Downstairs is offline"
          message: 'Airport Express Downstairs is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Mercury"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.mercury
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Airport Express Working Space is offline"
          message: 'Airport Express Working Space is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Hue"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.moon
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Philips Hue is offline"
          message: 'Philips Hue is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Broadlink RM Pro"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.broadlink_rm_pro
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Broadlink RM Pro is offline"
          message: 'Broadlink RM Pro is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Broadlink RM Mini"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.broadlink_rm_mini
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Broadlink RM Mini is offline"
          message: 'Broadlink RM Mini is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Foscam Black"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.foscam_black
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Foscam Black is offline"
          message: 'Foscam Black is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Foscam White"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.foscam_white
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Foscam White is offline"
          message: 'Foscam White is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Printer"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.printer
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Printer is offline"
          message: 'Printer is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Titan"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.titan
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Smart Plug in Common Room is offline"
          message: 'Smart Plug in Common Room is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Europa"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.europa
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Smart Plug in Bedroom is offline"
          message: 'Smart Plug in Bedroom is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Callisto"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.callisto
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Subwoofer Switch in Common Room is offline"
          message: 'Subwoofer Switch in Common Room is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: "Offline Ganymede"
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.ganymede
        to: 'off'
    action:
      - service: script.notifying
        data:
          title: "Ganymede Fan Switch in Common Room is offline"
          message: 'Ganymede Fan Switch in Common Room is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
