binary_sensor:
  - platform: ping
    host: 192.168.1.1
    name: "Deeper"
  - platform: ping
    host: 192.168.1.2
    name: "Pluto"
  - platform: ping
    host: 192.168.1.3
    name: "Neptune"
  - platform: ping
    host: 192.168.1.4
    name: "Uranus"
  - platform: ping
    host: 192.168.1.5
    name: "Mercury"
  - platform: ping
    host: 192.168.1.6
    name: "Apollo"
  - platform: ping
    host: 192.168.1.7
    name: "Sputnik"
  - platform: ping
    host: 192.168.1.11
    name: "Higher"

  - platform: ping
    host: 192.168.1.13
    name: "Broadlink RM Pro"
  - platform: ping
    host: 192.168.1.14
    name: "Broadlink RM Mini"

  - platform: ping
    host: 192.168.1.20
    name: "Titan"
  - platform: ping
    host: 192.168.1.21
    name: "Europa"

  - platform: ping
    host: 192.168.1.22
    name: "Ganymede"
  - platform: ping
    host: 192.168.1.23
    name: "Callisto"
  - platform: ping
    host: 192.168.1.24
    name: "Mimas"
  - platform: ping
    host: 192.168.1.25
    name: "Pandora"
  - platform: ping
    host: 192.168.1.26
    name: "Phoebe"
  - platform: ping
    host: 192.168.1.27
    name: "Calypso"

  - platform: ping
    host: 192.168.1.40
    name: "Moon"
  - platform: ping
    host: 192.168.1.44
    name: "Earth"

  - platform: ping
    host: 192.168.1.46
    name: "Wemos-Lite-A"
  - platform: ping
    host: 192.168.1.47
    name: "Wemos-Lite-LED"
  - platform: ping
    host: 192.168.1.48
    name: "Wemos-Pro"
  - platform: ping
    host: 192.168.1.49
    name: "NodeMCU"
  - platform: ping
    host: 192.168.1.51
    name: "Wemos-A"
  - platform: ping
    host: 192.168.1.52
    name: "Wemos-B"

  - platform: ping
    host: 192.168.1.78
    name: "Foscam Black"
  - platform: ping
    host: 192.168.1.79
    name: "Foscam White"

automation:

  # - alias: 'Device status offline'
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.broadlink_rm_pro, binary_sensor.broadlink_rm_mini, binary_sensor.moon, binary_sensor.earth, binary_sensor.foscam_black, binary_sensor.foscam_white
  #       from: 'on'
  #       to: 'off'
  #       for:
  #         minutes: 5
  #   action:
  #     - service: script.notifying
  #       data_template:
  #         email: "false"
  #         tv: "true"
  #         speak: "true"
  #         audio: "sinewave"
  #         light: "false"
  #         mobile: "false"
  #         title: '{{ trigger.to_state.attributes.friendly_name }} is {{ "Online" if trigger.to_state.state == "on" else "Offline" }}'
  #         message: '{{ trigger.to_state.attributes.friendly_name }} is {{ "Online" if trigger.to_state.state == "on" else "Offline" }} [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  # - alias: 'Router status offline'
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.deeper, binary_sensor.pluto, binary_sensor.neptune, binary_sensor.uranus, binary_sensor.mercury, binary_sensor.apollo, binary_sensor.sputnik, binary_sensor.higher
  #       from: 'on'
  #       to: 'off'
  #       for:
  #         minutes: 5
  #   action:
  #     - service: script.notifying
  #       data_template:
  #         email: "false"
  #         tv: "true"
  #         speak: "true"
  #         audio: "sinewave"
  #         light: "false"
  #         mobile: "false"
  #         title: '{{ trigger.to_state.attributes.friendly_name }} is {{ "Online" if trigger.to_state.state == "on" else "Offline" }}'
  #         message: '{{ trigger.to_state.attributes.friendly_name }} is {{ "Online" if trigger.to_state.state == "on" else "Offline" }} [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  # - alias: 'Smart plug status offline'
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.titan, binary_sensor.europa, binary_sensor.ganymede, binary_sensor.callisto, binary_sensor.mimas, binary_sensor.pandora, binary_sensor.phoebe, binary_sensor.calypso
  #       from: 'on'
  #       to: 'off'
  #       for:
  #         minutes: 5
  #   action:
  #     - service: script.notifying
  #       data_template:
  #         email: "false"
  #         tv: "true"
  #         speak: "true"
  #         audio: "sinewave"
  #         light: "false"
  #         mobile: "false"
  #         title: '{{ trigger.to_state.attributes.friendly_name }} is {{ "Online" if trigger.to_state.state == "on" else "Offline" }}'
  #         message: '{{ trigger.to_state.attributes.friendly_name }} is {{ "Online" if trigger.to_state.state == "on" else "Offline" }} [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: 'Bedroom Broadlink offline restart'
    trigger:
      - platform: template
        value_template: '{{ is_state("binary_sensor.broadlink_rm_mini", "off") }}'
    action:
      - service: script.turn_on
        entity_id: script.ganymede_restart
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          speak: "true"
          audio: "sinewave"
          light: "false"
          mobile: "false"
          title: 'Restarting Ganymede because Broadlink RM Mini is offline'
          message: 'Restarting Ganymede because Broadlink RM Mini is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: 'Bedroom Philips Hue offline restart'
    trigger:
      - platform: state
        entity_id: binary_sensor.moon
        from: 'on'
        to: 'off'
        for:
          minutes: 7
    action:
      - service: script.turn_on
        entity_id: script.ganymede_restart
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          speak: "true"
          audio: "sinewave"
          light: "false"
          mobile: "false"
          title: 'Restarting Ganymede because Philips Hue is offline'
          message: 'Restarting Ganymede because Philips Hue is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: 'Bedroom Neptune offline restart'
    trigger:
      - platform: state
        entity_id: binary_sensor.neptune
        from: 'on'
        to: 'off'
        for:
          minutes: 7
    action:
      - service: script.turn_on
        entity_id: script.ganymede_restart
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          speak: "true"
          audio: "sinewave"
          light: "false"
          mobile: "false"
          title: 'Restarting Ganymede because Neptune is offline'
          message: 'Restarting Ganymede because Neptune is offline [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
