binary_sensor:
  - platform: ping
    host: 192.168.1.1
    name: "Deeper"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.2
    name: "Pluto"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.3
    name: "Sun"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.4
    name: "Uranus"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.5
    name: "Neptune"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.6
    name: "Mercury"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.7
    name: "Apollo"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.8
    name: "Sputnik"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.10
    name: "Cookie"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.13
    name: "Candy"
    count: 2
    scan_interval: 30

  # - platform: ping
  #   host: 192.168.1.13
  #   name: "Broadlink RM Pro"
  - platform: ping
    host: 192.168.1.14
    name: "Broadlink RM Mini A"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.15
    name: "Broadlink RM Mini B"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.16
    name: "Doughnut"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.17
    name: "Biscuit"
    count: 2
    scan_interval: 30

  - platform: ping
    host: 192.168.1.18
    name: "Hyperion"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.19
    name: "Charon"
    count: 2
    scan_interval: 30

  - platform: ping
    host: 192.168.1.20
    name: "Titan"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.21
    name: "Europa"
    count: 2
    scan_interval: 30

  - platform: ping
    host: 192.168.1.22
    name: "Ganymede"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.23
    name: "Callisto"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.24
    name: "Mimas"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.25
    name: "Pandora"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.26
    name: "Phoebe"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.27
    name: "Calypso"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.28
    name: "SVA"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.29
    name: "SVB"
    count: 2
    scan_interval: 30

  - platform: ping
    host: 192.168.1.40
    name: "Moon"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.41
    name: "Wemos Lite Party"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.42
    name: "NodeMCU Matrix Clock"
    count: 2
    scan_interval: 30
  # - platform: ping
  #   host: 192.168.1.43
  #   name: ""
  #   count: 2
  #   scan_interval: 30
  - platform: ping
    host: 192.168.1.44
    name: "Earth"
    count: 2
    scan_interval: 30

  - platform: ping
    host: 192.168.1.46
    name: "Wemos PIR"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.47
    name: "Wemos BMW"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.48
    name: "Wemos Bluebird"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.49
    name: "Wemos Freed"
    count: 2
    scan_interval: 30
  # - platform: ping
  #   host: 192.168.1.51
  #   name: "Naked"
  #   count: 2
  #   scan_interval: 30
  # - platform: ping
  #   host: 192.168.1.52
  #   name: "Wemos B"
  #   count: 2
  #   scan_interval: 30

  - platform: ping
    host: 192.168.1.78
    name: "Foscam Black"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.79
    name: "Foscam White"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.80
    name: "Foscam R2"
    count: 2
    scan_interval: 30

counter:
  bedroom:
    name: "Bedroom Reboot Counts"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  commonroom:
    name: "Common Room Reboot Counts"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  firstfloor:
    name: "Frst Floor Reboot Counts"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false

group:
  online_cr:
    name: "Online Status Common Room"
    icon: mdi:lan-connect
    control: hidden
    entities:
      - binary_sensor.deeper
      - binary_sensor.apollo
      # - binary_sensor.higher
      - binary_sensor.pluto
      # - binary_sensor.broadlink_rm_pro
      - binary_sensor.broadlink_rm_mini_b
      - binary_sensor.foscam_r2
      - binary_sensor.foscam_black
      - binary_sensor.titan
      # - binary_sensor.hyperion
      - binary_sensor.ganymede
      - binary_sensor.mimas
      - binary_sensor.phoebe
      # - binary_sensor.sva
      # - binary_sensor.svb
      - binary_sensor.wemos_lite_party
      - binary_sensor.nodemcu_matrix_clock
      - binary_sensor.denon
      - binary_sensor.android_box
      - binary_sensor.biscuit
      - binary_sensor.candy
      - binary_sensor.apple_tv
      - binary_sensor.dune
      - binary_sensor.xdj_rx
  online_br:
    name: "Online Status Bedroom"
    icon: mdi:lan-connect
    control: hidden
    entities:
      - binary_sensor.neptune
      - binary_sensor.broadlink_rm_mini_a
      - binary_sensor.doughnut
      - binary_sensor.moon
      - binary_sensor.europa
      - binary_sensor.pandora
      - binary_sensor.hyperion
  online_ff:
    name: "Online Status First Floor"
    icon: mdi:lan-connect
    control: hidden
    entities:
      - binary_sensor.uranus
      - binary_sensor.mercury
      # - binary_sensor.sputnik
      - binary_sensor.foscam_white
      # - binary_sensor.wemos_bell
      - binary_sensor.earth
      - binary_sensor.charon
      - binary_sensor.callisto
      - binary_sensor.bmw
      - binary_sensor.pong
      - binary_sensor.freed

automation:

  - alias: 'Common Room Online Switch Restart'
    trigger:
      - platform: state
        entity_id: binary_sensor.foscam_black
        from: 'on'
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.foscam_r2
        from: 'on'
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.broadlink_rm_mini_b
        from: 'on'
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.candy
        from: 'on'
        to: 'off'
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: '{{ is_state("switch.ganymede", "on") and (is_state("binary_sensor.foscam_r2", "off") or is_state("binary_sensor.broadlink_rm_mini_b", "off") or is_state("binary_sensor.candy", "off")) }}'
    action:
       - service: script.turn_on
         entity_id: script.restart_ganymede
       - service: counter.increment
         entity_id: counter.commonroom

  # - alias: 'Common Room Online Switch Restart'
  #   trigger:
  #     - platform: time
  #       minutes: '/60'
  #       seconds: 00
  #     - condition: or
  #       conditions:
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.foscam_black", "off") }}'
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.foscam_r2", "off") }}'
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.broadlink_rm_mini_b", "off") }}'
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.candy", "off") }}'
  #   action:
  #      - service: script.turn_on
  #        entity_id: script.restart_ganymede
  #      - service: counter.increment
  #        entity_id: counter.commonroom

  - alias: 'Bedroom Online Switch Restart'
    trigger:
      - platform: state
        entity_id: binary_sensor.neptune
        from: 'on'
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.moon
        from: 'on'
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.broadlink_rm_mini_a
        from: 'on'
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.doughnut
        from: 'on'
        to: 'off'
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: '{{ is_state("switch.hyperion", "on") and (is_state("binary_sensor.moon", "off") or is_state("binary_sensor.broadlink_rm_mini_a", "off") or is_state("binary_sensor.doughnut", "off")) }}'
    action:
       - service: script.turn_on
         entity_id: script.restart_hyperion
       - service: counter.increment
         entity_id: counter.bedroom

  # - alias: 'Bedroom Online Switch Restart'
  #   trigger:
  #     - platform: time
  #       minutes: '/60'
  #       seconds: 00
  #   condition:
  #     - condition: or
  #       conditions:
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.broadlink_rm_mini_a", "off") }}'
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.neptune", "off") }}'
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.moon", "off") }}'
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.doughnut", "off") }}'
  #   action:
  #     - service: script.turn_on
  #       entity_id: script.restart_hyperion
  #     - service: counter.increment
  #       entity_id: counter.bedroom

  - alias: 'First Floor Online Switch Restart'
    trigger:
      - platform: state
        entity_id: binary_sensor.foscam_white
        from: 'on'
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.earth
        from: 'on'
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.uranus
        from: 'on'
        to: 'off'
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: '{{ is_state("switch.charon", "on") and (is_state("binary_sensor.foscam_white", "off") or is_state("binary_sensor.earth", "off") or is_state("binary_sensor.uranus", "off")) }}'
    action:
       - service: script.turn_on
         entity_id: script.restart_charon
       - service: counter.increment
         entity_id: counter.firstfloor

  # - alias: 'First Floor Online Switch Restart'
  #   trigger:
  #     - platform: time
  #       minutes: '/60'
  #       seconds: 00
  #   condition:
  #     - condition: or
  #       conditions:
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.foscam_white", "off") }}'
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.earth", "off") }}'
  #         - condition: template
  #           value_template: '{{ is_state("binary_sensor.foscam_white", "off") }}'
  #         # - condition: template
  #         #   value_template: '{{ is_state("binary_sensor.mercury", "off") }}'
  #   action:
  #     - service: script.turn_on
  #       entity_id: script.restart_charon
  #     - service: counter.increment
  #       entity_id: counter.firstfloor

  - alias: "Car Online"
    trigger:
      - platform: state
        entity_id: binary_sensor.bmw
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.pong
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.freed
        from: 'off'
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ is_state("light.warm_garage", "off") and is_state("sun.sun", "below_horizon") }}'
    action:
      - service: light.turn_on
        entity_id: light.warm_garage
      - service: script.notifying
        data_template:
          email: "false"
          tv: "true"
          line: "false"
          speak: "true"
          audio: "chime"
          light: "false"
          mobile: "false"
          message: 'Turn off Garage light because {{ trigger.from_state.attributes.friendly_name }} has gone online'

  - alias: "Car Offline"
    trigger:
      - platform: state
        entity_id: binary_sensor.bmw
        from: 'on'
        to: 'off'
        for:
          minutes: 1
      - platform: state
        entity_id: binary_sensor.pong
        from: 'on'
        to: 'off'
        for:
          minutes: 1
      - platform: state
        entity_id: binary_sensor.freed
        from: 'on'
        to: 'off'
        for:
          minutes: 1
    condition:
      - condition: template
        value_template: '{{ is_state("light.warm_garage", "on") }}'
    action:
      - service: light.turn_off
        entity_id: light.warm_garage
      - service: script.notifying
        data_template:
          email: "false"
          tv: "true"
          line: "false"
          speak: "true"
          audio: "chime"
          light: "false"
          mobile: "false"
          message: 'Turn off Garage light because {{ trigger.from_state.attributes.friendly_name }} has gone offline'
