binary_sensor:
  - platform: ping
    host: 192.168.1.1
    name: "Deeper"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.2
    name: "Pluto"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.3
    name: "Sun"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.4
    name: "Uranus"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.5
    name: "Neptune"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.6
    name: "Mercury"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.7
    name: "Apollo"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.8
    name: "Sputnik"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.12
    name: "Biscuit"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.13
    name: "Candy"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.14
    name: "Doughnut"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.15
    name: "Broadlink RM Mini A"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.16
    name: "Broadlink RM Mini B"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.17
    name: "Broadlink RM Mini C"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.18
    name: "Hyperion"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.19
    name: "Charon"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.120
    name: "Titan"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.121
    name: "Europa"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.22
    name: "Ganymede"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.23
    name: "Callisto"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.24
    name: "Mimas"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.25
    name: "Pandora"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.26
    name: "Phoebe"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.27
    name: "Calypso"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.28
    name: "SVA"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.29
    name: "SVB"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.30
    name: "pesiphone7plus"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.31
    name: "pesipadmini5"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.32
    name: "juesiphone6splus"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.33
    name: "juesipadmini4"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.34
    name: "pesipodtouch4"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.36
    name: "benjysiphone6"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.37
    name: "benjawan"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.38
    name: "benjysipadmini2"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.39
    name: "boom"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.40
    name: "Moon"
    count: 2
    scan_interval: 120
  # - platform: ping
  #   host: 192.168.1.41
  #   name: "Wemos Lite Party"
  #   count: 2
  #   scan_interval: 120
  - platform: ping
    host: 192.168.1.42
    name: "NodeMCU Matrix Clock"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.43
    name: "Wemos Ring Clock"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.44
    name: "Earth"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.46
    name: "Comet"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.52
    name: "Wemos ButtonBox"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.61
    name: "Wemos WLED RC"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.62
    name: "Wemos WLED B"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.63
    name: "Wemos WLED C"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.64
    name: "Wemos WLED D"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.65
    name: "Wemos WLED Party"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.66
    name: "Denon"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.67
    name: "Downlight Black1"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.68
    name: "Downlight Black2"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.69
    name: "Downlight Black3"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.70
    name: "Downlight Black4"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.71
    name: "Wemos WLED E"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.72
    name: "Smart Dimmer"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.73
    name: "Downlight Black4"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.74
    name: "Downlight Black6"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.75
    name: "Downlight Black7"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.76
    name: "Downlight Black8"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.77
    name: "Dune"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.78
    name: "Foscam Black"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.79
    name: "Foscam White"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.80
    name: "Foscam R2"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.81
    name: "Boxie B1"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.82
    name: "Boxie B2"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.83
    name: "ESP32 Cam"
    count: 2
    scan_interval: 120
  - platform: ping
    host: 192.168.1.200
    name: "pepe"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.202
    name: "pepework"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.1.250
    name: "sinbad"
    count: 2
    scan_interval: 30

input_boolean:
  presence_xdj_rx:
    name: "XDJ-RX online"
    initial: off
    icon: mdi:music

counter:
  bedroom:
    name: "Bedroom Reboot Counts"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  commonroom:
    name: "Common Room Reboot Counts"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  firstfloor:
    name: "Frst Floor Reboot Counts"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  workstation:
    name: "WorkStation Reboot Counts"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false
  camera:
    name: "Camera Reboot Counts"
    initial: 0
    step: 1
    icon: mdi:counter
    restore: false

group:
  online_cr:
    name: "Online Status Common Room"
    icon: mdi:lan-connect
    control: hidden
    view: false
    entities:
      - binary_sensor.deeper
      - binary_sensor.apollo
      - binary_sensor.pluto
      - binary_sensor.broadlink_rm_mini_b
      - binary_sensor.boxie_b2
      - binary_sensor.esp32_cam
      - binary_sensor.candy
      - binary_sensor.moon
      - binary_sensor.titan
      - binary_sensor.ganymede
      - binary_sensor.callisto
      - binary_sensor.mimas
      - binary_sensor.sva
      - binary_sensor.nodemcu_matrix_clock
      - binary_sensor.wemos_ring_clock
      - binary_sensor.wemos_wled_rc
      - binary_sensor.wemos_wled_b
      - binary_sensor.wemos_wled_c
      - binary_sensor.wemos_wled_d
      - binary_sensor.wemos_wled_e
      - binary_sensor.wemos_wled_party
      - binary_sensor.denon
      - binary_sensor.android_box
      - binary_sensor.biscuit
      - binary_sensor.apple_tv
      - binary_sensor.dune
      - binary_sensor.xdj_rx
  online_br:
    name: "Online Status Bedroom"
    icon: mdi:lan-connect
    view: false
    control: hidden
    entities:
      - binary_sensor.neptune
      - binary_sensor.broadlink_rm_mini_a
      - binary_sensor.doughnut
      - binary_sensor.europa
      - binary_sensor.pandora
      - binary_sensor.hyperion
      - binary_sensor.wemos_buttonbox
  online_ff:
    name: "Online Status First Floor"
    icon: mdi:lan-connect
    view: false
    control: hidden
    entities:
      - binary_sensor.uranus
      - binary_sensor.broadlink_rm_mini_c
      - binary_sensor.boxie_b1
      - binary_sensor.foscam_white
      - binary_sensor.earth
      - binary_sensor.svb
      - binary_sensor.phoebe
      - binary_sensor.calypso
      - binary_sensor.comet
      - binary_sensor.bmw
      - binary_sensor.pong
      - binary_sensor.freed

automation:

  - alias: 'Camera Online Switch Restart'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.foscam_r2, binary_sensor.broadlink_rm_mini_b
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: '{% if state_attr("automation.camera_online_switch_restart", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.camera_online_switch_restart.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.camera_online_switch_restart", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: script.turn_on
        entity_id: script.restart_ganymede
      - service: counter.increment
        entity_id: counter.camera
      - service: script.notifying
        data_template:
          email: "false"
          tv: "false"
          line: "false"
          speak: "true"
          audio: "false"
          light: "false"
          mobile: "pe"
          title: "Restarting Camera Online Switch (Ganymede)"
          message: 'Camera Online Switch (Ganymede) was restarted because {{ trigger.from_state.attributes.friendly_name }} was detected as being {{ trigger.to_state.state }}line for 5 minutes'

  - alias: 'ESP32 Camera Online Switch Restart'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.esp32_cam
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: '{% if state_attr("automation.esp32_camera_online_switch_restart", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.esp32_camera_online_switch_restart.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.esp32_camera_online_switch_restart", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: script.turn_on
        entity_id: script.restart_sva
      # - service: counter.increment
      #   entity_id: counter.camera
      - service: script.notifying
        data_template:
          email: "false"
          tv: "false"
          line: "false"
          speak: "true"
          audio: "false"
          light: "false"
          mobile: "pe"
          title: "Restarting ESP32 Camera Online Switch (SVA)"
          message: 'ESP32 Camera Online Switch (SVA) was restarted because {{ trigger.from_state.attributes.friendly_name }} was detected as being {{ trigger.to_state.state }}line for 5 minutes'

  - alias: 'Common Room Online Switch Restart'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.candy
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: '{% if state_attr("automation.common_room_online_switch_restart", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.common_room_online_switch_restart.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.common_room_online_switch_restart", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: script.turn_on
        entity_id: script.restart_callisto
      - service: counter.increment
        entity_id: counter.commonroom
      - service: script.notifying
        data_template:
          email: "false"
          tv: "false"
          line: "false"
          speak: "true"
          audio: "false"
          light: "false"
          mobile: "pe"
          title: "Restarting Common Room online switch (Callisto)"
          message: 'Common Room Online Switch (Phoebe) was restarted because {{ trigger.from_state.attributes.friendly_name }} was detected as being {{ trigger.to_state.state }}line for 5 minutes'

  - alias: 'Bedroom Online Switch Restart'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.neptune, binary_sensor.broadlink_rm_mini_a, binary_sensor.doughnut
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: '{% if state_attr("automation.bedroom_online_switch_restart", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.bedroom_online_switch_restart.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.bedroom_online_switch_restart", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: script.turn_on
        entity_id: script.restart_hyperion
      - service: counter.increment
        entity_id: counter.bedroom
      - service: script.notifying
        data_template:
          email: "false"
          tv: "false"
          line: "false"
          speak: "true"
          audio: "false"
          light: "false"
          mobile: "pe"
          title: "Restarting Bedroom online switch (Hyperion)"
          message: 'Bedroom Online Switch (Hyperion) was restarted because {{ trigger.from_state.attributes.friendly_name }} was detected as being {{ trigger.to_state.state }}line for 5 minutes'

  - alias: 'First Floor Online Switch Restart'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.uranus, binary_sensor.boxie
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: template
        value_template: '{% if state_attr("automation.first_floor_online_switch_restart", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.first_floor_online_switch_restart.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.first_floor_online_switch_restart", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: script.turn_on
        entity_id: script.restart_phoebe
      - service: counter.increment
        entity_id: counter.firstfloor
      - service: script.notifying
        data_template:
          email: "false"
          tv: "false"
          line: "false"
          speak: "true"
          audio: "false"
          light: "false"
          mobile: "pe"
          title: "Restarting First Floor online switch (Phoebe)"
          message: 'First Floor Online Switch (Phoebe) was restarted because {{ trigger.from_state.attributes.friendly_name }} was detected as being {{ trigger.to_state.state }}line for 5 minutes'

  - alias: "Car Online"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bmw, binary_sensor.pong, binary_sensor.freed
        from: 'off'
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ is_state("light.white_garage", "off") and is_state("sun.sun", "below_horizon") }}'
    action:
      - service: light.turn_on
        entity_id: light.white_garage
      - service: script.notifying
        data_template:
          email: "false"
          tv: "false"
          line: "false"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "pe"
          message: 'Turn on {{ trigger.to_state.attributes.friendly_name }} because {{ trigger.from_state.attributes.friendly_name }} gets online'

  - alias: "Car Offline"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bmw, binary_sensor.pong, binary_sensor.freed
        from: 'on'
        to: 'off'
        for:
          minutes: 1
    condition:
      - condition: template
        value_template: '{{ is_state("light.white_garage", "on") }}'
    action:
      - service: light.turn_off
        entity_id: light.white_garage
      - service: script.notifying
        data_template:
          email: "false"
          tv: "false"
          line: "false"
          speak: "false"
          audio: "chime"
          light: "false"
          mobile: "pe"
          message: 'Turn off {{ trigger.to_state.attributes.friendly_name }} because {{ trigger.from_state.attributes.friendly_name }} has gone offline'

  - alias: "XDJ-RX is online"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ is_state("device_tracker.ping_xdj_rx", "home") and is_state("binary_sensor.xdj_rx", "on") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.presence_xdj_rx", "off")  }}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.presence_xdj_rx

  - alias: "XDJ-RX is offline"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ is_state("device_tracker.ping_xdj_rx", "not_home") and is_state("binary_sensor.xdj_rx", "off") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.presence_xdj_rx", "on") }}'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.presence_xdj_rx

  - alias: "XDJ-RX is on"
    trigger:
      - platform: state
        entity_id: input_boolean.presence_xdj_rx
        from: 'off'
        to: 'on'
        for:
          minutes: 1
          seconds: 30
    condition:
      - condition: template
        value_template: '{{ is_state("binary_sensor.xdj_rx", "on") }}'
    action:
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          line: "true"
          speak: "true"
          audio: "pip"
          light: "false"
          mobile: "pe"
          message: "XDJ-RX has been turned on!"

  - alias: "XDJ-RX is off"
    trigger:
      - platform: state
        entity_id: input_boolean.presence_xdj_rx
        from: 'on'
        to: 'off'
        for:
          minutes: 1
          seconds: 30
    condition:
      - condition: template
        value_template: '{{ is_state("binary_sensor.xdj_rx", "off") }}'
    action:
      - service: script.notifying
        data_template:
          email: "true"
          tv: "true"
          line: "true"
          speak: "true"
          audio: "pip"
          light: "false"
          mobile: "pe"
          message: "XDJ-RX has been turned off!"
