input_boolean:

  presence_pe:
    name: "Pe at Home"
    initial: off
    icon: mdi:duck

  presence_jue:
    name: "Jue at Home"
    initial: off
    icon: mdi:owl

automation:

  - alias: 'Pe is away'
    trigger:
      - platform: template
        value_template: "{% if is_state('device_tracker.pesiphone6', 'not_home') %}true{% else %}false{% endif %}"
      - platform: numeric_state
        entity_id: proximity.pe_home
        above: 500
    condition:
      - condition: state
        entity_id: input_boolean.presence_pe
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.presence_pe

  - alias: 'Pe is home'
    trigger:
      - platform: template
        value_template: "{% if is_state('device_tracker.pesiphone6', 'home') %}true{% else %}false{% endif %}"
      - platform: numeric_state
        entity_id: proximity.pe_home
        below: 10
    condition:
      - condition: state
        entity_id: input_boolean.presence_pe
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.presence_pe

  - alias: Pe Arrival Notification
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'not_home'
        to: 'home'
    action:
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe has arrived home"
          message: 'เป้กลับถึงบ้าน [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.flashing_short
        data:
          title: "Pe has arrived home"
          message: 'Pe has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: Pe Departure Notification
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'home'
        to: 'not_home'
    action:
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe has left home"
          message: 'เป้ออกจากบ้าน [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.flashing_long
        data:
          title: "Pe has left home"
          message: 'Pe has left home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: 'Jue is away'
    trigger:
      - platform: template
        value_template: "{% if is_state('device_tracker.juesiphone6splus', 'not_home') %}true{% else %}false{% endif %}"
      - platform: numeric_state
        entity_id: proximity.jue_home
        above: 500
    condition:
      - condition: state
        entity_id: input_boolean.presence_jue
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.presence_jue

  - alias: 'Jue is home'
    trigger:
      - platform: template
        value_template: "{% if is_state('device_tracker.juesiphone6splus', 'home') %}true{% else %}false{% endif %}"
      - platform: numeric_state
        entity_id: proximity.jue_home
        below: 10
    condition:
      - condition: state
        entity_id: input_boolean.presence_jue
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.presence_jue

  - alias: Jue Arrival Notification
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'not_home'
        to: 'home'
    action:
      - service: script.notify_pesiphone6
        data:
          title: "Jue has arrived home"
          message: 'Jue has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.flashing_short
        data:
          title: "Jue has arrived home"
          message: 'Jue has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

  - alias: Jue Departure Notification
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'home'
        to: 'not_home'
    action:
      - service: script.notify_pesiphone6
        data:
          title: "Jue has left home"
          message: 'Jue has left home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.flashing_long
        data:
          title: "Jue has left home"
          message: 'Jue has left home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
