# shell_command:
#   wag160n_reboot: !secret wag160n_reboot

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

sensor:
  - platform: synologydsm
    # name: Saturn
    host: !secret synology_ip
    username: !secret my_username
    password: !secret my_longer_password
    monitored_conditions:
      - disk_temp
      - cpu_total_load
      - memory_real_usage
      - network_up
  - platform: syncthru
    resource: !secret earth_ip
    name: "Earth"
    monitored_conditions:
        - toner_black
        - drum_black
        - output_tray_0
        - tray_1
group:
  home_server:
    name: "Home Server"
    icon: mdi:server-security
    view: false
    control: hidden
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - input_boolean.mpd_silence
      - input_text.clear_mqtt_topic
  printer:
    name: "Earth"
    icon: mdi:printer
    view: false
    control: hidden
    entities:
      - sensor.samsung_m267x_287x_series_192168144
      - sensor.samsung_m267x_287x_series_192168144_toner_black
      - sensor.samsung_m267x_287x_series_192168144_drum_black
      - sensor.samsung_m267x_287x_series_192168144_output_tray_0
      - sensor.samsung_m267x_287x_series_192168144_tray_1

input_text:
  clear_mqtt_topic:
    name: "MQTT Topic to Clear"
    mode: text
    initial: ''

automation:

  - alias: "Let's Encrypt Renewal"
    initial_state: 'on'
    trigger:
      - platform: time
        at: '00:00:00'
    action:
      - service: hassio.addon_restart
        data:
          addon: core_letsencrypt

  - alias: "Clear MQTT Topics"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_text.clear_mqtt_topic
    condition:
      - condition: template
        value_template: "{{ 'homeassistant/sensor/' in states.input_text.clear_mqtt_topic.state }}"
    action:
      - service: mqtt.publish
        data_template:
          topic: "{{ states.input_text.clear_mqtt_topic.state }}"
          retain: true
