# shell_command:
#   wag160n_reboot: !secret wag160n_reboot

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

sensor:
  - platform: synologydsm
    # name: Saturn
    host: !secret synology2_ip
    username: !secret my_username
    password: !secret my_longer_password
    monitored_conditions:
      - disk_temp
      - cpu_total_load
      - memory_real_usage
      - network_up

group:
  home_server:
    name: "Home Server"
    icon: mdi:server-security
    control: hidden
    view: false
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
  printer:
    name: "Earth"
    icon: mdi:printer
    control: hidden
    view: false
    entities:
      - sensor.samsung_m267x_287x_series_192_168_1_44
      - sensor.samsung_m267x_287x_series_192_168_1_44_toner_black
      - sensor.samsung_m267x_287x_series_192_168_1_44_drum_black
      - sensor.samsung_m267x_287x_series_192_168_1_44_output_tray_0
      - sensor.samsung_m267x_287x_series_192_168_1_44_tray_1
  deeper:
    name: "Deeper"
    icon: mdi:server-network
    control: hidden
    view: false
    entities:
      - sensor.deeper_router_bytes_received
      - sensor.deeper_router_bytes_sent
      - sensor.deeper_router_kbyte_sec_received
      - sensor.deeper_router_kbyte_sec_sent
      # - sensor.deeper_router_packets_received
      # - sensor.deeper_router_packets_sent
      # - sensor.deeper_router_packets_sec_received
      # - sensor.deeper_router_packets_sec_sent
  glances:
    name: "Jupiter"
    icon: mdi:server-network
    control: hidden
    view: false
    entities:
      - sensor.glances_ram_used
      - sensor.glances_containers_ram_used
      - sensor.glances_thread
      - sensor.glances_cpu_temp
      - sensor.glances_sleeping
      - sensor.glances_disk_used
      - sensor.glances_disk_free
      - sensor.glances_ram_used_percent
      - sensor.glances_swap_used
      - sensor.glances_swap_free
      - sensor.glances_cpu_used
      - sensor.glances_running
      - sensor.glances_containers_active
      - sensor.glances_total
      - sensor.glances_disk_used_percent
      - sensor.glances_containers_cpu_used
      - sensor.glances_cpu_load
      - sensor.glances_ram_free
      - sensor.glances_swap_used_percent

