# shell_command:
#   wag160n_reboot: !secret wag160n_reboot

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

sensor:
  - platform: min_max
    entity_ids:
      - sensor.calypso_am2301_temperature
      - sensor.ganymede_am2301_temperature
      - sensor.hyperion_am2301_temperature
  - platform: synologydsm
    # name: Saturn
    host: !secret synology2_ip
    username: !secret my_username
    password: !secret my_longer_password
    monitored_conditions:
      - disk_temp
      - cpu_total_load
      - memory_real_usage
      - network_up

group:
  printer:
    name: "Earth"
    icon: mdi:printer
    entities:
      - sensor.samsung_m267x_287x_series_192_168_1_44
      - sensor.samsung_m267x_287x_series_192_168_1_44_toner_black
      - sensor.samsung_m267x_287x_series_192_168_1_44_drum_black
      - sensor.samsung_m267x_287x_series_192_168_1_44_output_tray_0
      - sensor.samsung_m267x_287x_series_192_168_1_44_tray_1
  glances:
    name: "Jupiter"
    icon: mdi:server-network
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.glances_ram_used
      - sensor.glances_containers_ram_used
      - sensor.glances_thread
      - sensor.glances_cpu_temp
      - sensor.glances_sleeping
      - sensor.glances_disk_used
      - sensor.glances_disk_free
      - sensor.glances_ram_used_percent
      - sensor.glances_swap_used
      - sensor.glances_swap_free
      - sensor.glances_cpu_used
      - sensor.glances_running
      - sensor.glances_containers_active
      - sensor.glances_total
      - sensor.glances_disk_used_percent
      - sensor.glances_containers_cpu_used
      - sensor.glances_cpu_load
      - sensor.glances_ram_free
      - sensor.glances_swap_used_percent

