# binary_sensor:
#   - platform: command_line
#     command: '/bin/ping -W 1 -c 1 8.8.8.8 > /dev/null 2>&1 && echo success || echo fail'
#     name: 'Internet'
#     device_class: connectivity
#     payload_on: 'success'
#     payload_off: 'fail'

# shell_command:
#   db_events: !secret db_events
#   db_states: !secret db_states
#   db_recorder_runs: !secret db_recorder_runs
#   db_schema_changes: !secret db_schema_changes

sensor:
  - platform: synologydsm
    name: Saturn
    host: !secret synology_ip
    username: !secret my_username
    password: !secret my_longer_password
    monitored_conditions:
      - disk_temp
  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: since_last_boot
      - type: processor_use
      - type: memory_use_percent
  - platform: speedtest
    minute:
      - 0
      - 10
      - 20
      - 30
      - 40
      - 50
    monitored_conditions:
      - download
      - upload
  # - platform: command_line
  #   command: !secret db_events
  #   name: "DB Events"
  # - platform: command_line
  #   command: !secret db_states
  #   name: "DB States"
  # - platform: command_line
  #   command: !secret db_recorder_runs
  #   name: "DB Recorder Runs"
  # - platform: command_line
  #   command: !secret db_schema_changes
  #   name: "DB Schema Changes"
  - platform: template
    sensors:
      uptime:
        friendly_name: Uptime
        icon_template: mdi:timelapse
        value_template: >-
          {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
          {%- set count = slb | length -%}
          {%- set hms = slb[count - 1] -%}
          {%- set hms_trimmed = hms.split('.')[0] -%}
          {%- set hms_split = hms_trimmed.split(':') -%}
          {%- set hours = hms_split[0] | int -%}
          {%- if count == 3 -%}
            {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
          {%- endif -%}

# automation:
#
#   - alias: "Internet is down"
#     # hide_entity: True
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.internet
#         to: 'off'
#     action:
#       - service: script.notifying
#         data:
#           title: "The Internet is down"
#           message: 'The Internet is down [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
