# switch:
  # - platform: mqtt
  #   name: "Ganymede"
  #   state_topic: "stat/ganymede/POWER"
  #   command_topic: "cmnd/ganymede/POWER"
  #   availability_topic: "tele/ganymede/LWT"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: 758b4c1a-943d-45b6-ab58-24a41a357cc2
  # - platform: mqtt
  #   name: "Calypso"
  #   state_topic: "stat/calypso/POWER"
  #   command_topic: "cmnd/calypso/POWER"
  #   availability_topic: "tele/calypso/LWT"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: f92b1ce3-3cd8-4f0c-8b0e-d7f5201c8084
  # - platform: mqtt
  #   name: "Mimas"
  #   state_topic: "stat/mimas/POWER"
  #   command_topic: "cmnd/mimas/POWER"
  #   availability_topic: "tele/mimas/LWT"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: 35cad35f-4f70-49fa-9c3c-ac8c84791ba4
  # - platform: mqtt
  #   name: "Charon"
  #   state_topic: "stat/charon/POWER"
  #   command_topic: "cmnd/charon/POWER"
  #   availability_topic: "tele/charon/LWT"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: f8ce62d8-0a9f-4af6-9b7d-369910fd1472
  # - platform: mqtt
  #   name: "Hyperion"
  #   state_topic: "stat/hyperion/POWER"
  #   command_topic: "cmnd/hyperion/POWER"
  #   availability_topic: "tele/hyperion/LWT"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: d5e177a9-f336-4b13-8608-480b15e66518
  # - platform: mqtt
  #   name: "Callisto"
  #   state_topic: "stat/callisto/POWER"
  #   command_topic: "cmnd/callisto/POWER"
  #   availability_topic: "tele/callisto/LWT"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: e216ff53-ad8b-4c2d-8acc-aabe35f4329c
  # - platform: mqtt
  #   name: "SVA1"
  #   state_topic: "stat/sva/POWER1"
  #   command_topic: "cmnd/sva/POWER1"
  #   availability_topic: "tele/sva/LWT"
  #   payload_on: "ON"
  #   payload_off: "OFF"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: 3c95ae74-31a1-43b6-8a42-40198326207c
  # - platform: mqtt
  #   name: "SVA2"
  #   state_topic: "stat/sva/POWER2"
  #   command_topic: "cmnd/sva/POWER2"
  #   availability_topic: "tele/sva/LWT"
  #   payload_on: "ON"
  #   payload_off: "OFF"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: c1efe643-46d6-4087-9171-b7997818d11c

# light:
  # - platform: mqtt
  #   name: "Pandora"
  #   state_topic: "tele/pandora/STATE"
  #   value_template: "{{ value_json.POWER }}"
  #   command_topic: "cmnd/pandora/POWER"
  #   availability_topic: "tele/pandora/LWT"
  #   payload_on: "ON"
  #   payload_off: "OFF"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: 9f398da5-7908-4254-8c1c-548629e45e5a
  # - platform: mqtt
  #   name: "Phoebe"
  #   state_topic: "tele/phoebe/STATE"
  #   value_template: "{{ value_json.POWER }}"
  #   command_topic: "cmnd/phoebe/POWER"
  #   availability_topic: "tele/phoebe/LWT"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   qos: 1
  #   retain: true
  #   optimistic: true
  #   unique_id: 3ae0dad4-400d-45c1-8364-cb69c15f4876

input_boolean:
  motion_detected:
    name: Motion Detected
    initial: off

binary_sensor:
  - platform: mqtt
    name: "Front Door"
    state_topic: "cmnd/frontdoor/POWER"
    payload_on: "OFF"
    payload_off: "ON"
    device_class: door
    qos: 1
    # retain: true
    # optimistic: true
    unique_id: a2c81956-bdcd-4b00-8bad-977d3bce825b
  - platform: mqtt
    name: "Window"
    state_topic: "cmnd/window/POWER"
    payload_on: "OFF"
    payload_off: "ON"
    device_class: window
    qos: 1
    # retain: true
    # optimistic: true
    unique_id: 9f398da5-7908-4254-8c1c-548629e45e5a
  - platform: mqtt
    state_topic: "cmnd/calypso_pir/POWER"
    name: "Calypso PIR"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: motion
    qos: 1
    # retain: true
    # optimistic: true

switch:
  - platform: mqtt
    name: "Front Door"
    command_topic: "cmnd/frontdoor/POWER"
    state_topic: "stat/frontdoor/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    # retain: true
  - platform: mqtt
    name: "Window"
    command_topic: "cmnd/wemos/POWER"
    state_topic: "stat/wemos/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    # retain: true

sensor:
  # - platform: mqtt
  #   name: "Ganymede Energy Today"
  #   state_topic: "tele/ganymede/SENSOR"
  #   value_template: "{{ value_json.ENERGY.Today | round(1) }}"
  #   unit_of_measurement: "kWh"
  #   # device_class: none
  # - platform: mqtt
  #   name: "Ganymede Energy Yesterday"
  #   state_topic: "tele/ganymede/SENSOR"
  #   value_template: "{{ value_json.ENERGY.Yesterday | round(1) }}"
  #   unit_of_measurement: "kWh"
  #   # device_class: none
  # - platform: mqtt
  #   name: "Ganymede Energy Total"
  #   state_topic: "tele/ganymede/SENSOR"
  #   value_template: "{{ value_json.ENERGY.Total | round(1) }}"
  #   unit_of_measurement: "kWh"
  #   # device_class: none
  # - platform: mqtt
  #   name: "Ganymede Power"
  #   state_topic: "tele/ganymede/SENSOR"
  #   value_template: "{{ value_json.ENERGY.Power | round(1) }}"
  #   unit_of_measurement: "Watts"
  #   # device_class: none
  # - platform: mqtt
  #   name: "Ganymede Power Factor"
  #   state_topic: "tele/ganymede/SENSOR"
  #   value_template: "{{ value_json.StatusPWR.Factor | round(2) }}"
  #   # device_class: none
  # - platform: mqtt
  #   name: "Ganymede Current"
  #   state_topic: "tele/ganymede/SENSOR"
  #   value_template: "{{ value_json.ENERGY.Current | round(2) }}"
  #   unit_of_measurement: "Amps"
  #   # device_class: none
  # - platform: mqtt
  #   name: "Ganymede Voltage"
  #   state_topic: "tele/ganymede/SENSOR"
  #   value_template: "{{ value_json.ENERGY.Voltage | round(0) }}"
  #   unit_of_measurement: "Volts"
  #   # device_class: none
  - platform: mqtt
    name: "Ganymede Energy"
    state_topic: "tele/ganymede/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] | round(1) }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Ganymede Power"
    state_topic: "tele/ganymede/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] | round(1) }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Ganymede Voltage"
    state_topic: "tele/ganymede/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] | round(0) }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Ganymede Current"
    state_topic: "tele/ganymede/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] | round(2) }}'
    unit_of_measurement: "A"
  # - platform: mqtt
  #   name: "First Floor Temperature"
  #   state_topic: "tele/callisto/SENSOR"
  #   value_template: "{{ value_json['AM2301'].Temperature }}"
  #   unit_of_measurement: "°C"
  #   device_class: temperature
  #   availability_topic: "tele/callisto/LWT"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  # - platform: statistics
  #   entity_id: sensor.callisto_temperature
  #   name: "First Floor Temperature"
  - platform: mqtt
    name: "First Floor Temperature"
    state_topic: "tele/callisto/SENSOR"
    value_template: "{{ value_json['AM2301'].Temperature }}"
    unit_of_measurement: "°C"
    device_class: temperature
    availability_topic: "tele/callisto/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "First Floor Humidity"
    state_topic: "tele/callisto/SENSOR"
    value_template: "{{ value_json['AM2301'].Humidity }}"
    unit_of_measurement: "%"
    device_class: humidity
    availability_topic: "tele/callisto/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Common Room Temperature"
    state_topic: "tele/mimas/SENSOR"
    value_template: "{{ value_json['AM2301'].Temperature }}"
    unit_of_measurement: "°C"
    device_class: temperature
    availability_topic: "tele/mimas/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Common Room Humidity"
    state_topic: "tele/mimas/SENSOR"
    value_template: "{{ value_json['AM2301'].Humidity }}"
    unit_of_measurement: "%"
    device_class: humidity
    availability_topic: "tele/mimas/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Bedroom Temperature"
    state_topic: "tele/pandora/SENSOR"
    value_template: "{{ value_json['AM2301'].Temperature }}"
    unit_of_measurement: "°C"
    device_class: temperature
    availability_topic: "tele/pandora/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Bedroom Humidity"
    state_topic: "tele/pandora/SENSOR"
    value_template: "{{ value_json['AM2301'].Humidity }}"
    unit_of_measurement: "%"
    device_class: humidity
    availability_topic: "tele/pandora/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  # - platform: mqtt
  #   name: "Common Room Temperature"
  #   state_topic: "tele/mimas/SENSOR"
  #   value_template: "{{ value_json.StatusSNS.AM2301.Temperature }}"
  #   unit_of_measurement: "°C"
  #   device_class: temperature
  # - platform: mqtt
  #   name: "Common Room Humidity"
  #   state_topic: "tele/mimas/SENSOR"
  #   value_template: "{{ value_json.StatusSNS.AM2301.Humidity }}"
  #   unit_of_measurement: "%"
  #   device_class: humidity
  # - platform: mqtt
  #   name: "Bedroom Temperature"
  #   state_topic: "tele/pandora/SENSOR"
  #   value_template: "{{ value_json.StatusSNS.AM2301.Temperature }}"
  #   unit_of_measurement: "°C"
  #   device_class: temperature
  # - platform: mqtt
  #   name: "Bedroom Humidity"
  #   state_topic: "tele/pandora/SENSOR"
  #   value_template: "{{ value_json.StatusSNS.AM2301.Humidity }}"
  #   unit_of_measurement: "%"
  #   device_class: humidity

group:
  sonoff:
    name: "Sonoff"
    icon: mdi:power-plug
    view: false
    control: hidden
    entities:
      - switch.ganymede
      - switch.phoebe
      - switch.charon
      - switch.hyperion
      - switch.callisto
      - switch.mimas
      - switch.pandora
      - switch.calypso
      - switch.svb
      - switfch.phoebe
      - switch.front_door
      - switch.wemos
      - switch.window

automation:

  - alias: "Enable MQTT discovery for all devices"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/bedroom/SetOption19"
          payload: "1"
      - service: mqtt.publish
        data:
          topic: "cmnd/firstfloor/SetOption19"
          payload: "1"
      - service: mqtt.publish
        data:
          topic: "cmnd/commmonroom/SetOption19"
          payload: "1"

  - alias: "Sync Power State on HA start-up"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/bedroom/STATE"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "cmnd/firstfloor/STATE"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "cmnd/commmonroom/STATE"
          payload: ""

  - alias: "3-way switch 1A"
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: 'off'
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.svb

  - alias: "3-way switch 1B"
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.svb

  - alias: "Calypso Motion Detecter"
    trigger:
      - platform: state
        entity_id: binary_sensor.calypso_pir
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.calypso_pir
        from: 'on'
        to: 'off'
        for:
          minutes: 5
          seconds: 00
    action:
      service_template: '{% if trigger.to_state.state == "on" %}input_boolean.turn_on{% elif trigger.to_state.state == "off" %}input_boolean.turn_off{% endif %}'
      entity_id: input_boolean.motion_detected
### RULES ###
# backlog switchmode1 0
# rule1 on button1#state=1 do publish cmnd/svb/power toggle endon on button1#state=2 do publish cmnd/svb/power toggle endon on button1#state=3 do publish cmnd/svb/power toggle endon
# rule1 on
# rule2 on switch1#state=1 do publish cmnd/floodlight/power toggle endon on switch1#state=2 do publish cmnd/floodlight/power toggle endon on switch1#state=3 do publish cmnd/floodlight/power toggle endon
# rule2 on
# rule 3on INA219#Current>0.100 do Backlog Dimmer 10;Color 10,0,0 endon
# rule1 on switch1#state=1 do publish cmnd/svb/power ON endon on switch1#state=2 do publish cmnd/svb/power OFF endon
# rule2 on button1#state do publish cmnd/svb/power %value% endon
