switch:
  - platform: mqtt
    name: "Ganymede"
    state_topic: "stat/ganymede/POWER"
    command_topic: "cmnd/ganymede/POWER"
    availability_topic: "tele/ganymede/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
    optimistic: true
  - platform: mqtt
    name: "Callisto"
    state_topic: "stat/callisto/POWER"
    command_topic: "cmnd/callisto/POWER"
    availability_topic: "tele/callisto/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
    optimistic: true
  - platform: mqtt
    name: "Mimas"
    state_topic: "stat/mimas/POWER"
    command_topic: "cmnd/mimas/POWER"
    availability_topic: "tele/mimas/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
    optimistic: true
  - platform: mqtt
    name: "Calypso"
    state_topic: "stat/calypso/POWER"
    command_topic: "cmnd/calypso/POWER"
    availability_topic: "tele/calypso/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
    optimistic: true
  - platform: mqtt
    name: "SVA"
    state_topic: "stat/sva/POWER"
    command_topic: "cmnd/sva/POWER"
    availability_topic: "tele/sva/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
    optimistic: true
  - platform: mqtt
    name: "SVB"
    state_topic: "stat/svb/POWER"
    command_topic: "cmnd/svb/POWER"
    availability_topic: "tele/svb/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
    optimistic: true

light:
  - platform: mqtt
    name: "Pandora"
    state_topic: "stat/pandora/POWER"
    command_topic: "cmnd/pandora/POWER"
    availability_topic: "tele/pandora/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
    optimistic: true
  - platform: mqtt
    name: "Phoebe"
    state_topic: "stat/phoebe/POWER"
    command_topic: "cmnd/phoebe/POWER"
    availability_topic: "tele/phoebe/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
    optimistic: true

sensor:
  - platform: mqtt
    name: "Ganymede Energy Today"
    state_topic: "tele/ganymede/SENSOR"
    value_template: "{{ value_json.ENERGY.Today | round(1) }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Ganymede Energy Yesterday"
    state_topic: "tele/ganymede/SENSOR"
    value_template: "{{ value_json.ENERGY.Yesterday | round(1) }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Ganymede Energy Total"
    state_topic: "tele/ganymede/SENSOR"
    value_template: "{{ value_json.ENERGY.Total | round(1) }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Ganymede Power"
    state_topic: "tele/ganymede/SENSOR"
    value_template: "{{ value_json.ENERGY.Power | round(1) }}"
    unit_of_measurement: "Watts"
  - platform: mqtt
    name: "Ganymede Power Factor"
    state_topic: "tele/ganymede/SENSOR"
    value_template: "{{ value_json.ENERGY.Factor | round(2) }}"
  - platform: mqtt
    name: "Ganymede Current"
    state_topic: "tele/ganymede/SENSOR"
    value_template: "{{ value_json.ENERGY.Current | round(2) }}"
    unit_of_measurement: "Amps"
  - platform: mqtt
    name: "Ganymede Voltage"
    state_topic: "tele/ganymede/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage | round(0) }}"
    unit_of_measurement: "Volts"

  - platform: mqtt
    name: "Callisto Temperature"
    state_topic: "tele/callisto/SENSOR"
    value_template: "{{ value_json['DHT22'].Temperature }}"
    unit_of_measurement: "°C"
  - platform: statistics
    entity_id: sensor.callisto_temperature
    name: "First Floor Temperature"
  - platform: mqtt
    name: "Callisto Humidity"
    state_topic: "tele/callisto/SENSOR"
    value_template: "{{ value_json['DHT22'].Humidity }}"
    unit_of_measurement: "%"
  - platform: statistics
    entity_id: sensor.callisto_humidity
    name: "First Floor Humidity"

  - platform: mqtt
    name: "Mimas Temperature"
    state_topic: "tele/mimas/SENSOR"
    value_template: "{{ value_json['DHT22'].Temperature }}"
    unit_of_measurement: "°C"
  - platform: statistics
    entity_id: sensor.mimas_temperature
    name: "Common Room Temperature"
  - platform: mqtt
    name: "Mimas Humidity"
    state_topic: "tele/mimas/SENSOR"
    value_template: "{{ value_json['DHT22'].Humidity }}"
    unit_of_measurement: "%"
  - platform: statistics
    entity_id: sensor.mimas_humidity
    name: "Common Room Humidity"

  - platform: mqtt
    name: "Pandora Temperature"
    state_topic: "tele/pandora/SENSOR"
    value_template: "{{ value_json['DHT22'].Temperature }}"
    unit_of_measurement: "°C"
  - platform: statistics
    entity_id: sensor.pandora_temperature
    name: "Bedroom Temperature"
  - platform: mqtt
    name: "Pandora Humidity"
    state_topic: "tele/pandora/SENSOR"
    value_template: "{{ value_json['DHT22'].Humidity }}"
    unit_of_measurement: "%"
  - platform: statistics
    entity_id: sensor.pandora_humidity
    name: "Bedroom Humidity"

binary_sensor:
  - platform: trend
    sensors:
      common_room_warmer:
        friendly_name: 'Common Room Warmer'
        entity_id: sensor.mimas_temperature
        sample_duration: 180
        min_gradient: 0.00044444444
        device_class: heat
      common_room_colder:
        friendly_name: 'Common Room Colder'
        entity_id: sensor.mimas_temperature
        sample_duration: 180
        min_gradient: -0.00044444444
        device_class: cold
  - platform: trend
    sensors:
      first_floor_warmer:
        friendly_name: 'First Floor Warmer'
        entity_id: sensor.callisto_temperature
        sample_duration: 180
        min_gradient: 0.00044444444
        device_class: heat
      first_floor_colder:
        friendly_name: 'First Floor Colder'
        entity_id: sensor.callisto_temperature
        sample_duration: 180
        min_gradient: -0.00044444444
        device_class: cold
  - platform: trend
    sensors:
      bedroom_warmer:
        friendly_name: 'Bedroom Warmer'
        entity_id: sensor.pandora_temperature
        sample_duration: 180
        min_gradient: 0.00044444444
        device_class: heat
      bedroom_colder:
        friendly_name: 'Bedroom Colder'
        entity_id: sensor.pandora_temperature
        sample_duration: 180
        min_gradient: -0.00044444444
        device_class: cold

group:
  sonoff:
    name: "Sonoff"
    icon: mdi:power-plug
    control: hidden
    entities:
      - switch.ganymede
      - switch.callisto
      - switch.mimas
      - light.pandora
      - light.phoebe
      - switch.calypso
      - switch.sva
      - switch.svb

automation:

  # - alias: "Auto Double Subwoofer On"
  #   trigger:
  #     - platform: template
  #       value_template: '{% if is_state("sensor.denon_source", "Music") or is_state("sensor.denon_source", "Apple TV") or is_state("sensor.denon_source", "Dune") or is_state("sensor.denon_source", "Biscuit") or is_state("sensor.denon_source", "DVD") or is_state("sensor.denon_source", "AUX") or is_state("sensor.denonsourcecheck", "USB/IPOD") %}true{% else %}false{% endif %}'
  #   condition:
  #     - condition: template
  #       value_template: '{{ is_state("switch.titan", "on") and is_state("media_player.denon", "on") }}'
  #   action:
  #     - service: switch.turn_on
  #       entity_id: switch.mimas

  # - alias: "Auto Double Subwoofer Off"
  #   trigger:
  #     - platform: template
  #       value_template: '{% if is_state("sensor.denon_source", "Cable TV") or is_state("sensor.denon_source", "TV") or is_state("sensor.denon_source", "TUNER") or is_state("sensor.denonsourcecheck", "Internet Radio") or is_state("sensor.denonsourcecheck", "NET") %}true{% else %}false{% endif %}'
  #     - platform: state
  #       entity_id: switch.titan
  #       from: 'on'
  #       to: 'off'
  #     - platform: state
  #       entity_id: media_player.denon
  #       from: 'on'
  #       to: 'off'
  #   action:
  #     - service: switch.turn_off
  #       entity_id: switch.mimas
