switch:
  - platform: mqtt
    name: "Ganymede"
    state_topic: "stat/ganymede/POWER"
    command_topic: "cmnd/ganymede/POWER"
    availability_topic: "tele/ganymede/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Callisto"
    state_topic: "stat/callisto/POWER"
    command_topic: "cmnd/callisto/POWER"
    availability_topic: "tele/callisto/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Mimas"
    state_topic: "stat/mimas/POWER"
    command_topic: "cmnd/mimas/POWER"
    availability_topic: "tele/mimas/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Phoebe"
    state_topic: "stat/phoebe/POWER"
    command_topic: "cmnd/phoebe/POWER"
    availability_topic: "tele/phoebe/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

light:
  - platform: mqtt
    name: "Pandora"
    state_topic: "stat/pandora/POWER"
    command_topic: "cmnd/pandora/POWER"
    availability_topic: "tele/pandora/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Calypso"
    state_topic: "stat/calypso/POWER"
    command_topic: "cmnd/calypso/POWER"
    availability_topic: "tele/calypso/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

sensor:
  - platform: mqtt
    name: "Ganymede Energy Today"
    state_topic: "tele/ganymede/ENERGY"
    value_template: "{{ value_json.Today | round(1) }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Ganymede Energy Yesterday"
    state_topic: "tele/ganymede/ENERGY"
    value_template: "{{ value_json.Yesterday | round(1) }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Ganymede Energy Total"
    state_topic: "tele/ganymede/ENERGY"
    value_template: "{{ value_json.Total | round(1) }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Ganymede Power"
    state_topic: "tele/ganymede/ENERGY"
    value_template: "{{ value_json.Power | round(1) }}"
    unit_of_measurement: "Watts"
  - platform: mqtt
    name: "Ganymede Power Factor"
    state_topic: "tele/ganymede/ENERGY"
    value_template: "{{ value_json.Factor | round(2) }}"
  - platform: mqtt
    name: "Ganymede Current"
    state_topic: "tele/ganymede/ENERGY"
    value_template: "{{ value_json.Current | round(2) }}"
    unit_of_measurement: "Amps"
  - platform: mqtt
    name: "Ganymede Voltage"
    state_topic: "tele/ganymede/ENERGY"
    value_template: "{{ value_json.Voltage | round(0) }}"
    unit_of_measurement: "Volts"
  - platform: mqtt
    name: "Pandora Temperature"
    state_topic: "tele/pandora/SENSOR"
    value_template: "{{ value_json['DHT22'].Temperature }}"
    unit_of_measurement: "°C"
  - platform: statistics
    entity_id: sensor.pandora_temperature
    name: "Bedroom Temperature"
  - platform: mqtt
    name: "Pandora Humidity"
    state_topic: "tele/pandora/SENSOR"
    value_template: "{{ value_json['DHT22'].Humidity }}"
    unit_of_measurement: "%"
  - platform: statistics
    entity_id: sensor.pandora_humidity
    name: "Bedroom Humidity"

automation:

  - alias: "Auto Double Subwoofer On"
    trigger:
      - platform: template
        value_template: '{% if is_state("sensor.denonsourcecheck", "Music") or is_state("sensor.denonsourcecheck", "MPLAY") or is_state("sensor.denonsourcecheck", "BD") or is_state("sensor.denonsourcecheck", "DVD") or is_state("sensor.denonsourcecheck", "AUX1") or is_state("sensor.denonsourcecheck", "USB/IPOD") %}true{% else %}false{% endif %}'
    condition:
      - condition: template
        value_template: '{{ is_state("switch.titan", "on") and is_state("media_player.denon", "on") }}'
    action:
      - service: switch.turn_on
        entity_id: switch.mimas

  - alias: "Auto Double Subwoofer Off"
    trigger:
      - platform: template
        value_template: '{% if is_state("sensor.denonsourcecheck", "SAT/CBL") or is_state("sensor.denonsourcecheck", "Game") or is_state("sensor.denonsourcecheck", "TV") or is_state("sensor.denonsourcecheck", "TUNER") or is_state("sensor.denonsourcecheck", "Internet Radio") or is_state("sensor.denonsourcecheck", "NET") %}true{% else %}false{% endif %}'
      - platform: state
        entity_id: switch.titan
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: media_player.denon
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.mimas

  # - alias: "Auto Fan Saturn On"
  #   trigger:
  #     - platform: template
  #       value_template: '{{ states.sensor.average_temperature.state | float > 41 }}'
  #   action:
  #     - service: switch.turn_on
  #       entity_id: switch.ganymede

  # - alias: "Auto Fan Saturn Off"
  #   trigger:
  #     - platform: template
  #       value_template: '{{ states.sensor.average_temperature.state | float < 41 }}'
  #   action:
  #     - service: switch.turn_off
  #       entity_id: switch.ganymede
