switch:
  - platform: tplink
    host: !secret tplink_ip_1
    name: "titan"
    enable_leds: True
  - platform: tplink
    host: !secret tplink_ip_2
    name: "europa"
    enable_leds: True

sensor:
  - platform: template
    sensors:
      titan_current_consumption:
        friendly_name: "Common Room Power"
        icon_template: mdi:power-socket-us
        value_template: '{% if states.switch.titan.attributes.current_consumption %}{{ states.switch.titan.attributes.current_consumption.split(" ")[0] | round(1) }}{% else %}false{% endif %}'
        unit_of_measurement: 'Watts'
        entity_id:
          - switch.titan
      titan_current:
        friendly_name: "Common Room Current"
        icon_template: mdi:pulse
        value_template: '{% if states.switch.titan.attributes.current %}{{ states.switch.titan.attributes.current.split(" ")[0] | round(2) }}{% else %}false{% endif %}'
        unit_of_measurement: 'Amps'
        entity_id:
          - switch.titan
      titan_voltage:
        friendly_name: "Common Room Voltage"
        icon_template: mdi:tower-fire
        value_template: '{% if states.switch.titan.attributes.voltage %}{{ states.switch.titan.attributes.voltage.split(" ")[0] | round(0) }}{% else %}false{% endif %}'
        unit_of_measurement: 'Volts'
        entity_id:
          - switch.titan
  - platform: template
    sensors:
      europa_current_consumption:
        friendly_name: "Bedroom Power"
        icon_template: mdi:power-socket-us
        value_template: '{% if states.switch.europa.attributes.current_consumption %}{{ states.switch.europa.attributes.current_consumption.split(" ")[0] | round(1) }}{% else %}false{% endif %}'
        unit_of_measurement: 'Watts'
        entity_id:
          - switch.europa
      europa_current:
        friendly_name: "Bedroom Current"
        icon_template: mdi:pulse
        value_template: '{% if states.switch.europa.attributes.current %}{{ states.switch.europa.attributes.current.split(" ")[0] | round(2) }}{% else %}false{% endif %}'
        unit_of_measurement: 'Amps'
        entity_id:
          - switch.europa
      europa_voltage:
        friendly_name: "Bedroom Voltage"
        icon_template: mdi:tower-fire
        value_template: '{% if states.switch.europa.attributes.voltage %}{{ states.switch.europa.attributes.voltage.split(" ")[0] | round(0) }}{% else %}false{% endif %}'
        unit_of_measurement: 'Volts'
        entity_id:
          - switch.europa

# binary_sensor:
#   - platform: template
#     sensors:
#       washer:
#         friendly_name: "Washer"
#         value_template: '{% if not is_state_attr("switch.europa", "current_consumption", "") %}{{ states.switch.europa.attributes.current_consumption.split(" ")[0] | round(1) | float < 1.5 }}{% endif %}'
#         entity_id:
#           - switch.europa

# automation:
#
#   - alias: "Washer is Completed"
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.washer
#         from: 'off'
#         to: 'on'
#         for:
#           minutes: 2
#     action:
#       - service: script.notifying
#         data:
#           email: "false"
#           tv: "true"
#           speak: "true"
#           audio: "pip"
#           light: "once"
#           mobile: "jue"
#           title: "Washing machine has finished its current job"
#           message: 'Washing machine has finished its current job [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'

#   - alias: "Smart Plug Titan On"
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.titan_current_consumption
#         value_template: '{{ states.sensor.titan_current_consumption.state }}'
#         above: 150
#     action:
#       - service: notify.email
#         data_template:
#           title: "Titan is running"
#           message: "Titan is running with the current electricity consumption of {{ states.sensor.titan_current_consumption.state }} W"
#
#   - alias: "Smart Plug Titan Off"
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.titan_current_consumption
#         value_template: '{{ states.sensor.titan_current_consumption.state }}'
#         below: 10
#     action:
#       - service: notify.email
#         data_template:
#           title: "Titan is not running"
#           message: "Titan is not running with the current electricity consumption of {{ states.sensor.titan_current_consumption.state }} W"
#
#   - alias: "Smart Plug Europa On"
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.europa_current_consumption
#         value_template: '{{ states.sensor.europa_current_consumption.state }}'
#         above: 30
#     action:
#       - service: notify.email
#         data_template:
#           title: "Europa is running"
#           message: "Europa is running with the current electricity consumption of {{ states.sensor.europa_current_consumption.state }} W"
#
#   - alias: "Smart Plug Europa Off"
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.europa_current_consumption
#         value_template: '{{ states.sensor.europa_current_consumption.state }}'
#         below: 5
#     action:
#       - service: notify.email
#         data_template:
#           title: "Europa is not running"
#           message: "Europa is not running with the current electricity consumption of {{ states.sensor.europa_current_consumption.state }} W"
