switch:
  - platform: tplink
    host: !secret tplink_ip_1
  - platform: tplink
    host: !secret tplink_ip_2

sensor:
  - platform: template
    sensors:
      titan_current_consumption:
        friendly_name: "Common Room Power"
        icon_template: mdi:power-plug
        value_template: '{{ states.switch.titan.attributes["Current consumption"].split(" ")[0] }}'
        unit_of_measurement: 'Watts'
      titan_current:
        friendly_name: "Common Room Electric"
        icon_template: mdi:power-socket
        value_template: '{{ states.switch.titan.attributes["Current"].split(" ")[0] }}'
        unit_of_measurement: 'Amps'
      titan_voltage:
        friendly_name: "Common Room Voltage"
        icon_template: mdi:tower-fire
        value_template: '{{ states.switch.titan.attributes["Voltage"].split(" ")[0] }}'
        unit_of_measurement: 'Volts'
  - platform: template
    sensors:
      europa_current_consumption:
        friendly_name: "Bedroom Power"
        icon_template: mdi:power-plug
        value_template: '{{ states.switch.europa.attributes["Current consumption"].split(" ")[0] }}'
        unit_of_measurement: 'Watts'
      europa_current:
        friendly_name: "Bedroom Electric"
        icon_template: mdi:power-socket
        value_template: '{{ states.switch.europa.attributes["Current"].split(" ")[0] }}'
        unit_of_measurement: 'Amps'
      europa_voltage:
        friendly_name: "Bedroom Voltage"
        icon_template: mdi:tower-fire
        value_template: '{{ states.switch.europa.attributes["Voltage"].split(" ")[0] }}'
        unit_of_measurement: 'Volts'

# automation:
#
#   - alias: "Smart Plug Titan On"
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.titan_current_consumption
#         value_template: '{{ states.sensor.titan_current_consumption.state }}'
#         above: 150
#     action:
#       - service: notify.email
#         data_template:
#           title: "Titan is running"
#           message: "Titan is running with the current electricity consumption of {{ states.sensor.titan_current_consumption.state }} W"
#
#   - alias: "Smart Plug Titan Off"
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.titan_current_consumption
#         value_template: '{{ states.sensor.titan_current_consumption.state }}'
#         below: 10
#     action:
#       - service: notify.email
#         data_template:
#           title: "Titan is not running"
#           message: "Titan is not running with the current electricity consumption of {{ states.sensor.titan_current_consumption.state }} W"
#
#   - alias: "Smart Plug Europa On"
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.europa_current_consumption
#         value_template: '{{ states.sensor.europa_current_consumption.state }}'
#         above: 30
#     action:
#       - service: notify.email
#         data_template:
#           title: "Europa is running"
#           message: "Europa is running with the current electricity consumption of {{ states.sensor.europa_current_consumption.state }} W"
#
#   - alias: "Smart Plug Europa Off"
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.europa_current_consumption
#         value_template: '{{ states.sensor.europa_current_consumption.state }}'
#         below: 5
#     action:
#       - service: notify.email
#         data_template:
#           title: "Europa is not running"
#           message: "Europa is not running with the current electricity consumption of {{ states.sensor.europa_current_consumption.state }} W"
