zone:
  - name: Home
    icon: mdi:home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 100
  - name: Benjawan
    icon: mdi:home-variant
    latitude: !secret latitude_benjawan
    longitude: !secret longitude_benjawan
    radius: 100
  - name: Malaiwan
    icon: mdi:home-modern
    latitude: !secret latitude_malaiwan
    longitude: !secret longitude_malaiwan
    radius: 100
  # - name: Nonthaburi
  #   icon: mdi:castle
  #   latitude: !secret latitude_nonthaburi
  #   longitude: !secret longitude_nonthaburi
  #   radius: 100

proximity:
  pe_home:
    zone: home
    devices:
      - device_tracker.pesiphone6
    tolerance: 1000
    unit_of_measurement: m
  jue_home:
    zone: home
    devices:
      - device_tracker.juesiphone6splus
    tolerance: 1000
    unit_of_measurement: m
  jue_malaiwan:
    zone: malaiwan
    devices:
      - device_tracker.juesiphone6splus
    tolerance: 1000
    unit_of_measurement: m
  pe_benjawan:
    zone: benjawan
    devices:
      - device_tracker.pesiphone6
    tolerance: 1000
    unit_of_measurement: m

camera:
  - platform: generic
    name: Current Location Pe
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.pesiphone6.attributes.latitude }},{{ states.device_tracker.pesiphone6.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:P%7C{{ states.device_tracker.pesiphone6.attributes.latitude }},{{ states.device_tracker.pesiphone6.attributes.longitude }}
    limit_refetch_to_url_change: true
  - platform: generic
    name: Current Location Jue
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.juesiphone6splus.attributes.latitude }},{{ states.device_tracker.juesiphone6splus.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:P%7C{{ states.device_tracker.juesiphone6splus.attributes.latitude }},{{ states.device_tracker.juesiphone6splus.attributes.longitude }}
    limit_refetch_to_url_change: true
  # - platform: generic
  #   name: Current Location BMW
  #   still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.pesipodtouch4.attributes.latitude }},{{ states.device_tracker.pesipodtouch4.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:red%7Clabel:P%7C{{ states.device_tracker.pesipodtouch4.attributes.latitude }},{{ states.device_tracker.pesipodtouch4.attributes.longitude }}
  #   limit_refetch_to_url_change: true

sensor:
  - platform: google_travel_time
    name: "Home to Benjy"
    api_key: !secret google_travel_time_api_key
    origin: zone.home
    destination: zone.benjawan
    options:
      mode: driving
      units: metric
  - platform: google_travel_time
    name: "Benjy to Home"
    api_key: !secret google_travel_time_api_key
    origin: zone.benjawan
    destination: zone.home
    options:
      mode: driving
      units: metric
  - platform: google_travel_time
    name: "Home to Malaiwan"
    api_key: !secret google_travel_time_api_key
    origin: zone.home
    destination: zone.malaiwan
    options:
      mode: driving
      units: metric
  - platform: google_travel_time
    name: "Malaiwan to Home"
    api_key: !secret google_travel_time_api_key
    origin: zone.malaiwan
    destination: zone.home
    options:
      mode: driving
      units: metric
  - platform: template
    sensors:
      location_pe:
        friendly_name: "Location Pe"
        icon_template: mdi:map-marker
        value_template: '{% if is_state("device_tracker.pesiphone6", "home") and is_state("device_tracker.iphone_pe", "home") %}Home{% else %}Away{% endif %}'
      location_jue:
        friendly_name: "Location Jue"
        icon_template: mdi:map-marker
        value_template: '{% if is_state("device_tracker.juesiphone6splus", "home") and is_state("device_tracker.iphone_jue", "home") %}Home{% else %}Away{% endif %}'

automation:
  - alias: "Jue Leaves Home"
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'home'
        to: 'not_home'
        for:
          seconds: 45
    condition:
      - condition: state
        entity_id: sensor.location_jue
        state: 'Away'
    action:
      - service: script.flashing_long
        data:
          title: "Jue has left home"
          message: 'Jue has left home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_pesiphone6
        data:
          title: "Jue has left home"
          message: 'Jue has left home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Jue 3km Away From Home"
    trigger:
      - platform: numeric_state
        entity_id: proximity.jue_home
        below: 3200
        above: 2800
    action:
      - service: script.flashing_once
        data:
          title: "Jue is 3km away from Home"
          message: 'Jue is 3km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_pesiphone6
        data:
          title: "Jue is 3km away from Home"
          message: 'Jue is 3km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Jue 2km Away From Home"
    trigger:
      - platform: numeric_state
        entity_id: proximity.jue_home
        below: 2200
        above: 1800
    action:
      - service: script.flashing_once
        data:
          title: "Jue is 2km away from Home"
          message: 'Jue is 2km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_pesiphone6
        data:
          title: "Jue is 2km away from Home"
          message: 'Jue is 2km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Jue 1km Away From Home"
    trigger:
      - platform: numeric_state
        entity_id: proximity.jue_home
        below: 1200
        above: 800
    action:
      - service: script.flashing_once
        data:
          title: "Jue is 1km away from Home"
          message: 'Jue is 1km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_pesiphone6
        data:
          title: "Jue is 1km away from Home"
          message: 'Jue is 1km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Jue Arrives Home"
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'not_home'
        to: 'home'
        for:
          seconds: 45
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: proximity.jue_home
          below: 50
        - condition: state
          entity_id: sensor.location_jue
          state: 'Home'
    action:
      - service: script.flashing_short
        data:
          title: "Jue has arrived home"
          message: 'Jue has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_pesiphone6
        data:
          title: "Jue has arrived home"
          message: 'Jue has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Jue Leaves Malaiwan"
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'Malaiwan'
        to: 'not_home'
        for:
          seconds: 45
    action:
      - service: script.flashing_long
        data:
          title: "Jue has left Malaiwan"
          message: 'Jue has left Malaiwan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_pesiphone6
        data:
          title: "Jue has left Malaiwan"
          message: 'Jue has left Malaiwan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Jue Arrives Malaiwan"
    trigger:
      - platform: state
        entity_id: device_tracker.juesiphone6splus
        from: 'not_home'
        to: 'Malaiwan'
        for:
          seconds: 45
    condition:
      - condition: numeric_state
        entity_id: proximity.jue_malaiwan
        below: 50
    action:
      - service: script.flashing_short
        data:
          title: "Jue has arrived Malaiwan"
          message: 'Jue has arrived Malaiwan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_pesiphone6
        data:
          title: "Jue has arrived Malaiwan"
          message: 'Jue has arrived Malaiwan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Pe Leaves Home"
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'home'
        to: 'not_home'
        for:
          seconds: 45
    condition:
      - condition: state
        entity_id: sensor.location_pe
        state: 'Away'
    action:
      - service: script.flashing_long
        data:
          title: "Pe has left home"
          message: 'Pe has left home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe has left home"
          message: 'เป้ออกจากบ้านแล้ว [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Pe 3km Away From Home"
    trigger:
      - platform: numeric_state
        entity_id: proximity.pe_home
        below: 3200
        above: 2800
    action:
      - service: script.flashing_once
        data:
          title: "Pe is 3km away from Home"
          message: 'Pe is 3km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe is 3km away from Home"
          message: 'เป้อยู่ห่างจากบ้านประมาณ 3 กม. [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Pe 2km Away From Home"
    trigger:
      - platform: numeric_state
        entity_id: proximity.pe_home
        below: 2200
        above: 1800
    action:
      - service: script.flashing_once
        data:
          title: "Pe is 2km away from Home"
          message: 'Pe is 2km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe is 2km away from Home"
          message: 'เป้อยู่ห่างจากบ้านประมาณ 2 กม. [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Pe 1km Away From Home"
    trigger:
      - platform: numeric_state
        entity_id: proximity.pe_home
        below: 1200
        above: 800
    action:
      - service: script.flashing_once
        data:
          title: "Pe is 1km away from Home"
          message: 'Pe is 1km away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe is 1km away from Home"
          message: 'เป้อยู่ห่างจากบ้านประมาณ 1 กม. [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Pe Arrives Home"
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'not_home'
        to: 'home'
        for:
          seconds: 45
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: proximity.pe_home
          below: 50
        - condition: state
          entity_id: sensor.location_pe
          state: 'Home'
    action:
      - service: script.flashing_short
        data:
          title: "Pe has arrived home"
          message: 'Pe has arrived home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe has arrived home"
          message: 'เป้กลับมาถึงบ้านแล้ว [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Pe Leaves Benjawan"
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'Benjawan'
        to: 'not_home'
        for:
          seconds: 45
    action:
      - service: script.flashing_long
        data:
          title: "Pe has left Benjawan"
          message: 'Pe has left Benjawan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe has left Benjawan"
          message: 'เป้ออกจากบ้านเบญแล้ว [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  - alias: "Pe Arrives Benjawan"
    trigger:
      - platform: state
        entity_id: device_tracker.pesiphone6
        from: 'not_home'
        to: 'Benjawan'
        for:
          seconds: 45
    condition:
      - condition: numeric_state
        entity_id: proximity.pe_benjawan
        below: 50
    action:
      - service: script.flashing_short
        data:
          title: "Pe has arrived Benjawan"
          message: 'Pe has arrived Benjawan [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
      - service: script.notify_juesiphone6splus
        data:
          title: "Pe has arrived Benjawan"
          message: 'เป้ถึงบ้านเบญแล้ว [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  # - alias: "Benjy Arrives"
  #   trigger:
  #     - platform: state
  #       entity_id: device_tracker.benjysiphone6
  #       from: 'not_home'
  #       to: 'home'
  #       for:
  #         seconds: 45
  #   action:
  #     - service: script.flashing_long
  #       data:
  #         title: "Benjy arrives"
  #         message: 'Benjy visits and she has arrived [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  #     - service: script.notify_pesiphone6
  #       data:
  #         title: "Benjy arrives"
  #         message: 'Benjy visits and she has arrived [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  #     - service: input_select.select_option
  #       data:
  #         entity_id: input_select.homemode
  #         option: Visitor
  # - alias: "Benjy Leaves"
  #   trigger:
  #     - platform: state
  #       entity_id: device_tracker.benjysiphone6
  #       from: 'home'
  #       to: 'not_home'
  #       for:
  #         seconds: 45
  #   action:
  #     - service: script.flashing_short
  #       data:
  #         title: "Benjy leaves"
  #         message: 'Benjy has left [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  #     - service: script.notify_pesiphone6
  #       data:
  #         title: "Benjy leaves"
  #         message: 'Benjy has left [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
  #     - service: input_select.select_previous
  #       data:
  #         entity_id: input_select.homemode

  # - alias: "Testing Pe 2m Away From Home"
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: proximity.pe_home
  #       below: 50
  #       above: 2
  #   action:
  #     - service: script.flashing_short
  #       data:
  #         title: "Testing: Pe is 2m away from Home"
  #         message: 'Testing: Pe is 2m away from Home [{{now().strftime("%d.%m.%y")}} {{now().strftime("%H:%M")}}]'
