input_boolean:
  peathome:
    name: Pe is at Home
    initial: off
    icon: mdi:home
  jueathome:
    name: Jue is at Home
    initial: off
    icon: mdi:home
  benjyathome:
    name: Benjy is at Home
    initial: off
    icon: mdi:home
  jueatmalaiwan:
    name: Jue is at Malaiwan
    initial: off
    icon: mdi:flower
  jueatbigc:
    name: Jue is at Big C Extra On-Nut
    initial: off
    icon: mdi:store
  peatbigc:
    name: Pe is at Big C Extra On-Nut
    initial: off
    icon: mdi:store
  peatpause:
    name: Pe is at Pause 103
    initial: off
    icon: mdi:home-city
  jueatpause:
    name: Jue is at Pause 103
    initial: off
    icon: mdi:home-city
  peatnichemono:
    name: Pe is at Niche Mono Bearing
    initial: off
    icon: mdi:home-city
  jueatnichemono:
    name: Jue is at Niche Mono Bearing
    initial: off
    icon: mdi:home-city
  mpd_silence:
    name: Silence speeching
    initial: off
    icon: mdi:volume-off

input_select:
  homemode:
    name: "Home Mode"
    options:
     - Home
     - Away (Pe)
     - Away (Jue)
     - Away
     - Vacation
     - Visitor
    icon: mdi:home-outline

zone:
  - name: Home
    icon: mdi:home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 250
  - name: Benjys
    icon: mdi:home-variant
    latitude: !secret latitude_benjys
    longitude: !secret longitude_benjys
    radius: 250
  - name: Malaiwan
    icon: mdi:home-modern
    latitude: !secret latitude_malaiwan
    longitude: !secret longitude_malaiwan
    radius: 250
  - name: Seacon Square
    icon: mdi:shopping
    latitude: !secret latitude_seaconsquare
    longitude: !secret longitude_seaconsquare
    radius: 250
  - name: Paradise Park
    icon: mdi:shopping
    latitude: !secret latitude_paradisepark
    longitude: !secret longitude_paradisepark
    radius: 250
  - name: Central Bangna
    icon: mdi:shopping
    latitude: !secret latitude_centralbangna
    longitude: !secret longitude_centralbangna
    radius: 250
  - name: Foodland
    icon: mdi:food
    latitude: !secret latitude_foodland
    longitude: !secret longitude_foodland
    radius: 250
  - name: Pause 103
    icon: mdi:home-city
    latitude: !secret latitude_pause103
    longitude: !secret longitude_pause103
    radius: 250
  # - name: Big C Extra On-Nut
  #   icon: mdi:store
  #   latitude: !secret latitude_bigcextraonnut
  #   longitude: !secret longitude_bigcextraonnut
  #   radius: 250
  - name: Niche Mono Bearing
    icon: mdi:home-city
    latitude: !secret latitude_nichemono_bearing
    longitude: !secret longitude_nichemono_bearing
    radius: 250

group:
  devices:
    name: "Devices"
    icon: mdi:account
    entities:
      - device_tracker.pesiphone13pro
      - device_tracker.pesipadmini5
      - device_tracker.juesiphonexsmax
      - device_tracker.juesipadmini4
      - device_tracker.benjysiphone11
      - device_tracker.sinbad
      - input_boolean.peathome
      - input_boolean.jueathome
      - input_boolean.jueatmalaiwan
      - input_boolean.peatpause
      - input_boolean.jueatpause
      - input_boolean.peatbigc
      - input_boolean.jueatbigc


automation:

  - alias: "Set Home Mode"
    initial_state: "on"
    trigger:
      - platform: template
        value_template:  '{{ is_state("input_boolean.peathome", "on") and is_state("input_boolean.jueathome", "on") }}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Home'

  - alias: "Set Away Mode Pe"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_boolean.peathome
        from: 'on'
        to: 'off'
        for:
          minutes: 2
      - platform: template
        value_template:  '{{ is_state("input_boolean.peatpause", "on") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.jueathome", "on") }}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Away (Pe)'
      - service: light.turn_off
        entity_id: group.hue_all
      - service: script.switch_to_off

  - alias: "Set Away Mode Jue"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_boolean.jueathome
        from: 'on'
        to: 'off'
        for:
          minutes: 2
      - platform: template
        value_template:  '{{ is_state("input_boolean.jueatmalaiwan", "on") }}'
      - platform: template
        value_template:  '{{ is_state("input_boolean.jueatpause", "on") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.peathome", "on") }}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Away (Jue)'
      - service: light.turn_off
        entity_id: group.hue_all


  - alias: "Set Vacation Mode Pe"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_boolean.peathome
        from: 'on'
        to: 'off'
        for:
          hours: 20
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.jueathome", "on") }}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Vacation'
      - service: light.turn_off
        entity_id: group.hue_all

  - alias: "Set Vacation Mode Jue"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_boolean.jueathome
        from: 'on'
        to: 'off'
        for:
          hours: 20
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.peathome", "on") }}'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Vacation'
      - service: light.turn_off
        entity_id: group.hue_all

  - alias: "Set Visitor Mode"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_boolean.benjyathome
        from: 'off'
        to: 'on'
        for:
          minutes: 2
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.homemode
          option: 'Visitor'

  - alias: "Pe is at Home"
    initial_state: "on"
    trigger:
      - platform: template
        value_template: '{{ is_state("device_tracker.pesiphone13pro", "home") }}'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.peathome
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatpause
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatbigc
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatnichemono
      - service: mqtt.publish
        data:
          topic: 'location/pe' 
          payload: 'home'

  - alias: "Pe is not at Home"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ not is_state("device_tracker.pesiphone13pro", "home") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.peathome", "on") }}'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peathome
      - service: mqtt.publish
        data:
          topic: 'location/pe' 
          payload: 'not_home'

  - alias: "Jue is at Home"
    initial_state: "on"
    trigger:
      - platform: template
        value_template: '{{ is_state("device_tracker.juesiphonexsmax", "home") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.jueathome", "off") }}'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.jueathome
      - service: mqtt.publish
        data:
          topic: 'location/jue' 
          payload: 'home'
      
  - alias: "Jue is not at Home"
    initial_state: "on"
    trigger:
      - platform: template
        value_template: '{{ not is_state("device_tracker.juesiphonexsmax", "home") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.jueathome", "on") }}'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.jueathome
      - service: mqtt.publish
        data:
          topic: 'location/jue' 
          payload: 'not_home'
      
  - alias: "Benjy is at Home"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template:  '{{ states.device_tracker.benjysiphone11.state == "home" }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.benjyathome", "off") }}'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.benjyathome
      - service: mqtt.publish
        data:
          topic: 'location/benjy' 
          payload: 'home'

  - alias: "Benjy is not at Home"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template:  '{{ states.device_tracker.benjysiphone11.state != "home" }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.benjyathome", "on") }}'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.benjyathome
      - service: mqtt.publish
        data:
          topic: 'location/benjy' 
          payload: 'not_home'

  - alias: "Pe is at Big C On-Nut"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ is_state("device_tracker.pesiphone13pro", "Big C Extra On-Nut") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.peatbigc", "off") }}'
      - condition: template
        value_template: '{% if state_attr("automation.pe_is_at_big_c_on-nut", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.pe_is_at_big_c_on-nut.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.pe_is_at_big_c_on-nut", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.peatbigc
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peathome
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatpause
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatnichemono
      - service: mqtt.publish
        data:
          topic: 'location/pe' 
          payload: 'bigc'
      
  - alias: "Pe is not at Big C On-Nut"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ not is_state("device_tracker.pesiphone13pro", "Big C Extra On-Nut") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.peatbigc", "on") }}'
      - condition: template
        value_template: '{% if state_attr("automation.pe_is_not_at_big_c_on-nut", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.pe_is_not_at_big_c_on-nut.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.pe_is_not_at_big_c_on-nut", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatbigc
      - service: mqtt.publish
        data:
          topic: 'location/pe' 
          payload: 'not_home'

  - alias: "Pe is at Niche Mono Bearing"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ is_state("device_tracker.pesiphone13pro", "Niche Mono Bearing") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.peatnichemono", "off") }}'
      - condition: template
        value_template: '{% if state_attr("automation.pe_is_at_niche_mono_bearing", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.pe_is_at_niche_mono_bearing.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.pe_is_at_niche_mono_bearing", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.peatnichemono
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peathome
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatpause
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatbigc
      - service: mqtt.publish
        data:
          topic: 'location/pe' 
          payload: 'niche_mono_bearing'
      
  - alias: "Pe is not at Niche Mono Bearing"
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ not is_state("device_tracker.pesiphone13pro", "BNiche Mono Bearing") }}'
    condition:
      - condition: template
        value_template: '{{ is_state("input_boolean.peatnichemono", "on") }}'
      - condition: template
        value_template: '{% if state_attr("automation.pe_is_not_at_niche_mono_bearing", "last_triggered") == none %}{{ (as_timestamp(now())-as_timestamp(states.automation.pe_is_not_at_niche_mono_bearing.last_updated)) > 600 }}{% else %}{{ (as_timestamp(now())-as_timestamp(state_attr("automation.pe_is_not_at_niche_mono_bearing", "last_triggered"))) > 600 }}{% endif %}'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.peatnichemono
      - service: mqtt.publish
        data:
          topic: 'location/pe' 
          payload: 'not_home'

